var searchData=
[
  ['callwrapper',['CallWrapper',['../structcugip_1_1_cell_operation_with_global_state_1_1_call_wrapper.html',1,'cugip::CellOperationWithGlobalState']]],
  ['callwrapper_3c_20false_2c_20tdummy_20_3e',['CallWrapper&lt; false, TDummy &gt;',['../structcugip_1_1_cell_operation_with_global_state_1_1_call_wrapper_3_01false_00_01_t_dummy_01_4.html',1,'cugip::CellOperationWithGlobalState']]],
  ['callwrapper_3c_20true_2c_20tdummy_20_3e',['CallWrapper&lt; true, TDummy &gt;',['../structcugip_1_1_cell_operation_with_global_state_1_1_call_wrapper_3_01true_00_01_t_dummy_01_4.html',1,'cugip::CellOperationWithGlobalState']]],
  ['celloperation',['CellOperation',['../structcugip_1_1_cell_operation.html',1,'cugip']]],
  ['celloperationwithglobalstate',['CellOperationWithGlobalState',['../structcugip_1_1_cell_operation_with_global_state.html',1,'cugip']]],
  ['cellularautomaton',['CellularAutomaton',['../classcugip_1_1_cellular_automaton.html',1,'cugip']]],
  ['cellularautomatonbasecrtp',['CellularAutomatonBaseCRTP',['../classcugip_1_1_cellular_automaton_base_c_r_t_p.html',1,'cugip']]],
  ['cellularautomatonbasecrtp_3c_20asynccellularautomatonwithglobalstate_3c_20tgrid_2c_20tneighborhood_2c_20trule_2c_20tglobalstate_2c_20tsemiglobalstate_20_3e_2c_20trule_2c_20device_5fimage_3c_20tgrid_3a_3aelement_2c_20tgrid_3a_3acdimension_20_3e_2c_202_20_3e',['CellularAutomatonBaseCRTP&lt; AsyncCellularAutomatonWithGlobalState&lt; TGrid, TNeighborhood, TRule, TGlobalState, TSemiGlobalState &gt;, TRule, device_image&lt; TGrid::Element, TGrid::cDimension &gt;, 2 &gt;',['../classcugip_1_1_cellular_automaton_base_c_r_t_p.html',1,'cugip']]],
  ['cellularautomatonbasecrtp_3c_20asynccellularautomatonwithglobalstateandpointer_3c_20tgrid_2c_20tneighborhood_2c_20trule_2c_20tglobalstate_2c_20tsemiglobalstate_20_3e_2c_20trule_2c_20device_5fimage_3c_20tgrid_3a_3aelement_2c_20tgrid_3a_3acdimension_20_3e_2c_202_20_3e',['CellularAutomatonBaseCRTP&lt; AsyncCellularAutomatonWithGlobalStateAndPointer&lt; TGrid, TNeighborhood, TRule, TGlobalState, TSemiGlobalState &gt;, TRule, device_image&lt; TGrid::Element, TGrid::cDimension &gt;, 2 &gt;',['../classcugip_1_1_cellular_automaton_base_c_r_t_p.html',1,'cugip']]],
  ['cellularautomatonbasecrtp_3c_20cellularautomaton_3c_20tgrid_2c_20tneighborhood_2c_20trule_20_3e_2c_20trule_2c_20device_5fimage_3c_20tgrid_3a_3aelement_2c_20tgrid_3a_3acdimension_20_3e_20_3e',['CellularAutomatonBaseCRTP&lt; CellularAutomaton&lt; TGrid, TNeighborhood, TRule &gt;, TRule, device_image&lt; TGrid::Element, TGrid::cDimension &gt; &gt;',['../classcugip_1_1_cellular_automaton_base_c_r_t_p.html',1,'cugip']]],
  ['cellularautomatonbasecrtp_3c_20cellularautomatonwithglobalstate_3c_20tgrid_2c_20tneighborhood_2c_20trule_2c_20tglobalstate_20_3e_2c_20trule_2c_20device_5fimage_3c_20tgrid_3a_3aelement_2c_20tgrid_3a_3acdimension_20_3e_20_3e',['CellularAutomatonBaseCRTP&lt; CellularAutomatonWithGlobalState&lt; TGrid, TNeighborhood, TRule, TGlobalState &gt;, TRule, device_image&lt; TGrid::Element, TGrid::cDimension &gt; &gt;',['../classcugip_1_1_cellular_automaton_base_c_r_t_p.html',1,'cugip']]],
  ['cellularautomatonwithglobalstate',['CellularAutomatonWithGlobalState',['../classcugip_1_1_cellular_automaton_with_global_state.html',1,'cugip']]],
  ['channelsumfunctor',['ChannelSumFunctor',['../structcugip_1_1_channel_sum_functor.html',1,'cugip']]],
  ['checkerboardimageview',['CheckerBoardImageView',['../classcugip_1_1_checker_board_image_view.html',1,'cugip']]],
  ['choose',['Choose',['../structcugip_1_1_choose.html',1,'cugip']]],
  ['choose_3c_200_2c_20h_2c_20t_2e_2e_2e_20_3e',['Choose&lt; 0, H, T... &gt;',['../structcugip_1_1_choose_3_010_00_01_h_00_01_t_8_8_8_01_4.html',1,'cugip']]],
  ['choose_3c_20n_2c_20h_2c_20t_2e_2e_2e_20_3e',['Choose&lt; N, H, T... &gt;',['../structcugip_1_1_choose_3_01_n_00_01_h_00_01_t_8_8_8_01_4.html',1,'cugip']]],
  ['choose_3c_20n_2d1_2c_20t_2e_2e_2e_20_3e',['Choose&lt; N-1, T... &gt;',['../structcugip_1_1_choose.html',1,'cugip']]],
  ['clear_5fnonminima_5fplateaus_5fftor',['clear_nonminima_plateaus_ftor',['../structcugip_1_1clear__nonminima__plateaus__ftor.html',1,'cugip']]],
  ['coherence_5fenhancing_5fdiffusion',['coherence_enhancing_diffusion',['../classcugip_1_1coherence__enhancing__diffusion.html',1,'cugip']]],
  ['column_5faccessor',['column_accessor',['../classcugip_1_1column__accessor.html',1,'cugip']]],
  ['computationstep',['ComputationStep',['../structcugip_1_1_relabel_1_1_computation_step.html',1,'cugip::Relabel']]],
  ['computationstep_3c_20relabelimplementation_3a_3anaive_2c_20thelper_20_3e',['ComputationStep&lt; RelabelImplementation::Naive, tHelper &gt;',['../structcugip_1_1_relabel_1_1_computation_step_3_01_relabel_implementation_1_1_naive_00_01t_helper_01_4.html',1,'cugip::Relabel']]],
  ['computationstep_3c_20relabelimplementation_3a_3aoptimizednaive_2c_20thelper_20_3e',['ComputationStep&lt; RelabelImplementation::OptimizedNaive, tHelper &gt;',['../structcugip_1_1_relabel_1_1_computation_step_3_01_relabel_implementation_1_1_optimized_naive_00_01t_helper_01_4.html',1,'cugip::Relabel']]],
  ['compute_5fdiffusion_5ftensor_5fftor',['compute_diffusion_tensor_ftor',['../structcugip_1_1compute__diffusion__tensor__ftor.html',1,'cugip']]],
  ['compute_5fstructural_5ftensor_5fftor',['compute_structural_tensor_ftor',['../structcugip_1_1compute__structural__tensor__ftor.html',1,'cugip']]],
  ['connectedcomponentlabelingrule',['ConnectedComponentLabelingRule',['../structcugip_1_1_connected_component_labeling_rule.html',1,'cugip']]],
  ['connectedcomponentlabelingrule2',['ConnectedComponentLabelingRule2',['../structcugip_1_1_connected_component_labeling_rule2.html',1,'cugip']]],
  ['const_5fdevice_5fimage_5fview',['const_device_image_view',['../classcugip_1_1const__device__image__view.html',1,'cugip']]],
  ['const_5fdevice_5fmemory_5f1d',['const_device_memory_1d',['../structcugip_1_1const__device__memory__1d.html',1,'cugip']]],
  ['const_5fdevice_5fmemory_5f2d',['const_device_memory_2d',['../structcugip_1_1const__device__memory__2d.html',1,'cugip']]],
  ['const_5fdevice_5fmemory_5f3d',['const_device_memory_3d',['../structcugip_1_1const__device__memory__3d.html',1,'cugip']]],
  ['const_5fdevice_5fptr',['const_device_ptr',['../structcugip_1_1const__device__ptr.html',1,'cugip']]],
  ['const_5fhost_5fimage_5fview',['const_host_image_view',['../classcugip_1_1const__host__image__view.html',1,'cugip']]],
  ['const_5fhost_5fmemory_5f1d',['const_host_memory_1d',['../structcugip_1_1const__host__memory__1d.html',1,'cugip']]],
  ['const_5fhost_5fmemory_5f2d',['const_host_memory_2d',['../structcugip_1_1const__host__memory__2d.html',1,'cugip']]],
  ['const_5fhost_5fmemory_5f3d',['const_host_memory_3d',['../structcugip_1_1const__host__memory__3d.html',1,'cugip']]],
  ['const_5fmemory_5fview',['const_memory_view',['../classcugip_1_1const__memory__view.html',1,'cugip']]],
  ['constantdeviceimageview',['ConstantDeviceImageView',['../classcugip_1_1_constant_device_image_view.html',1,'cugip']]],
  ['convert_5ffloat_5fand_5fbyte',['convert_float_and_byte',['../structcugip_1_1convert__float__and__byte.html',1,'cugip']]],
  ['convolution_5fkernel',['convolution_kernel',['../structcugip_1_1convolution__kernel.html',1,'cugip']]],
  ['convolution_5fkernel_3c_20cugip_3a_3asimple_5fvector_3c_20float_2c_20tdimension_20_3e_2c_20typename_20cugip_3a_3afillstaticsize_3c_20tdimension_2c_203_20_3e_3a_3atype_20_3e',['convolution_kernel&lt; cugip::simple_vector&lt; float, tDimension &gt;, typename cugip::FillStaticSize&lt; tDimension, 3 &gt;::Type &gt;',['../structcugip_1_1convolution__kernel.html',1,'cugip']]],
  ['convolution_5fkernel_3c_20simple_5fvector_3c_20float_2c_20tdimension_20_3e_2c_20typename_20fillstaticsize_3c_20tdimension_2c_203_20_3e_3a_3atype_20_3e',['convolution_kernel&lt; simple_vector&lt; float, tDimension &gt;, typename FillStaticSize&lt; tDimension, 3 &gt;::Type &gt;',['../structcugip_1_1convolution__kernel.html',1,'cugip']]],
  ['convolution_5fkernel_3c_20ttype_2c_20staticsize_3c_20tsize_20_3e_20_3e',['convolution_kernel&lt; TType, StaticSize&lt; tSize &gt; &gt;',['../structcugip_1_1convolution__kernel_3_01_t_type_00_01_static_size_3_01t_size_01_4_01_4.html',1,'cugip']]],
  ['convolution_5foperator',['convolution_operator',['../structcugip_1_1convolution__operator.html',1,'cugip']]],
  ['conwayrule',['ConwayRule',['../structcugip_1_1_conway_rule.html',1,'cugip']]],
  ['copydirectiontag',['CopyDirectionTag',['../structcugip_1_1_copy_direction_tag.html',1,'cugip']]]
];
