var annotated =
[
    [ "cugip::access_helper< TType >", "structcugip_1_1access__helper.html", "structcugip_1_1access__helper" ],
    [ "cugip::apply_diffusion_tensor_ftor< TStructuralTensor, TGradient >", "structcugip_1_1apply__diffusion__tensor__ftor.html", "structcugip_1_1apply__diffusion__tensor__ftor" ],
    [ "cugip::border_handling_mirror_t", "structcugip_1_1border__handling__mirror__t.html", "structcugip_1_1border__handling__mirror__t" ],
    [ "cugip::border_handling_none_t", "structcugip_1_1border__handling__none__t.html", "structcugip_1_1border__handling__none__t" ],
    [ "cugip::border_handling_periodic_t", "structcugip_1_1border__handling__periodic__t.html", "structcugip_1_1border__handling__periodic__t" ],
    [ "cugip::border_handling_repeat_t", "structcugip_1_1border__handling__repeat__t.html", "structcugip_1_1border__handling__repeat__t" ],
    [ "cugip::compute_diffusion_tensor_ftor< TStructuralTensor >", "structcugip_1_1compute__diffusion__tensor__ftor.html", "structcugip_1_1compute__diffusion__tensor__ftor" ],
    [ "cugip::detail::compute_divergence< TOutputType, TLocator, tDim >", "structcugip_1_1detail_1_1compute__divergence.html", "structcugip_1_1detail_1_1compute__divergence" ],
    [ "cugip::detail::compute_divergence< TOutputType, TLocator, 0 >", "structcugip_1_1detail_1_1compute__divergence_3_01_t_output_type_00_01_t_locator_00_010_01_4.html", "structcugip_1_1detail_1_1compute__divergence_3_01_t_output_type_00_01_t_locator_00_010_01_4" ],
    [ "cugip::compute_structural_tensor_ftor< TGradientVector, TStructuralTensor >", "structcugip_1_1compute__structural__tensor__ftor.html", "structcugip_1_1compute__structural__tensor__ftor" ],
    [ "cugip::detail::compute_symmetric_difference< TOutputType, TLocator, tDim >", "structcugip_1_1detail_1_1compute__symmetric__difference.html", "structcugip_1_1detail_1_1compute__symmetric__difference" ],
    [ "cugip::detail::compute_symmetric_difference< TOutputType, TLocator, 0 >", "structcugip_1_1detail_1_1compute__symmetric__difference_3_01_t_output_type_00_01_t_locator_00_010_01_4.html", "structcugip_1_1detail_1_1compute__symmetric__difference_3_01_t_output_type_00_01_t_locator_00_010_01_4" ],
    [ "cugip::const_device_image_view< TElement, tDim >", "classcugip_1_1const__device__image__view.html", "classcugip_1_1const__device__image__view" ],
    [ "cugip::const_device_memory_1d< TType >", "structcugip_1_1const__device__memory__1d.html", "structcugip_1_1const__device__memory__1d" ],
    [ "cugip::const_device_memory_2d< TType >", "structcugip_1_1const__device__memory__2d.html", "structcugip_1_1const__device__memory__2d" ],
    [ "cugip::const_device_ptr< TType >", "structcugip_1_1const__device__ptr.html", "structcugip_1_1const__device__ptr" ],
    [ "cugip::convert_float_and_byte", "structcugip_1_1convert__float__and__byte.html", "structcugip_1_1convert__float__and__byte" ],
    [ "cugip::convolution_kernel< TType, TSizeTraits >", "structcugip_1_1convolution__kernel.html", "structcugip_1_1convolution__kernel" ],
    [ "cugip::detail::convolution_operator< TInputType, TOutputType, TConvolutionMask >", "structcugip_1_1detail_1_1convolution__operator.html", "structcugip_1_1detail_1_1convolution__operator" ],
    [ "cugip::detail::copy_methods_impl< false, false >", "structcugip_1_1detail_1_1copy__methods__impl_3_01false_00_01false_01_4.html", "structcugip_1_1detail_1_1copy__methods__impl_3_01false_00_01false_01_4" ],
    [ "cugip::detail::copy_methods_impl< false, true >", "structcugip_1_1detail_1_1copy__methods__impl_3_01false_00_01true_01_4.html", "structcugip_1_1detail_1_1copy__methods__impl_3_01false_00_01true_01_4" ],
    [ "cugip::detail::copy_methods_impl< true, false >", "structcugip_1_1detail_1_1copy__methods__impl_3_01true_00_01false_01_4.html", "structcugip_1_1detail_1_1copy__methods__impl_3_01true_00_01false_01_4" ],
    [ "cugip::detail::copy_methods_impl< true, true >", "structcugip_1_1detail_1_1copy__methods__impl_3_01true_00_01true_01_4.html", "structcugip_1_1detail_1_1copy__methods__impl_3_01true_00_01true_01_4" ],
    [ "cugip::device_flag", "structcugip_1_1device__flag.html", "structcugip_1_1device__flag" ],
    [ "cugip::device_flag_view", "structcugip_1_1device__flag__view.html", "structcugip_1_1device__flag__view" ],
    [ "cugip::device_image< TElement, tDim >", "classcugip_1_1device__image.html", "classcugip_1_1device__image" ],
    [ "cugip::device_image_view< TElement, tDim >", "classcugip_1_1device__image__view.html", "classcugip_1_1device__image__view" ],
    [ "cugip::device_memory_1d< TType >", "structcugip_1_1device__memory__1d.html", "structcugip_1_1device__memory__1d" ],
    [ "cugip::device_memory_1d_owner< TType >", "structcugip_1_1device__memory__1d__owner.html", "structcugip_1_1device__memory__1d__owner" ],
    [ "cugip::device_memory_2d< TType >", "structcugip_1_1device__memory__2d.html", "structcugip_1_1device__memory__2d" ],
    [ "cugip::device_memory_2d_owner< TType >", "structcugip_1_1device__memory__2d__owner.html", "structcugip_1_1device__memory__2d__owner" ],
    [ "cugip::device_memory_3d< TType >", "structcugip_1_1device__memory__3d.html", "structcugip_1_1device__memory__3d" ],
    [ "cugip::device_ptr< TType >", "structcugip_1_1device__ptr.html", "structcugip_1_1device__ptr" ],
    [ "cugip::dim_traits< tDim >", "structcugip_1_1dim__traits.html", "structcugip_1_1dim__traits" ],
    [ "cugip::dimension< const_device_image_view< TElement, tDim > >", "structcugip_1_1dimension_3_01const__device__image__view_3_01_t_element_00_01t_dim_01_4_01_4.html", null ],
    [ "cugip::dimension< convolution_kernel< TType, TSizeTraits > >", "structcugip_1_1dimension_3_01convolution__kernel_3_01_t_type_00_01_t_size_traits_01_4_01_4.html", null ],
    [ "cugip::dimension< device_image< TElement, tDim > >", "structcugip_1_1dimension_3_01device__image_3_01_t_element_00_01t_dim_01_4_01_4.html", null ],
    [ "cugip::dimension< device_image_view< TElement, tDim > >", "structcugip_1_1dimension_3_01device__image__view_3_01_t_element_00_01t_dim_01_4_01_4.html", null ],
    [ "cugip::dimension< image_locator< TImageView, TBorderHandling > >", "structcugip_1_1dimension_3_01image__locator_3_01_t_image_view_00_01_t_border_handling_01_4_01_4.html", null ],
    [ "cugip::dimension< simple_vector< TCoordinateType, tDim > >", "structcugip_1_1dimension_3_01simple__vector_3_01_t_coordinate_type_00_01t_dim_01_4_01_4.html", null ],
    [ "cugip::dimension< size_traits_1d< tWidth > >", "structcugip_1_1dimension_3_01size__traits__1d_3_01t_width_01_4_01_4.html", null ],
    [ "cugip::dimension< size_traits_2d< tWidth, tHeight > >", "structcugip_1_1dimension_3_01size__traits__2d_3_01t_width_00_01t_height_01_4_01_4.html", null ],
    [ "cugip::dimension< size_traits_3d< tWidth, tHeight, tDepth > >", "structcugip_1_1dimension_3_01size__traits__3d_3_01t_width_00_01t_height_00_01t_depth_01_4_01_4.html", null ],
    [ "cugip::dimension_1d_tag", "structcugip_1_1dimension__1d__tag.html", null ],
    [ "cugip::dimension_2d_tag", "structcugip_1_1dimension__2d__tag.html", null ],
    [ "cugip::dimension_3d_tag", "structcugip_1_1dimension__3d__tag.html", null ],
    [ "cugip::dimension_4d_tag", "structcugip_1_1dimension__4d__tag.html", null ],
    [ "cugip::dimension_helper< 1 >", "structcugip_1_1dimension__helper_3_011_01_4.html", "structcugip_1_1dimension__helper_3_011_01_4" ],
    [ "cugip::dimension_helper< 2 >", "structcugip_1_1dimension__helper_3_012_01_4.html", "structcugip_1_1dimension__helper_3_012_01_4" ],
    [ "cugip::dimension_helper< 3 >", "structcugip_1_1dimension__helper_3_013_01_4.html", "structcugip_1_1dimension__helper_3_013_01_4" ],
    [ "cugip::dimension_helper< 4 >", "structcugip_1_1dimension__helper_3_014_01_4.html", "structcugip_1_1dimension__helper_3_014_01_4" ],
    [ "cugip::divergence< TInputType, TOutputType >", "structcugip_1_1divergence.html", "structcugip_1_1divergence" ],
    [ "cugip::element< TType, tChannelCount >", "structcugip_1_1element.html", "structcugip_1_1element" ],
    [ "cugip::get_neighborhood_accessor< TImageView, TNeigborhoodTag >", "structcugip_1_1get__neighborhood__accessor.html", "structcugip_1_1get__neighborhood__accessor" ],
    [ "cugip::get_policy< tIdx, const simple_vector< TType, tChannelCount > >", "structcugip_1_1get__policy_3_01t_idx_00_01const_01simple__vector_3_01_t_type_00_01t_channel_count_01_4_01_4.html", "structcugip_1_1get__policy_3_01t_idx_00_01const_01simple__vector_3_01_t_type_00_01t_channel_count_01_4_01_4" ],
    [ "cugip::get_policy< tIdx, simple_vector< TType, tChannelCount > >", "structcugip_1_1get__policy_3_01t_idx_00_01simple__vector_3_01_t_type_00_01t_channel_count_01_4_01_4.html", "structcugip_1_1get__policy_3_01t_idx_00_01simple__vector_3_01_t_type_00_01t_channel_count_01_4_01_4" ],
    [ "cugip::gradient_difference< TInputType, TOutputType >", "structcugip_1_1gradient__difference.html", "structcugip_1_1gradient__difference" ],
    [ "cugip::gradient_magnitude_symmetric_difference< TInputType, TOutputType >", "structcugip_1_1gradient__magnitude__symmetric__difference.html", "structcugip_1_1gradient__magnitude__symmetric__difference" ],
    [ "cugip::gradient_symmetric_difference< TInputType, TOutputType >", "structcugip_1_1gradient__symmetric__difference.html", "structcugip_1_1gradient__symmetric__difference" ],
    [ "cugip::grayscale_ftor", "structcugip_1_1grayscale__ftor.html", "structcugip_1_1grayscale__ftor" ],
    [ "cugip::image_locator< TImageView, TBorderHandling >", "classcugip_1_1image__locator.html", "classcugip_1_1image__locator" ],
    [ "cugip::is_device_view< TView >", "structcugip_1_1is__device__view.html", null ],
    [ "cugip::is_device_view< const_device_image_view< TElement, tDim > >", "structcugip_1_1is__device__view_3_01const__device__image__view_3_01_t_element_00_01t_dim_01_4_01_4.html", null ],
    [ "cugip::is_device_view< device_image_view< TElement, tDim > >", "structcugip_1_1is__device__view_3_01device__image__view_3_01_t_element_00_01t_dim_01_4_01_4.html", null ],
    [ "cugip::mandelbrot_ftor", "structcugip_1_1mandelbrot__ftor.html", "structcugip_1_1mandelbrot__ftor" ],
    [ "cugip::memory_management< TElement, 2 >", "structcugip_1_1memory__management_3_01_t_element_00_012_01_4.html", "structcugip_1_1memory__management_3_01_t_element_00_012_01_4" ],
    [ "cugip::detail::multiply_ftor< TType >", "structcugip_1_1detail_1_1multiply__ftor.html", "structcugip_1_1detail_1_1multiply__ftor" ],
    [ "cugip::negate< TType >", "structcugip_1_1negate.html", "structcugip_1_1negate" ],
    [ "cugip::neighborhood_4", "structcugip_1_1neighborhood__4.html", "structcugip_1_1neighborhood__4" ],
    [ "cugip::neighborhood_4_tag", "structcugip_1_1neighborhood__4__tag.html", "structcugip_1_1neighborhood__4__tag" ],
    [ "cugip::neighborhood_accessor< TImageLocator, TNeighborhood >", "classcugip_1_1neighborhood__accessor.html", "classcugip_1_1neighborhood__accessor" ],
    [ "cugip::random_color_map< TInputType >", "structcugip_1_1random__color__map.html", "structcugip_1_1random__color__map" ],
    [ "cugip::simple_vector< TCoordinateType, tDim >", "classcugip_1_1simple__vector.html", "classcugip_1_1simple__vector" ],
    [ "cugip::size_traits< 0, convolution_kernel< TType, TSizeTraits > >", "structcugip_1_1size__traits_3_010_00_01convolution__kernel_3_01_t_type_00_01_t_size_traits_01_4_01_4.html", "structcugip_1_1size__traits_3_010_00_01convolution__kernel_3_01_t_type_00_01_t_size_traits_01_4_01_4" ],
    [ "cugip::size_traits< 1, convolution_kernel< TType, TSizeTraits > >", "structcugip_1_1size__traits_3_011_00_01convolution__kernel_3_01_t_type_00_01_t_size_traits_01_4_01_4.html", "structcugip_1_1size__traits_3_011_00_01convolution__kernel_3_01_t_type_00_01_t_size_traits_01_4_01_4" ],
    [ "cugip::size_traits< 2, convolution_kernel< TType, TSizeTraits > >", "structcugip_1_1size__traits_3_012_00_01convolution__kernel_3_01_t_type_00_01_t_size_traits_01_4_01_4.html", "structcugip_1_1size__traits_3_012_00_01convolution__kernel_3_01_t_type_00_01_t_size_traits_01_4_01_4" ],
    [ "cugip::size_traits_1d< tWidth >", "structcugip_1_1size__traits__1d.html", "structcugip_1_1size__traits__1d" ],
    [ "cugip::size_traits_2d< tWidth, tHeight >", "structcugip_1_1size__traits__2d.html", "structcugip_1_1size__traits__2d" ],
    [ "cugip::size_traits_3d< tWidth, tHeight, tDepth >", "structcugip_1_1size__traits__3d.html", "structcugip_1_1size__traits__3d" ],
    [ "cugip::detail::threshold_mask_operator< TInputType, TOutputType >", "structcugip_1_1detail_1_1threshold__mask__operator.html", "structcugip_1_1detail_1_1threshold__mask__operator" ],
    [ "cugip::thresholding_ftor< TInValue, TOutValue >", "structcugip_1_1thresholding__ftor.html", "structcugip_1_1thresholding__ftor" ],
    [ "cugip::detail::weighted_add_ftor< TWeight >", "structcugip_1_1detail_1_1weighted__add__ftor.html", "structcugip_1_1detail_1_1weighted__add__ftor" ]
];