CUGIP: cugip::symmetric_tensor< TType, tDimension > Class Template Reference
cugip::symmetric_tensor< TType, tDimension > Class Template Reference
#include <symmetric_tensor.hpp>
Public Types
typedef simple_vector< TType, cBufferSize > base_type
Public Types inherited from cugip::simple_vector< TType,((tDimension+1)*tDimension)/2 >
typedef TType coord_t
typedef simple_vector< TType, tDim > this_t
Public Member Functions
CUGIP_DECL_HYBRID symmetric_tensor ()
CUGIP_DECL_HYBRID TType & get (int aRow, int aCol)
CUGIP_DECL_HYBRID const TType & get (int aRow, int aCol) const
CUGIP_DECL_HYBRID simple_vector< TType, tDimension > column (int aCol) const
CUGIP_DECL_HYBRID simple_vector< TType, tDimension > row (int aRow) const
Public Member Functions inherited from cugip::simple_vector< TType,((tDimension+1)*tDimension)/2 >
CUGIP_DECL_HYBRID simple_vector ()
CUGIP_DECL_HYBRID simple_vector (TTypeaValue, FillFlag)
CUGIP_DECL_HYBRID constexpr simple_vector (TTypeconst &v0)
CUGIP_DECL_HYBRID constexpr simple_vector (TTypeconst &v0, TTypeconst &v1)
CUGIP_DECL_HYBRID constexpr simple_vector (TTypeconst &v0, TTypeconst &v1, TTypeconst &v2)
CUGIP_DECL_HYBRID simple_vector (const simple_vector< TOtherCoordType, tDim > &aArg)
CUGIP_DECL_HYBRID simple_vector (std::initializer_list< TType > aList)
CUGIP_DECL_HYBRID simple_vector & operator= (const simple_vector< TOtherCoordType, tDim > &aArg)
CUGIP_DECL_HYBRID simple_vector & operator+= (const simple_vector< TOtherCoordType, tDim > &aArg)
CUGIP_DECL_HYBRID simple_vector & operator-= (const simple_vector< TOtherCoordType, tDim > &aArg)
CUGIP_DECL_HYBRID simple_vector operator- () const
CUGIP_DECL_HYBRID TTypeconst & get () const
CUGIP_DECL_HYBRID TType & get ()
CUGIP_DECL_HYBRID const TType & operator[] (int aIdx) const
CUGIP_DECL_HYBRID TType & operator[] (int aIdx)
CUGIP_DECL_HYBRID void set (TTypeconst &value)
Static Public Attributes
static constexpr int cBufferSize = ((tDimension + 1) * tDimension) / 2
static constexpr int cDimension = tDimension
Static Public Attributes inherited from cugip::simple_vector< TType,((tDimension+1)*tDimension)/2 >
static constexpr int dim
Additional Inherited Members
Public Attributes inherited from cugip::simple_vector< TType,((tDimension+1)*tDimension)/2 >
TType mValues [tDim]
Detailed Description
template<typename TType, int tDimension>
class cugip::symmetric_tensor< TType, tDimension >
Definition at line 10 of file symmetric_tensor.hpp.
Member Typedef Documentation
template<typename TType, int tDimension> typedef simple_vector<TType, cBufferSize> cugip::symmetric_tensor< TType, tDimension >::base_type
Definition at line 14 of file symmetric_tensor.hpp.
Constructor & Destructor Documentation
template<typename TType, int tDimension> CUGIP_DECL_HYBRID cugip::symmetric_tensor< TType, tDimension >::symmetric_tensor () inline
Definition at line 18 of file symmetric_tensor.hpp.
References CUGIP_DECL_HYBRID.
Member Function Documentation
template<typename TType, int tDimension> CUGIP_DECL_HYBRID simple_vector<TType, tDimension> cugip::symmetric_tensor< TType, tDimension >::column (int aCol) const inline
Todo:
get wrapper which provides access
Definition at line 45 of file symmetric_tensor.hpp.
References CUGIP_DECL_HYBRID.
Referenced by cugip::eigen_vector(), and cugip::symmetric_tensor< TType, tDimension >::row().
template<typename TType, int tDimension> CUGIP_DECL_HYBRID TType& cugip::symmetric_tensor< TType, tDimension >::get (int aRow, int aCol) inline
Definition at line 24 of file symmetric_tensor.hpp.
References CUGIP_DECL_HYBRID.
Referenced by cugip::matrix_from_eigen_vectors_and_values(), and cugip::matrix_trace().
template<typename TType, int tDimension> CUGIP_DECL_HYBRID const TType& cugip::symmetric_tensor< TType, tDimension >::get (int aRow, int aCol) const inline
Definition at line 34 of file symmetric_tensor.hpp.
References CUGIP_DECL_HYBRID.
template<typename TType, int tDimension> CUGIP_DECL_HYBRID simple_vector<TType, tDimension> cugip::symmetric_tensor< TType, tDimension >::row (int aRow) const inline
Definition at line 56 of file symmetric_tensor.hpp.
References cugip::symmetric_tensor< TType, tDimension >::column().
Member Data Documentation
template<typename TType, int tDimension> constexpr int cugip::symmetric_tensor< TType, tDimension >::cBufferSize = ((tDimension + 1) * tDimension) / 2 static
Definition at line 13 of file symmetric_tensor.hpp.
template<typename TType, int tDimension> constexpr int cugip::symmetric_tensor< TType, tDimension >::cDimension = tDimension static
Definition at line 15 of file symmetric_tensor.hpp.
The documentation for this class was generated from the following file:
/home/johny/programming/git/MedV4D/extern/cugip/include/cugip/math/symmetric_tensor.hpp