CUGIP: cugip::MinimalGraphCutComputation< TGraph > Class Template Reference
cugip::MinimalGraphCutComputation< TGraph > Class Template Reference
#include <graph_cut_implementation.hpp>
Public Types
typedef float Flow
Public Member Functions
MinimalGraphCutComputation ()
void setGraph (TGraph &aGraph)
template<typename TTraceObject >
Flow run (TTraceObject &aTraceObject)
template<typename TPolicy , typename TTraceObject >
Flow run (TPolicy &aPolicy, TTraceObject &aTraceObject)
void init_residuals ()
Protected Attributes
TGraph * mGraph
GraphCutData< Flow > mGraphData
ParallelQueue< int > mVertexQueue
thrust::host_vector< int > mLevelStarts
Detailed Description
template<typename TGraph>
class cugip::MinimalGraphCutComputation< TGraph >
Definition at line 240 of file graph_cut_implementation.hpp.
Member Typedef Documentation
template<typename TGraph> typedef float cugip::MinimalGraphCutComputation< TGraph >::Flow
Definition at line 243 of file graph_cut_implementation.hpp.
Constructor & Destructor Documentation
template<typename TGraph> cugip::MinimalGraphCutComputation< TGraph >::MinimalGraphCutComputation () inline
Definition at line 244 of file graph_cut_implementation.hpp.
Member Function Documentation
template<typename TGraph> void cugip::MinimalGraphCutComputation< TGraph >::init_residuals () inline
Definition at line 311 of file graph_cut_implementation.hpp.
template<typename TGraph> template<typename TTraceObject > Flow cugip::MinimalGraphCutComputation< TGraph >::run (TTraceObject & aTraceObject) inline
Definition at line 280 of file graph_cut_implementation.hpp.
Referenced by cugip::Graph< TFlow >::max_flow_with_tracing().
template<typename TGraph> template<typename TPolicy , typename TTraceObject > Flow cugip::MinimalGraphCutComputation< TGraph >::run (TPolicy & aPolicy, TTraceObject & aTraceObject) inline
Definition at line 288 of file graph_cut_implementation.hpp.
References cugip::MinCut< TGraphData, TPolicy, TTraceObject >::compute(), CUGIP_ASSERT, cugip::Sink, and cugip::Source.
template<typename TGraph> void cugip::MinimalGraphCutComputation< TGraph >::setGraph (TGraph & aGraph) inline
Definition at line 249 of file graph_cut_implementation.hpp.
References cugip::graphCutDataFromGraph(), cugip::Sink, and cugip::Source.
Referenced by cugip::Graph< TFlow >::max_flow_with_tracing().
Member Data Documentation
template<typename TGraph> TGraph* cugip::MinimalGraphCutComputation< TGraph >::mGraph protected
Definition at line 330 of file graph_cut_implementation.hpp.
template<typename TGraph> GraphCutData<Flow> cugip::MinimalGraphCutComputation< TGraph >::mGraphData protected
Definition at line 331 of file graph_cut_implementation.hpp.
template<typename TGraph> thrust::host_vector<int> cugip::MinimalGraphCutComputation< TGraph >::mLevelStarts protected
Definition at line 333 of file graph_cut_implementation.hpp.
template<typename TGraph> ParallelQueue<int> cugip::MinimalGraphCutComputation< TGraph >::mVertexQueue protected
Definition at line 332 of file graph_cut_implementation.hpp.
The documentation for this class was generated from the following file:
/home/johny/programming/git/MedV4D/extern/cugip/include/cugip/advanced_operations/detail/graph_cut_implementation.hpp