CUGIP: cugip::const_device_image_view< TElement, tDim > Class Template Reference
cugip::const_device_image_view< TElement, tDim > Class Template Reference
#include <image_view.hpp>
Public Types
typedef dim_traits< tDim >::extents_t extents_t
typedef dim_traits< tDim >::coord_t coord_t
typedef dim_traits< tDim >::diff_t diff_t
typedef memory_management< TElement, tDim >::const_device_memory memory_t
typedef const_device_image_view< TElement, tDim > this_t
typedef TElement value_type
typedef const TElement const_value_type
typedef const_value_type & accessed_type
Public Member Functions
CUGIP_DECL_HYBRID const_device_image_view (const TElement *buffer, extents_t size, extents_t strides)
CUGIP_DECL_HYBRID const_device_image_view ()
CUGIP_DECL_HYBRID extents_t dimensions () const
CUGIP_DECL_HYBRID accessed_type & operator[] (coord_t aCoords) const
template<typename TBorderHandling >
CUGIP_DECL_HYBRID image_locator< this_t, TBorderHandling > locator (coord_t aCoordinates) const
CUGIP_DECL_HYBRID const_value_type * pointer () const
CUGIP_DECL_HYBRID extents_t strides () const
const_device_image_view< TElement, tDim > subview (const coord_t &corner, const extents_t &size) const
Static Public Attributes
static const int cDimension = tDim
Protected Attributes
extents_t mSize
const TElement * mDevicePtr
extents_t mStrides
Detailed Description
template<typename TElement, int tDim = 2>
class cugip::const_device_image_view< TElement, tDim >
Definition at line 114 of file image_view.hpp.
Member Typedef Documentation
template<typename TElement, int tDim = 2> typedef const_value_type& cugip::const_device_image_view< TElement, tDim >::accessed_type
Definition at line 125 of file image_view.hpp.
template<typename TElement, int tDim = 2> typedef const TElement cugip::const_device_image_view< TElement, tDim >::const_value_type
Definition at line 124 of file image_view.hpp.
template<typename TElement, int tDim = 2> typedef dim_traits<tDim>::coord_t cugip::const_device_image_view< TElement, tDim >::coord_t
Definition at line 119 of file image_view.hpp.
template<typename TElement, int tDim = 2> typedef dim_traits<tDim>::diff_t cugip::const_device_image_view< TElement, tDim >::diff_t
Definition at line 120 of file image_view.hpp.
template<typename TElement, int tDim = 2> typedef dim_traits<tDim>::extents_t cugip::const_device_image_view< TElement, tDim >::extents_t
Definition at line 118 of file image_view.hpp.
template<typename TElement, int tDim = 2> typedef memory_management<TElement, tDim>::const_device_memory cugip::const_device_image_view< TElement, tDim >::memory_t
Definition at line 121 of file image_view.hpp.
template<typename TElement, int tDim = 2> typedef const_device_image_view<TElement, tDim> cugip::const_device_image_view< TElement, tDim >::this_t
Definition at line 122 of file image_view.hpp.
template<typename TElement, int tDim = 2> typedef TElement cugip::const_device_image_view< TElement, tDim >::value_type
Definition at line 123 of file image_view.hpp.
Constructor & Destructor Documentation
template<typename TElement, int tDim = 2> CUGIP_DECL_HYBRID cugip::const_device_image_view< TElement, tDim >::const_device_image_view (const TElement * buffer, extents_t size, extents_t strides) inline
Definition at line 138 of file image_view.hpp.
References CUGIP_DECL_HYBRID.
template<typename TElement, int tDim = 2> CUGIP_DECL_HYBRID cugip::const_device_image_view< TElement, tDim >::const_device_image_view () inline
Definition at line 145 of file image_view.hpp.
References CUGIP_DECL_HYBRID.
Member Function Documentation
template<typename TElement, int tDim = 2> CUGIP_DECL_HYBRID extents_t cugip::const_device_image_view< TElement, tDim >::dimensions () const inline
Definition at line 149 of file image_view.hpp.
References CUGIP_DECL_HYBRID, and cugip::device_image_view< TElement, tDim >::mSize.
template<typename TElement, int tDim = 2> template<typename TBorderHandling > CUGIP_DECL_HYBRID image_locator<this_t, TBorderHandling> cugip::const_device_image_view< TElement, tDim >::locator (coord_t aCoordinates) const inline
Todo:
remove const_cast
Definition at line 164 of file image_view.hpp.
References CUGIP_DECL_HYBRID.
template<typename TElement, int tDim = 2> CUGIP_DECL_HYBRID accessed_type& cugip::const_device_image_view< TElement, tDim >::operator[] (coord_t aCoords) const inline
Definition at line 156 of file image_view.hpp.
References CUGIP_DECL_HYBRID, cugip::dot(), cugip::device_image_view< TElement, tDim >::mDevicePtr, and cugip::device_image_view< TElement, tDim >::mStrides.
template<typename TElement, int tDim = 2> CUGIP_DECL_HYBRID const_value_type* cugip::const_device_image_view< TElement, tDim >::pointer () const inline
Definition at line 174 of file image_view.hpp.
References CUGIP_DECL_HYBRID, and cugip::device_image_view< TElement, tDim >::mDevicePtr.
template<typename TElement, int tDim = 2> CUGIP_DECL_HYBRID extents_t cugip::const_device_image_view< TElement, tDim >::strides () const inline
Definition at line 181 of file image_view.hpp.
References cugip::device_image_view< TElement, tDim >::mStrides.
template<typename TElement, int tDim = 2> const_device_image_view<TElement, tDim> cugip::const_device_image_view< TElement, tDim >::subview (const coord_t & corner, const extents_t & size) const inline
Definition at line 187 of file image_view.hpp.
References CUGIP_ASSERT, cugip::device_image_view< TElement, tDim >::dimensions(), cugip::dot(), cugip::device_image_view< TElement, tDim >::mDevicePtr, and cugip::device_image_view< TElement, tDim >::mStrides.
Member Data Documentation
template<typename TElement, int tDim = 2> const int cugip::const_device_image_view< TElement, tDim >::cDimension = tDim static
Definition at line 117 of file image_view.hpp.
template<typename TElement, int tDim = 2> const TElement* cugip::const_device_image_view< TElement, tDim >::mDevicePtr protected
Definition at line 200 of file image_view.hpp.
template<typename TElement, int tDim = 2> extents_t cugip::const_device_image_view< TElement, tDim >::mSize protected
Definition at line 199 of file image_view.hpp.
template<typename TElement, int tDim = 2> extents_t cugip::const_device_image_view< TElement, tDim >::mStrides protected
Definition at line 201 of file image_view.hpp.
The documentation for this class was generated from the following file:
/home/johny/programming/git/MedV4D/extern/cugip/include/cugip/image_view.hpp