CUGIP: cugip::device_image_view< TElement, tDim > Class Template Reference
cugip::device_image_view< TElement, tDim > Class Template Reference
#include <image_view.hpp>
Public Types
typedef dim_traits< tDim >::extents_t extents_t
typedef dim_traits< tDim >::coord_t coord_t
typedef dim_traits< tDim >::diff_t diff_t
typedef memory_management< TElement, tDim >::device_memory memory_t
typedef device_image_view< TElement, tDim > this_t
typedef TElement value_type
typedef const TElement const_value_type
typedef value_type & accessed_type
Public Member Functions
CUGIP_DECL_HYBRID device_image_view (TElement *buffer, extents_t size, extents_t strides)
device_image_view ()
CUGIP_DECL_HYBRID extents_t dimensions () const
CUGIP_DECL_HYBRID accessed_type operator[] (coord_t aCoords) const
template<typename TBorderHandling >
CUGIP_DECL_HYBRID image_locator< this_t, TBorderHandling > locator (coord_t aCoordinates) const
CUGIP_DECL_HYBRID value_type * pointer () const
CUGIP_DECL_HYBRID extents_t strides () const
device_image_view< TElement, tDim > subview (const coord_t &corner, const extents_t &size) const
Static Public Attributes
static const int cDimension = tDim
Protected Attributes
extents_t mSize
TElement * mDevicePtr
extents_t mStrides
Detailed Description
template<typename TElement, int tDim = 2>
class cugip::device_image_view< TElement, tDim >
Definition at line 13 of file image_view.hpp.
Member Typedef Documentation
template<typename TElement, int tDim = 2> typedef value_type& cugip::device_image_view< TElement, tDim >::accessed_type
Definition at line 24 of file image_view.hpp.
template<typename TElement, int tDim = 2> typedef const TElement cugip::device_image_view< TElement, tDim >::const_value_type
Definition at line 23 of file image_view.hpp.
template<typename TElement, int tDim = 2> typedef dim_traits<tDim>::coord_t cugip::device_image_view< TElement, tDim >::coord_t
Definition at line 18 of file image_view.hpp.
template<typename TElement, int tDim = 2> typedef dim_traits<tDim>::diff_t cugip::device_image_view< TElement, tDim >::diff_t
Definition at line 19 of file image_view.hpp.
template<typename TElement, int tDim = 2> typedef dim_traits<tDim>::extents_t cugip::device_image_view< TElement, tDim >::extents_t
Definition at line 17 of file image_view.hpp.
template<typename TElement, int tDim = 2> typedef memory_management<TElement, tDim>::device_memory cugip::device_image_view< TElement, tDim >::memory_t
Definition at line 20 of file image_view.hpp.
template<typename TElement, int tDim = 2> typedef device_image_view<TElement, tDim> cugip::device_image_view< TElement, tDim >::this_t
Definition at line 21 of file image_view.hpp.
template<typename TElement, int tDim = 2> typedef TElement cugip::device_image_view< TElement, tDim >::value_type
Definition at line 22 of file image_view.hpp.
Constructor & Destructor Documentation
template<typename TElement, int tDim = 2> CUGIP_DECL_HYBRID cugip::device_image_view< TElement, tDim >::device_image_view (TElement * buffer, extents_t size, extents_t strides) inline
Definition at line 31 of file image_view.hpp.
template<typename TElement, int tDim = 2> cugip::device_image_view< TElement, tDim >::device_image_view () inline
Definition at line 37 of file image_view.hpp.
References CUGIP_DECL_HYBRID.
Member Function Documentation
template<typename TElement, int tDim = 2> CUGIP_DECL_HYBRID extents_t cugip::device_image_view< TElement, tDim >::dimensions () const inline
Definition at line 41 of file image_view.hpp.
References CUGIP_DECL_HYBRID, and cugip::device_image_view< TElement, tDim >::mSize.
Referenced by cugip::device_image_view< TElement, tDim >::subview(), and cugip::const_device_image_view< TElement, tDim >::subview().
template<typename TElement, int tDim = 2> template<typename TBorderHandling > CUGIP_DECL_HYBRID image_locator<this_t, TBorderHandling> cugip::device_image_view< TElement, tDim >::locator (coord_t aCoordinates) const inline
Todo:
remove const_cast
Definition at line 56 of file image_view.hpp.
References CUGIP_DECL_HYBRID.
template<typename TElement, int tDim = 2> CUGIP_DECL_HYBRID accessed_type cugip::device_image_view< TElement, tDim >::operator[] (coord_t aCoords) const inline
Definition at line 48 of file image_view.hpp.
References CUGIP_DECL_HYBRID, cugip::dot(), cugip::device_image_view< TElement, tDim >::mDevicePtr, and cugip::device_image_view< TElement, tDim >::mStrides.
template<typename TElement, int tDim = 2> CUGIP_DECL_HYBRID value_type* cugip::device_image_view< TElement, tDim >::pointer () const inline
Definition at line 66 of file image_view.hpp.
References CUGIP_DECL_HYBRID, and cugip::device_image_view< TElement, tDim >::mDevicePtr.
template<typename TElement, int tDim = 2> CUGIP_DECL_HYBRID extents_t cugip::device_image_view< TElement, tDim >::strides () const inline
Definition at line 73 of file image_view.hpp.
References cugip::device_image_view< TElement, tDim >::mStrides.
Referenced by cugip::makeConstDeviceImageView(), and cugip::makeDeviceImageView().
template<typename TElement, int tDim = 2> device_image_view<TElement, tDim> cugip::device_image_view< TElement, tDim >::subview (const coord_t & corner, const extents_t & size) const inline
Definition at line 79 of file image_view.hpp.
References CUGIP_ASSERT, cugip::device_image_view< TElement, tDim >::dimensions(), cugip::dot(), cugip::device_image_view< TElement, tDim >::mDevicePtr, and cugip::device_image_view< TElement, tDim >::mStrides.
Member Data Documentation
template<typename TElement, int tDim = 2> const int cugip::device_image_view< TElement, tDim >::cDimension = tDim static
Definition at line 16 of file image_view.hpp.
template<typename TElement, int tDim = 2> TElement* cugip::device_image_view< TElement, tDim >::mDevicePtr protected
Definition at line 109 of file image_view.hpp.
Referenced by cugip::device_image_view< TElement, tDim >::operator[](), cugip::const_device_image_view< TElement, tDim >::operator[](), cugip::device_image_view< TElement, tDim >::pointer(), cugip::const_device_image_view< TElement, tDim >::pointer(), cugip::device_image_view< TElement, tDim >::subview(), and cugip::const_device_image_view< TElement, tDim >::subview().
template<typename TElement, int tDim = 2> extents_t cugip::device_image_view< TElement, tDim >::mSize protected
Creates view for cut through the image
Template Parameters
tSliceDimension Dimension axis perpendicular to the cut
Parameters
slice Coordinate of the slice - index in tSliceDimension
Definition at line 108 of file image_view.hpp.
Referenced by cugip::device_image_view< TElement, tDim >::dimensions(), and cugip::const_device_image_view< TElement, tDim >::dimensions().
template<typename TElement, int tDim = 2> extents_t cugip::device_image_view< TElement, tDim >::mStrides protected
Definition at line 110 of file image_view.hpp.
Referenced by cugip::device_image_view< TElement, tDim >::operator[](), cugip::const_device_image_view< TElement, tDim >::operator[](), cugip::device_image_view< TElement, tDim >::strides(), cugip::const_device_image_view< TElement, tDim >::strides(), cugip::device_image_view< TElement, tDim >::subview(), and cugip::const_device_image_view< TElement, tDim >::subview().
The documentation for this class was generated from the following file:
/home/johny/programming/git/MedV4D/extern/cugip/include/cugip/image_view.hpp