CUGIP: cugip::texture_image< TElement, tDim > Class Template Reference
cugip::texture_image< TElement, tDim > Class Template Reference
#include <texture.hpp>
Public Types
typedef texture_view< TElement, tDim > view_t
typedef texture_view< TElement, tDim > const_view_t
typedef TElement element_t
typedef TElement value_type
typedef dim_traits< tDim >::extents_t extents_t
Public Member Functions
texture_image (extents_t aDimensions)
~texture_image ()
CUGIP_DECL_HYBRID extents_t dimensions () const
void allocate (extents_t aSize)
void finalize ()
view_t view () const
view_t const_view () const
Public Attributes
memory_management< TElement, tDim >::device_memory_owner mData
cudaTextureObject_t mTexture
Detailed Description
template<typename TElement, int tDim>
class cugip::texture_image< TElement, tDim >
Definition at line 39 of file texture.hpp.
Member Typedef Documentation
template<typename TElement, int tDim> typedef texture_view<TElement, tDim> cugip::texture_image< TElement, tDim >::const_view_t
Definition at line 43 of file texture.hpp.
template<typename TElement, int tDim> typedef TElement cugip::texture_image< TElement, tDim >::element_t
Definition at line 44 of file texture.hpp.
template<typename TElement, int tDim> typedef dim_traits<tDim>::extents_t cugip::texture_image< TElement, tDim >::extents_t
Definition at line 47 of file texture.hpp.
template<typename TElement, int tDim> typedef TElement cugip::texture_image< TElement, tDim >::value_type
Definition at line 45 of file texture.hpp.
template<typename TElement, int tDim> typedef texture_view<TElement, tDim> cugip::texture_image< TElement, tDim >::view_t
Definition at line 42 of file texture.hpp.
Constructor & Destructor Documentation
template<typename TElement, int tDim> cugip::texture_image< TElement, tDim >::texture_image (extents_t aDimensions) inline
Definition at line 50 of file texture.hpp.
template<typename TElement, int tDim> cugip::texture_image< TElement, tDim >::~texture_image () inline
Definition at line 54 of file texture.hpp.
References CUGIP_DECL_HYBRID.
Member Function Documentation
template<typename TElement, int tDim> void cugip::texture_image< TElement, tDim >::allocate (extents_t aSize) inline
Todo:
Definition at line 64 of file texture.hpp.
References cugip::texture_view< TElement, tDim >::mTexture.
template<typename TElement, int tDim> view_t cugip::texture_image< TElement, tDim >::const_view () const inline
Definition at line 91 of file texture.hpp.
References cugip::view().
template<typename TElement, int tDim> CUGIP_DECL_HYBRID extents_t cugip::texture_image< TElement, tDim >::dimensions () const inline
Definition at line 60 of file texture.hpp.
template<typename TElement, int tDim> void cugip::texture_image< TElement, tDim >::finalize () inline
Definition at line 79 of file texture.hpp.
References cugip::texture_view< TElement, tDim >::mTexture.
template<typename TElement, int tDim> view_t cugip::texture_image< TElement, tDim >::view () const inline
Definition at line 85 of file texture.hpp.
References cugip::texture_view< TElement, tDim >::mTexture.
Referenced by cugip::const_view(), and cugip::view().
Member Data Documentation
template<typename TElement, int tDim> memory_management<TElement, tDim>::device_memory_owner cugip::texture_image< TElement, tDim >::mData
Definition at line 96 of file texture.hpp.
template<typename TElement, int tDim> cudaTextureObject_t cugip::texture_image< TElement, tDim >::mTexture
Definition at line 97 of file texture.hpp.
The documentation for this class was generated from the following file:
/home/johny/programming/git/MedV4D/extern/cugip/include/cugip/texture.hpp