CUGIP: cugip::host_image< TElement, tDim > Class Template Reference
cugip::host_image< TElement, tDim > Class Template Reference
#include <host_image.hpp>
Public Types
typedef host_image_view< TElement, tDim > view_t
typedef const_host_image_view< TElement, tDim > const_view_t
typedef TElement element_t
typedef TElement value_type
typedef dim_traits< tDim >::extents_t extents_t
Public Member Functions
host_image ()
host_image (extents_t aExtents)
host_image (int aS0, int aS1)
host_image (int aS0, int aS1, int aS2)
host_image (host_image &&aOther)=default
host_image & operator= (host_image &&aOther)=default
host_image & operator= (const host_image &)=delete
host_image (const host_image &)=delete
extents_t dimensions () const
view_t view ()
const_view_t const_view () const
value_type * pointer () const
extents_t strides () const
Protected Member Functions
void reallocate (const extents_t &aSize)
Protected Attributes
extents_t mSize
extents_t mStrides
std::unique_ptr< value_type[]> mHostPtr
Detailed Description
template<typename TElement, int tDim = 2>
class cugip::host_image< TElement, tDim >
Returns
Strides for memory without padding.
Definition at line 36 of file host_image.hpp.
Member Typedef Documentation
template<typename TElement, int tDim = 2> typedef const_host_image_view<TElement, tDim> cugip::host_image< TElement, tDim >::const_view_t
Definition at line 40 of file host_image.hpp.
template<typename TElement, int tDim = 2> typedef TElement cugip::host_image< TElement, tDim >::element_t
Definition at line 41 of file host_image.hpp.
template<typename TElement, int tDim = 2> typedef dim_traits<tDim>::extents_t cugip::host_image< TElement, tDim >::extents_t
Definition at line 44 of file host_image.hpp.
template<typename TElement, int tDim = 2> typedef TElement cugip::host_image< TElement, tDim >::value_type
Definition at line 42 of file host_image.hpp.
template<typename TElement, int tDim = 2> typedef host_image_view<TElement, tDim> cugip::host_image< TElement, tDim >::view_t
Definition at line 39 of file host_image.hpp.
Constructor & Destructor Documentation
template<typename TElement, int tDim = 2> cugip::host_image< TElement, tDim >::host_image () inline
Definition at line 46 of file host_image.hpp.
Referenced by cugip::host_image< TElement, tDim >::host_image().
template<typename TElement, int tDim = 2> cugip::host_image< TElement, tDim >::host_image (extents_t aExtents) inline
Definition at line 49 of file host_image.hpp.
References cugip::host_image< TElement, tDim >::reallocate().
template<typename TElement, int tDim = 2> cugip::host_image< TElement, tDim >::host_image (int aS0, int aS1) inline
Definition at line 54 of file host_image.hpp.
References cugip::host_image< TElement, tDim >::reallocate().
template<typename TElement, int tDim = 2> cugip::host_image< TElement, tDim >::host_image (int aS0, int aS1, int aS2) inline
Definition at line 60 of file host_image.hpp.
References cugip::host_image< TElement, tDim >::host_image(), cugip::host_image< TElement, tDim >::operator=(), and cugip::host_image< TElement, tDim >::reallocate().
template<typename TElement, int tDim = 2> cugip::host_image< TElement, tDim >::host_image (host_image< TElement, tDim > && aOther) default
template<typename TElement, int tDim = 2> cugip::host_image< TElement, tDim >::host_image (const host_image< TElement, tDim > &) delete
Member Function Documentation
template<typename TElement, int tDim = 2> const_view_t cugip::host_image< TElement, tDim >::const_view () const inline
Definition at line 83 of file host_image.hpp.
References cugip::host_image< TElement, tDim >::mHostPtr, cugip::host_image< TElement, tDim >::mSize, and cugip::host_image< TElement, tDim >::mStrides.
Referenced by cugip::const_view().
template<typename TElement, int tDim = 2> extents_t cugip::host_image< TElement, tDim >::dimensions () const inline
Definition at line 73 of file host_image.hpp.
References cugip::host_image< TElement, tDim >::mSize.
template<typename TElement, int tDim = 2> host_image& cugip::host_image< TElement, tDim >::operator= (host_image< TElement, tDim > && aOther) default
Referenced by cugip::host_image< TElement, tDim >::host_image().
template<typename TElement, int tDim = 2> host_image& cugip::host_image< TElement, tDim >::operator= (const host_image< TElement, tDim > &) delete
template<typename TElement, int tDim = 2> value_type* cugip::host_image< TElement, tDim >::pointer () const inline
Definition at line 89 of file host_image.hpp.
References cugip::host_image< TElement, tDim >::mHostPtr.
template<typename TElement, int tDim = 2> void cugip::host_image< TElement, tDim >::reallocate (const extents_t & aSize) inline protected
Definition at line 100 of file host_image.hpp.
References cugip::host_image< TElement, tDim >::mHostPtr, cugip::host_image< TElement, tDim >::mSize, cugip::host_image< TElement, tDim >::mStrides, cugip::product(), and cugip::stridesFromSize().
Referenced by cugip::host_image< TElement, tDim >::host_image().
template<typename TElement, int tDim = 2> extents_t cugip::host_image< TElement, tDim >::strides () const inline
Definition at line 95 of file host_image.hpp.
References cugip::host_image< TElement, tDim >::mStrides.
template<typename TElement, int tDim = 2> view_t cugip::host_image< TElement, tDim >::view () inline
Definition at line 77 of file host_image.hpp.
References cugip::host_image< TElement, tDim >::mHostPtr, cugip::host_image< TElement, tDim >::mSize, and cugip::host_image< TElement, tDim >::mStrides.
Referenced by cugip::view().
Member Data Documentation
template<typename TElement, int tDim = 2> std::unique_ptr<value_type []> cugip::host_image< TElement, tDim >::mHostPtr protected
Definition at line 109 of file host_image.hpp.
Referenced by cugip::host_image< TElement, tDim >::const_view(), cugip::host_image< TElement, tDim >::pointer(), cugip::host_image< TElement, tDim >::reallocate(), and cugip::host_image< TElement, tDim >::view().
template<typename TElement, int tDim = 2> extents_t cugip::host_image< TElement, tDim >::mSize protected
Definition at line 107 of file host_image.hpp.
Referenced by cugip::host_image< TElement, tDim >::const_view(), cugip::host_image< TElement, tDim >::dimensions(), cugip::host_image< TElement, tDim >::reallocate(), and cugip::host_image< TElement, tDim >::view().
template<typename TElement, int tDim = 2> extents_t cugip::host_image< TElement, tDim >::mStrides protected
Definition at line 108 of file host_image.hpp.
Referenced by cugip::host_image< TElement, tDim >::const_view(), cugip::host_image< TElement, tDim >::reallocate(), cugip::host_image< TElement, tDim >::strides(), and cugip::host_image< TElement, tDim >::view().
The documentation for this class was generated from the following file:
/home/johny/programming/git/MedV4D/extern/cugip/include/cugip/host_image.hpp