CUGIP: cugip::Graph< TFlow > Class Template Reference
cugip::Graph< TFlow > Class Template Reference
#include <graph_cut.hpp>
Public Types
typedef int VertexId
typedef TFlow EdgeWeight
Public Member Functions
void set_vertex_count (int aCount)
void set_nweights (int aEdgeCount, const EdgeRecord *aEdges, const EdgeWeight *aWeightsForward, const EdgeWeight *aWeightsBackward)
void set_tweights (const EdgeWeight *aCapSource, const EdgeWeight *aCapSink)
TFlow max_flow ()
template<typename TPolicy >
TFlow max_flow (TPolicy &aPolicy)
template<typename TTraceObject >
TFlow max_flow_with_tracing (TTraceObject &aTraceObject)
template<typename TPolicy , typename TTraceObject >
TFlow max_flow_with_tracing (TPolicy &aPolicy, TTraceObject &aTraceObject)
template<typename THostArrayView >
void fill_segments (THostArrayView aVertices, uint8_t mMask=255, uint8_t mBackground=0) const
void debug_print ()
Public Attributes
GraphCutData< TFlow > mGraphData
std::vector< int > mLevelStarts
ParallelQueue< int > mVertexQueue
ParallelQueue< int > mLevelStartsQueue
thrust::device_vector< EdgeWeight > mSourceTLinks
thrust::device_vector< EdgeWeight > mSinkTLinks
thrust::device_vector< EdgeWeight > mExcess
thrust::device_vector< int > mLabels
thrust::device_vector< int > mNeighbors
thrust::device_vector< int > mSecondVertices
thrust::device_vector< int > mEdges
thrust::device_vector< EdgeResidualsRecord< TFlow > > mResiduals
thrust::device_vector< EdgeWeight > mEdgeWeightsForward
thrust::device_vector< EdgeWeight > mEdgeWeightsBackward
thrust::device_vector< EdgeWeight > mSinkFlow
Detailed Description
template<typename TFlow>
class cugip::Graph< TFlow >
Definition at line 48 of file graph_cut.hpp.
Member Typedef Documentation
template<typename TFlow > typedef TFlow cugip::Graph< TFlow >::EdgeWeight
Definition at line 52 of file graph_cut.hpp.
template<typename TFlow > typedef int cugip::Graph< TFlow >::VertexId
Definition at line 51 of file graph_cut.hpp.
Member Function Documentation
template<typename TFlow > void cugip::Graph< TFlow >::debug_print ()
Definition at line 339 of file graph_cut.hpp.
template<typename TFlow > template<typename THostArrayView > void cugip::Graph< TFlow >::fill_segments (THostArrayView aVertices, uint8_t mMask = 255, uint8_t mBackground = 0) const
Todo:
prevent another allocation on GPU
Definition at line 321 of file graph_cut.hpp.
References cugip::copy(), and cugip::transform().
template<typename TFlow > TFlow cugip::Graph< TFlow >::max_flow () inline
Definition at line 70 of file graph_cut.hpp.
template<typename TFlow > template<typename TPolicy > TFlow cugip::Graph< TFlow >::max_flow (TPolicy & aPolicy) inline
Definition at line 77 of file graph_cut.hpp.
template<typename TFlow > template<typename TTraceObject > TFlow cugip::Graph< TFlow >::max_flow_with_tracing (TTraceObject & aTraceObject) inline
Definition at line 84 of file graph_cut.hpp.
References cugip::MinimalGraphCutComputation< TGraph >::run(), and cugip::MinimalGraphCutComputation< TGraph >::setGraph().
template<typename TFlow > template<typename TPolicy , typename TTraceObject > TFlow cugip::Graph< TFlow >::max_flow_with_tracing (TPolicy & aPolicy, TTraceObject & aTraceObject) inline
Definition at line 94 of file graph_cut.hpp.
References cugip::MinimalGraphCutComputation< TGraph >::run(), and cugip::MinimalGraphCutComputation< TGraph >::setGraph().
template<typename TFlow > void cugip::Graph< TFlow >::set_nweights (int aEdgeCount, const EdgeRecord * aEdges, const EdgeWeight * aWeightsForward, const EdgeWeight * aWeightsBackward)
Definition at line 241 of file graph_cut.hpp.
References cugip::CONNECTION_VERTEX, cugip::copy(), CUGIP_DPRINT, cugip::EdgeRecord::first, and cugip::EdgeRecord::second.
template<typename TFlow > void cugip::Graph< TFlow >::set_tweights (const EdgeWeight * aCapSource, const EdgeWeight * aCapSink)
Definition at line 294 of file graph_cut.hpp.
References cugip::copy(), and cugip::fill().
template<typename TFlow > void cugip::Graph< TFlow >::set_vertex_count (int aCount)
Definition at line 215 of file graph_cut.hpp.
References CUGIP_DPRINT, cugip::Sink, and cugip::Source.
Member Data Documentation
template<typename TFlow > thrust::device_vector<int> cugip::Graph< TFlow >::mEdges
Definition at line 139 of file graph_cut.hpp.
template<typename TFlow > thrust::device_vector<EdgeWeight> cugip::Graph< TFlow >::mEdgeWeightsBackward
Definition at line 143 of file graph_cut.hpp.
template<typename TFlow > thrust::device_vector<EdgeWeight> cugip::Graph< TFlow >::mEdgeWeightsForward
Definition at line 142 of file graph_cut.hpp.
template<typename TFlow > thrust::device_vector<EdgeWeight> cugip::Graph< TFlow >::mExcess
Definition at line 134 of file graph_cut.hpp.
template<typename TFlow > GraphCutData<TFlow> cugip::Graph< TFlow >::mGraphData
Definition at line 126 of file graph_cut.hpp.
template<typename TFlow > thrust::device_vector<int> cugip::Graph< TFlow >::mLabels
Definition at line 135 of file graph_cut.hpp.
template<typename TFlow > std::vector<int> cugip::Graph< TFlow >::mLevelStarts
Definition at line 128 of file graph_cut.hpp.
template<typename TFlow > ParallelQueue<int> cugip::Graph< TFlow >::mLevelStartsQueue
Definition at line 130 of file graph_cut.hpp.
template<typename TFlow > thrust::device_vector<int> cugip::Graph< TFlow >::mNeighbors
Definition at line 136 of file graph_cut.hpp.
template<typename TFlow > thrust::device_vector<EdgeResidualsRecord<TFlow> > cugip::Graph< TFlow >::mResiduals
Definition at line 140 of file graph_cut.hpp.
template<typename TFlow > thrust::device_vector<int> cugip::Graph< TFlow >::mSecondVertices
Definition at line 138 of file graph_cut.hpp.
template<typename TFlow > thrust::device_vector<EdgeWeight> cugip::Graph< TFlow >::mSinkFlow
Definition at line 145 of file graph_cut.hpp.
template<typename TFlow > thrust::device_vector<EdgeWeight> cugip::Graph< TFlow >::mSinkTLinks
Definition at line 133 of file graph_cut.hpp.
template<typename TFlow > thrust::device_vector<EdgeWeight> cugip::Graph< TFlow >::mSourceTLinks
Definition at line 132 of file graph_cut.hpp.
template<typename TFlow > ParallelQueue<int> cugip::Graph< TFlow >::mVertexQueue
Definition at line 129 of file graph_cut.hpp.
The documentation for this class was generated from the following file:
/home/johny/programming/git/MedV4D/extern/cugip/include/cugip/advanced_operations/graph_cut.hpp