CUGIP: cugip::detail::SharedMemory< TElement, TStaticSize, TThreadBlockSize > Class Template Reference
cugip::detail::SharedMemory< TElement, TStaticSize, TThreadBlockSize > Class Template Reference
#include <shared_memory.hpp>
Public Types
typedef simple_vector< int, cDimension > coord_t
Public Member Functions
template<typename TView >
CUGIP_DECL_DEVICE void load (TView aView, coord_t aCorner)
template<typename TView >
CUGIP_DECL_DEVICE void loadZeroOut (TView aView, coord_t aCorner)
CUGIP_DECL_DEVICE TElement & get (coord_t aCoords)
CUGIP_DECL_DEVICE device_image_view< TElement, cDimension > view ()
CUGIP_DECL_DEVICE void shift_up (int aShift)
CUGIP_DECL_DEVICE void shift_up2 (int aShift)
template<typename TView >
CUGIP_DECL_DEVICE void shift_and_load (TView aView, coord_t aCorner, int aShift)
Static Public Attributes
static constexpr int cDimension = TStaticSize::cDimension
static constexpr int cElementCount = TStaticSize::count()
static constexpr int cBufferSize = cElementCount * sizeof(TElement)
static constexpr int cLayerSize = TStaticSize::count() / TStaticSize::last()
Protected Attributes
int8_t data [cBufferSize]
Detailed Description
template<typename TElement, typename TStaticSize, typename TThreadBlockSize = RunTimeThreadBlockSize>
class cugip::detail::SharedMemory< TElement, TStaticSize, TThreadBlockSize >
Definition at line 21 of file shared_memory.hpp.
Member Typedef Documentation
template<typename TElement , typename TStaticSize , typename TThreadBlockSize = RunTimeThreadBlockSize> typedef simple_vector<int, cDimension> cugip::detail::SharedMemory< TElement, TStaticSize, TThreadBlockSize >::coord_t
Definition at line 29 of file shared_memory.hpp.
Member Function Documentation
template<typename TElement , typename TStaticSize , typename TThreadBlockSize = RunTimeThreadBlockSize> CUGIP_DECL_DEVICE TElement& cugip::detail::SharedMemory< TElement, TStaticSize, TThreadBlockSize >::get (coord_t aCoords) inline
Definition at line 72 of file shared_memory.hpp.
References CUGIP_DECL_DEVICE, cugip::get_linear_access_index(), and cugip::to_vector().
template<typename TElement , typename TStaticSize , typename TThreadBlockSize = RunTimeThreadBlockSize> template<typename TView > CUGIP_DECL_DEVICE void cugip::detail::SharedMemory< TElement, TStaticSize, TThreadBlockSize >::load (TView aView, coord_t aCorner) inline
Definition at line 33 of file shared_memory.hpp.
References CUGIP_DECL_DEVICE, cugip::index_from_linear_access_index(), cugip::max_coords(), cugip::min_coords(), cugip::threadOrderFromIndex(), and cugip::to_vector().
template<typename TElement , typename TStaticSize , typename TThreadBlockSize = RunTimeThreadBlockSize> template<typename TView > CUGIP_DECL_DEVICE void cugip::detail::SharedMemory< TElement, TStaticSize, TThreadBlockSize >::loadZeroOut (TView aView, coord_t aCorner) inline
Definition at line 50 of file shared_memory.hpp.
References CUGIP_DECL_DEVICE, cugip::index_from_linear_access_index(), cugip::max_coords(), cugip::min_coords(), cugip::threadOrderFromIndex(), and cugip::to_vector().
template<typename TElement , typename TStaticSize , typename TThreadBlockSize = RunTimeThreadBlockSize> template<typename TView > CUGIP_DECL_DEVICE void cugip::detail::SharedMemory< TElement, TStaticSize, TThreadBlockSize >::shift_and_load (TView aView, coord_t aCorner, int aShift) inline
Definition at line 124 of file shared_memory.hpp.
References cugip::index_from_linear_access_index(), cugip::max_coords(), cugip::min_coords(), and cugip::threadOrderFromIndex().
template<typename TElement , typename TStaticSize , typename TThreadBlockSize = RunTimeThreadBlockSize> CUGIP_DECL_DEVICE void cugip::detail::SharedMemory< TElement, TStaticSize, TThreadBlockSize >::shift_up (int aShift) inline
Definition at line 87 of file shared_memory.hpp.
References CUGIP_DECL_DEVICE, and cugip::threadOrderFromIndex().
template<typename TElement , typename TStaticSize , typename TThreadBlockSize = RunTimeThreadBlockSize> CUGIP_DECL_DEVICE void cugip::detail::SharedMemory< TElement, TStaticSize, TThreadBlockSize >::shift_up2 (int aShift) inline
Definition at line 105 of file shared_memory.hpp.
References CUGIP_DECL_DEVICE, and cugip::threadOrderFromIndex().
template<typename TElement , typename TStaticSize , typename TThreadBlockSize = RunTimeThreadBlockSize> CUGIP_DECL_DEVICE device_image_view<TElement, cDimension> cugip::detail::SharedMemory< TElement, TStaticSize, TThreadBlockSize >::view () inline
Definition at line 80 of file shared_memory.hpp.
References CUGIP_DECL_DEVICE, cugip::makeDeviceImageView(), and cugip::to_vector().
Referenced by cugip::detail::kernel_nonlocal_means(), and cugip::detail::kernel_nonlocal_means2().
Member Data Documentation
template<typename TElement , typename TStaticSize , typename TThreadBlockSize = RunTimeThreadBlockSize> constexpr int cugip::detail::SharedMemory< TElement, TStaticSize, TThreadBlockSize >::cBufferSize = cElementCount * sizeof(TElement) static
Definition at line 26 of file shared_memory.hpp.
template<typename TElement , typename TStaticSize , typename TThreadBlockSize = RunTimeThreadBlockSize> constexpr int cugip::detail::SharedMemory< TElement, TStaticSize, TThreadBlockSize >::cDimension = TStaticSize::cDimension static
Definition at line 24 of file shared_memory.hpp.
template<typename TElement , typename TStaticSize , typename TThreadBlockSize = RunTimeThreadBlockSize> constexpr int cugip::detail::SharedMemory< TElement, TStaticSize, TThreadBlockSize >::cElementCount = TStaticSize::count() static
Definition at line 25 of file shared_memory.hpp.
template<typename TElement , typename TStaticSize , typename TThreadBlockSize = RunTimeThreadBlockSize> constexpr int cugip::detail::SharedMemory< TElement, TStaticSize, TThreadBlockSize >::cLayerSize = TStaticSize::count() / TStaticSize::last() static
Definition at line 27 of file shared_memory.hpp.
template<typename TElement , typename TStaticSize , typename TThreadBlockSize = RunTimeThreadBlockSize> int8_t cugip::detail::SharedMemory< TElement, TStaticSize, TThreadBlockSize >::data[cBufferSize] protected
Definition at line 144 of file shared_memory.hpp.
The documentation for this class was generated from the following file:
/home/johny/programming/git/MedV4D/extern/cugip/include/cugip/detail/shared_memory.hpp