CUGIP: cugip::MultiIntervalMeasurement< TTimerSet, tTimerId > Class Template Reference
cugip::MultiIntervalMeasurement< TTimerSet, tTimerId > Class Template Reference
#include <timers.hpp>
Public Member Functions
MultiIntervalMeasurement ()
MultiIntervalMeasurement (TTimerSet *timer_set, typename TTimerSet::Id id)
MultiIntervalMeasurement (MultiIntervalMeasurement &&other)
~MultiIntervalMeasurement ()
void stopAll ()
template<int... tStoppedTimer>
void stop ()
template<int... tResetedTimer>
void reset ()
MultiIntervalMeasurement & operator= (MultiIntervalMeasurement &&other)
Protected Member Functions
template<int tTimer>
int handleTimerStop (std::chrono::high_resolution_clock::time_point now)
Protected Attributes
std::chrono::high_resolution_clock::time_point start_
TTimerSet::Id id_
TTimerSet * timer_set_
std::bitset< TTimerSet::kTimerCount > active_durations_
Detailed Description
template<typename TTimerSet, int... tTimerId>
class cugip::MultiIntervalMeasurement< TTimerSet, tTimerId >
Definition at line 51 of file timers.hpp.
Constructor & Destructor Documentation
template<typename TTimerSet , int... tTimerId> cugip::MultiIntervalMeasurement< TTimerSet, tTimerId >::MultiIntervalMeasurement () inline
Definition at line 53 of file timers.hpp.
template<typename TTimerSet , int... tTimerId> cugip::MultiIntervalMeasurement< TTimerSet, tTimerId >::MultiIntervalMeasurement (TTimerSet * timer_set, typename TTimerSet::Id id) inline
Definition at line 57 of file timers.hpp.
References cugip::ignoreReturnValues().
template<typename TTimerSet , int... tTimerId> cugip::MultiIntervalMeasurement< TTimerSet, tTimerId >::MultiIntervalMeasurement (MultiIntervalMeasurement< TTimerSet, tTimerId > && other) inline
Definition at line 65 of file timers.hpp.
template<typename TTimerSet , int... tTimerId> cugip::MultiIntervalMeasurement< TTimerSet, tTimerId >::~MultiIntervalMeasurement () inline
Definition at line 74 of file timers.hpp.
Member Function Documentation
template<typename TTimerSet , int... tTimerId> template<int tTimer> int cugip::MultiIntervalMeasurement< TTimerSet, tTimerId >::handleTimerStop (std::chrono::high_resolution_clock::time_point now) inline protected
Definition at line 114 of file timers.hpp.
template<typename TTimerSet , int... tTimerId> MultiIntervalMeasurement& cugip::MultiIntervalMeasurement< TTimerSet, tTimerId >::operator= (MultiIntervalMeasurement< TTimerSet, tTimerId > && other) inline
Definition at line 102 of file timers.hpp.
template<typename TTimerSet , int... tTimerId> template<int... tResetedTimer> void cugip::MultiIntervalMeasurement< TTimerSet, tTimerId >::reset () inline
Definition at line 95 of file timers.hpp.
References cugip::ignoreReturnValues().
template<typename TTimerSet , int... tTimerId> template<int... tStoppedTimer> void cugip::MultiIntervalMeasurement< TTimerSet, tTimerId >::stop () inline
Definition at line 88 of file timers.hpp.
References cugip::ignoreReturnValues().
template<typename TTimerSet , int... tTimerId> void cugip::MultiIntervalMeasurement< TTimerSet, tTimerId >::stopAll () inline
Definition at line 78 of file timers.hpp.
References cugip::ignoreReturnValues().
Member Data Documentation
template<typename TTimerSet , int... tTimerId> std::bitset<TTimerSet::kTimerCount> cugip::MultiIntervalMeasurement< TTimerSet, tTimerId >::active_durations_ protected
Definition at line 128 of file timers.hpp.
template<typename TTimerSet , int... tTimerId> TTimerSet::Id cugip::MultiIntervalMeasurement< TTimerSet, tTimerId >::id_ protected
Definition at line 124 of file timers.hpp.
template<typename TTimerSet , int... tTimerId> std::chrono::high_resolution_clock::time_point cugip::MultiIntervalMeasurement< TTimerSet, tTimerId >::start_ protected
Definition at line 123 of file timers.hpp.
template<typename TTimerSet , int... tTimerId> TTimerSet* cugip::MultiIntervalMeasurement< TTimerSet, tTimerId >::timer_set_ protected
Definition at line 126 of file timers.hpp.
The documentation for this class was generated from the following file:
/home/johny/programming/git/MedV4D/extern/cugip/include/cugip/timers.hpp