CUGIP: cugip::image_locator< TImageView, TBorderHandling > Class Template Reference
cugip::image_locator< TImageView, TBorderHandling > Class Template Reference
#include <image_locator.hpp>
Public Types
typedef TImageView::extents_t extents_t
typedef TImageView::coord_t coord_t
typedef TImageView::diff_t diff_t
typedef TImageView::value_type value_type
typedef
TImageView::const_value_type const_value_type
typedef TImageView::accessed_type accessed_type
Public Member Functions
CUGIP_DECL_HYBRID image_locator (TImageView &aView, coord_t aCoords)
CUGIP_DECL_HYBRID accessed_type operator[] (diff_t aOffset)
CUGIP_DECL_HYBRID accessed_type get ()
template<size_t tDimIdx>
CUGIP_DECL_HYBRID accessed_type dim_offset (int aOffset)
Protected Attributes
TImageView & mView
coord_t mCoords
Detailed Description
template<typename TImageView, typename TBorderHandling = border_handling_none_t>
class cugip::image_locator< TImageView, TBorderHandling >
Definition at line 41 of file image_locator.hpp.
Member Typedef Documentation
template<typename TImageView , typename TBorderHandling = border_handling_none_t> typedef TImageView::accessed_type cugip::image_locator< TImageView, TBorderHandling >::accessed_type
Definition at line 50 of file image_locator.hpp.
template<typename TImageView , typename TBorderHandling = border_handling_none_t> typedef TImageView::const_value_type cugip::image_locator< TImageView, TBorderHandling >::const_value_type
Definition at line 48 of file image_locator.hpp.
template<typename TImageView , typename TBorderHandling = border_handling_none_t> typedef TImageView::coord_t cugip::image_locator< TImageView, TBorderHandling >::coord_t
Definition at line 45 of file image_locator.hpp.
template<typename TImageView , typename TBorderHandling = border_handling_none_t> typedef TImageView::diff_t cugip::image_locator< TImageView, TBorderHandling >::diff_t
Definition at line 46 of file image_locator.hpp.
template<typename TImageView , typename TBorderHandling = border_handling_none_t> typedef TImageView::extents_t cugip::image_locator< TImageView, TBorderHandling >::extents_t
Definition at line 44 of file image_locator.hpp.
template<typename TImageView , typename TBorderHandling = border_handling_none_t> typedef TImageView::value_type cugip::image_locator< TImageView, TBorderHandling >::value_type
Definition at line 47 of file image_locator.hpp.
Constructor & Destructor Documentation
template<typename TImageView , typename TBorderHandling = border_handling_none_t> CUGIP_DECL_HYBRID cugip::image_locator< TImageView, TBorderHandling >::image_locator (TImageView & aView, coord_t aCoords) [inline]
Definition at line 53 of file image_locator.hpp.
Member Function Documentation
template<typename TImageView , typename TBorderHandling = border_handling_none_t> template<size_t tDimIdx> CUGIP_DECL_HYBRID accessed_type cugip::image_locator< TImageView, TBorderHandling >::dim_offset (int aOffset) [inline]
Definition at line 72 of file image_locator.hpp.
References cugip::get(), cugip::max_coords(), cugip::image_locator< TImageView, TBorderHandling >::mCoords, cugip::min_coords(), and cugip::image_locator< TImageView, TBorderHandling >::mView.
template<typename TImageView , typename TBorderHandling = border_handling_none_t> CUGIP_DECL_HYBRID accessed_type cugip::image_locator< TImageView, TBorderHandling >::get () [inline]
Definition at line 65 of file image_locator.hpp.
References cugip::image_locator< TImageView, TBorderHandling >::mCoords, and cugip::image_locator< TImageView, TBorderHandling >::mView.
template<typename TImageView , typename TBorderHandling = border_handling_none_t> CUGIP_DECL_HYBRID accessed_type cugip::image_locator< TImageView, TBorderHandling >::operator[] (diff_t aOffset) [inline]
Todo:
Definition at line 57 of file image_locator.hpp.
References cugip::max_coords(), cugip::image_locator< TImageView, TBorderHandling >::mCoords, cugip::min_coords(), and cugip::image_locator< TImageView, TBorderHandling >::mView.
Member Data Documentation
template<typename TImageView , typename TBorderHandling = border_handling_none_t> coord_t cugip::image_locator< TImageView, TBorderHandling >::mCoords [protected]
Definition at line 82 of file image_locator.hpp.
Referenced by cugip::image_locator< TImageView, TBorderHandling >::dim_offset(), cugip::image_locator< TImageView, TBorderHandling >::get(), and cugip::image_locator< TImageView, TBorderHandling >::operator[]().
template<typename TImageView , typename TBorderHandling = border_handling_none_t> TImageView& cugip::image_locator< TImageView, TBorderHandling >::mView [protected]
Definition at line 81 of file image_locator.hpp.
Referenced by cugip::image_locator< TImageView, TBorderHandling >::dim_offset(), cugip::image_locator< TImageView, TBorderHandling >::get(), and cugip::image_locator< TImageView, TBorderHandling >::operator[]().
The documentation for this class was generated from the following file:
/home/johny/Dropbox/programming/git/cugip/include/cugip/image_locator.hpp