CUGIP: cugip::ParallelQueueView< TType > Class Template Reference
cugip::ParallelQueueView< TType > Class Template Reference
#include <parallel_queue.hpp>
Public Member Functions
CUGIP_DECL_DEVICE int allocate (int aItemCount)
CUGIP_DECL_DEVICE int append (const TType &aItem)
CUGIP_DECL_DEVICE int push_back (const TType &aItem)
CUGIP_DECL_HYBRID int size ()
CUGIP_DECL_HOST int host_size ()
CUGIP_DECL_DEVICE int device_size ()
CUGIP_DECL_HOST void clear ()
CUGIP_DECL_DEVICE void clear_device ()
CUGIP_DECL_DEVICE TType & operator[] (int aIndex)
CUGIP_DECL_DEVICE TType & back ()
CUGIP_DECL_DEVICE TType & get_device (int aIndex)
CUGIP_DECL_DEVICE TType & get_device (int aIndex) const
Public Attributes
TType * mData
device_ptr< int > mSize
Detailed Description
template<typename TType>
class cugip::ParallelQueueView< TType >
Definition at line 21 of file parallel_queue.hpp.
Member Function Documentation
template<typename TType> CUGIP_DECL_DEVICE int cugip::ParallelQueueView< TType >::allocate (int aItemCount) inline
Definition at line 25 of file parallel_queue.hpp.
Referenced by cugip::initBFSKernel(), and cugip::TileProcessor< TGraph, TPolicy >::processTile().
template<typename TType> CUGIP_DECL_DEVICE int cugip::ParallelQueueView< TType >::append (const TType & aItem) inline
Definition at line 31 of file parallel_queue.hpp.
Referenced by cugip::bfsPropagationMultiIterationGlobalSyncKernel(), cugip::bfsPropagationMultiIterationKernel(), cugip::propagateFromVertex(), cugip::propagateFromVertex2(), and cugip::ParallelQueueView< int >::push_back().
template<typename TType> CUGIP_DECL_DEVICE TType& cugip::ParallelQueueView< TType >::back () inline
Definition at line 86 of file parallel_queue.hpp.
Referenced by cugip::relabel_compute_dynamic().
template<typename TType> CUGIP_DECL_HOST void cugip::ParallelQueueView< TType >::clear () inline
Definition at line 68 of file parallel_queue.hpp.
Referenced by cugip::Relabel< TGraphData, TPolicy >::init_bfs().
template<typename TType> CUGIP_DECL_DEVICE void cugip::ParallelQueueView< TType >::clear_device () inline
Definition at line 74 of file parallel_queue.hpp.
Referenced by cugip::relabel_compute_dynamic().
template<typename TType> CUGIP_DECL_DEVICE int cugip::ParallelQueueView< TType >::device_size () inline
Definition at line 62 of file parallel_queue.hpp.
Referenced by cugip::bfsPropagationMultiIterationGlobalSyncKernel(), cugip::bfsPropagationMultiIterationKernel(), and cugip::ParallelQueueView< int >::size().
template<typename TType> CUGIP_DECL_DEVICE TType& cugip::ParallelQueueView< TType >::get_device (int aIndex) inline
Definition at line 96 of file parallel_queue.hpp.
Referenced by cugip::ParallelQueueView< int >::back(), cugip::initBFSKernel(), cugip::NaiveSweepPass< TGraph, TPolicy >::invoke(), cugip::NaiveSweepPass2< TGraph, TPolicy >::invoke(), cugip::Tile< TGraph >::load(), cugip::ParallelQueueView< int >::operator[](), cugip::TileProcessor< TGraph, TPolicy >::processTile(), and cugip::pushImplementation().
template<typename TType> CUGIP_DECL_DEVICE TType& cugip::ParallelQueueView< TType >::get_device (int aIndex) const inline
Definition at line 105 of file parallel_queue.hpp.
template<typename TType> CUGIP_DECL_HOST int cugip::ParallelQueueView< TType >::host_size () inline
Definition at line 55 of file parallel_queue.hpp.
Referenced by cugip::ParallelQueueView< int >::size().
template<typename TType> CUGIP_DECL_DEVICE TType& cugip::ParallelQueueView< TType >::operator[] (int aIndex) inline
Definition at line 80 of file parallel_queue.hpp.
template<typename TType> CUGIP_DECL_DEVICE int cugip::ParallelQueueView< TType >::push_back (const TType & aItem) inline
Definition at line 39 of file parallel_queue.hpp.
Referenced by cugip::relabel_compute_dynamic().
template<typename TType> CUGIP_DECL_HYBRID int cugip::ParallelQueueView< TType >::size () inline
Definition at line 45 of file parallel_queue.hpp.
Referenced by cugip::Push< TGraphData, TPolicy >::PushIteration< tImplementationId >::compute(), cugip::Relabel< TGraphData, TPolicy >::compute(), cugip::ParallelQueue< int >::fill_host(), cugip::relabel_compute_dynamic(), and cugip::ParallelQueue< int >::resize().
Member Data Documentation
template<typename TType> TType* cugip::ParallelQueueView< TType >::mData
Definition at line 110 of file parallel_queue.hpp.
Referenced by cugip::ParallelQueueView< int >::append(), and cugip::ParallelQueueView< int >::get_device().
template<typename TType> device_ptr<int> cugip::ParallelQueueView< TType >::mSize
Definition at line 111 of file parallel_queue.hpp.
Referenced by cugip::ParallelQueueView< int >::allocate(), cugip::ParallelQueueView< int >::append(), cugip::ParallelQueueView< int >::back(), cugip::ParallelQueueView< int >::clear(), cugip::ParallelQueueView< int >::clear_device(), cugip::ParallelQueueView< int >::device_size(), and cugip::ParallelQueueView< int >::host_size().
The documentation for this class was generated from the following file:
/home/johny/programming/git/MedV4D/extern/cugip/include/cugip/parallel_queue.hpp