CUGIP: cugip::matrix< TType, tRowCount, tColCount > Class Template Reference
cugip::matrix< TType, tRowCount, tColCount > Class Template Reference
#include <matrix.hpp>
Public Types
typedef simple_vector< simple_vector< TType, tColCount >, tRowCount > base_type
typedef TType element_t
Public Types inherited from cugip::simple_vector< simple_vector< TType, tColCount >, tRowCount >
typedef simple_vector< TType, tColCount > coord_t
typedef simple_vector< simple_vector< TType, tColCount >, tDim > this_t
Public Member Functions
CUGIP_DECL_HYBRID matrix ()
CUGIP_DECL_HYBRID TType & get (int aRow, int aCol)
CUGIP_DECL_HYBRID const TType & get (int aRow, int aCol) const
CUGIP_DECL_HYBRID simple_vector< TType, tRowCount > column (int aCol) const
CUGIP_DECL_HYBRID column_accessor< matrix< TType, tRowCount, tColCount > > column (int aCol)
CUGIP_DECL_HYBRID simple_vector< TType, tColCount > row (int aRow) const
CUGIP_DECL_HYBRID simple_vector< TType, tColCount > & row (int aRow)
Public Member Functions inherited from cugip::simple_vector< simple_vector< TType, tColCount >, tRowCount >
CUGIP_DECL_HYBRID simple_vector ()
CUGIP_DECL_HYBRID simple_vector (simple_vector< TType, tColCount >aValue, FillFlag)
CUGIP_DECL_HYBRID constexpr simple_vector (simple_vector< TType, tColCount >const &v0)
CUGIP_DECL_HYBRID constexpr simple_vector (simple_vector< TType, tColCount >const &v0, simple_vector< TType, tColCount >const &v1)
CUGIP_DECL_HYBRID constexpr simple_vector (simple_vector< TType, tColCount >const &v0, simple_vector< TType, tColCount >const &v1, simple_vector< TType, tColCount >const &v2)
CUGIP_DECL_HYBRID simple_vector (const simple_vector< TOtherCoordType, tDim > &aArg)
CUGIP_DECL_HYBRID simple_vector (std::initializer_list< simple_vector< TType, tColCount > > aList)
CUGIP_DECL_HYBRID simple_vector & operator= (const simple_vector< TOtherCoordType, tDim > &aArg)
CUGIP_DECL_HYBRID simple_vector & operator+= (const simple_vector< TOtherCoordType, tDim > &aArg)
CUGIP_DECL_HYBRID simple_vector & operator-= (const simple_vector< TOtherCoordType, tDim > &aArg)
CUGIP_DECL_HYBRID simple_vector operator- () const
CUGIP_DECL_HYBRID simple_vector< TType, tColCount >const & get () const
CUGIP_DECL_HYBRID simple_vector< TType, tColCount > & get ()
CUGIP_DECL_HYBRID const simple_vector< TType, tColCount > & operator[] (int aIdx) const
CUGIP_DECL_HYBRID simple_vector< TType, tColCount > & operator[] (int aIdx)
CUGIP_DECL_HYBRID void set (simple_vector< TType, tColCount >const &value)
Static Public Attributes
static constexpr int cRowCount = tRowCount
static constexpr int cColCount = tColCount
Static Public Attributes inherited from cugip::simple_vector< simple_vector< TType, tColCount >, tRowCount >
static constexpr int dim
Additional Inherited Members
Public Attributes inherited from cugip::simple_vector< simple_vector< TType, tColCount >, tRowCount >
simple_vector< TType, tColCount > mValues [tDim]
Detailed Description
template<typename TType, int tRowCount, int tColCount>
class cugip::matrix< TType, tRowCount, tColCount >
Definition at line 50 of file matrix.hpp.
Member Typedef Documentation
template<typename TType, int tRowCount, int tColCount> typedef simple_vector<simple_vector<TType, tColCount>, tRowCount> cugip::matrix< TType, tRowCount, tColCount >::base_type
Definition at line 53 of file matrix.hpp.
template<typename TType, int tRowCount, int tColCount> typedef TType cugip::matrix< TType, tRowCount, tColCount >::element_t
Definition at line 57 of file matrix.hpp.
Constructor & Destructor Documentation
template<typename TType, int tRowCount, int tColCount> CUGIP_DECL_HYBRID cugip::matrix< TType, tRowCount, tColCount >::matrix () inline
Definition at line 60 of file matrix.hpp.
References CUGIP_DECL_HYBRID.
Member Function Documentation
template<typename TType, int tRowCount, int tColCount> CUGIP_DECL_HYBRID simple_vector<TType, tRowCount> cugip::matrix< TType, tRowCount, tColCount >::column (int aCol) const inline
Todo:
get wrapper which provides access
Definition at line 81 of file matrix.hpp.
References CUGIP_DECL_HYBRID.
Referenced by cugip::eigen_vectors().
template<typename TType, int tRowCount, int tColCount> CUGIP_DECL_HYBRID column_accessor<matrix<TType, tRowCount, tColCount> > cugip::matrix< TType, tRowCount, tColCount >::column (int aCol) inline
Definition at line 92 of file matrix.hpp.
References CUGIP_DECL_HYBRID.
template<typename TType, int tRowCount, int tColCount> CUGIP_DECL_HYBRID TType& cugip::matrix< TType, tRowCount, tColCount >::get (int aRow, int aCol) inline
Definition at line 66 of file matrix.hpp.
References CUGIP_DECL_HYBRID.
Referenced by cugip::matrix_trace().
template<typename TType, int tRowCount, int tColCount> CUGIP_DECL_HYBRID const TType& cugip::matrix< TType, tRowCount, tColCount >::get (int aRow, int aCol) const inline
Definition at line 73 of file matrix.hpp.
References CUGIP_DECL_HYBRID.
template<typename TType, int tRowCount, int tColCount> CUGIP_DECL_HYBRID simple_vector<TType, tColCount> cugip::matrix< TType, tRowCount, tColCount >::row (int aRow) const inline
Definition at line 99 of file matrix.hpp.
References CUGIP_DECL_HYBRID.
Referenced by cugip::matrix_from_eigen_vectors_and_values().
template<typename TType, int tRowCount, int tColCount> CUGIP_DECL_HYBRID simple_vector<TType, tColCount>& cugip::matrix< TType, tRowCount, tColCount >::row (int aRow) inline
Definition at line 106 of file matrix.hpp.
Member Data Documentation
template<typename TType, int tRowCount, int tColCount> constexpr int cugip::matrix< TType, tRowCount, tColCount >::cColCount = tColCount static
Definition at line 55 of file matrix.hpp.
template<typename TType, int tRowCount, int tColCount> constexpr int cugip::matrix< TType, tRowCount, tColCount >::cRowCount = tRowCount static
Definition at line 54 of file matrix.hpp.
The documentation for this class was generated from the following file:
/home/johny/programming/git/MedV4D/extern/cugip/include/cugip/math/matrix.hpp