CUGIP: cugip::device_image< TElement, tDim > Class Template Reference
cugip::device_image< TElement, tDim > Class Template Reference
#include <image.hpp>
Public Types
typedef device_image_view< TElement, tDim > view_t
typedef const_device_image_view< TElement, tDim > const_view_t
typedef TElement element_t
typedef TElement value_type
typedef dim_traits< tDim >::extents_t extents_t
Public Member Functions
device_image ()
device_image (extents_t aExtents)
device_image (int aS0)
device_image (int aS0, int aS1)
device_image (int aS0, int aS1, int aS2)
device_image (device_image &&aOther)=default
device_image & operator= (device_image &&aOther)=default
device_image & operator= (const device_image &)=delete
device_image (const device_image &)=delete
CUGIP_DECL_HYBRID extents_t dimensions () const
view_t view ()
const_view_t const_view () const
value_type * pointer () const
extents_t strides () const
void resize (extents_t aExtents)
void reset ()
Protected Attributes
memory_management< TElement, tDim >::device_memory_owner mData
Detailed Description
template<typename TElement, int tDim = 2>
class cugip::device_image< TElement, tDim >
Definition at line 23 of file image.hpp.
Member Typedef Documentation
template<typename TElement, int tDim = 2> typedef const_device_image_view<TElement, tDim> cugip::device_image< TElement, tDim >::const_view_t
Definition at line 27 of file image.hpp.
template<typename TElement, int tDim = 2> typedef TElement cugip::device_image< TElement, tDim >::element_t
Definition at line 28 of file image.hpp.
template<typename TElement, int tDim = 2> typedef dim_traits<tDim>::extents_t cugip::device_image< TElement, tDim >::extents_t
Definition at line 31 of file image.hpp.
template<typename TElement, int tDim = 2> typedef TElement cugip::device_image< TElement, tDim >::value_type
Definition at line 29 of file image.hpp.
template<typename TElement, int tDim = 2> typedef device_image_view<TElement, tDim> cugip::device_image< TElement, tDim >::view_t
Definition at line 26 of file image.hpp.
Constructor & Destructor Documentation
template<typename TElement, int tDim = 2> cugip::device_image< TElement, tDim >::device_image () inline
Definition at line 36 of file image.hpp.
Referenced by cugip::device_image< simple_vector< float, tDimension >, tDimension >::device_image().
template<typename TElement, int tDim = 2> cugip::device_image< TElement, tDim >::device_image (extents_t aExtents) inline
Definition at line 39 of file image.hpp.
template<typename TElement, int tDim = 2> cugip::device_image< TElement, tDim >::device_image (int aS0) inline
Definition at line 43 of file image.hpp.
template<typename TElement, int tDim = 2> cugip::device_image< TElement, tDim >::device_image (int aS0, int aS1) inline
Definition at line 47 of file image.hpp.
template<typename TElement, int tDim = 2> cugip::device_image< TElement, tDim >::device_image (int aS0, int aS1, int aS2) inline
Definition at line 51 of file image.hpp.
template<typename TElement, int tDim = 2> cugip::device_image< TElement, tDim >::device_image (device_image< TElement, tDim > && aOther) default
template<typename TElement, int tDim = 2> cugip::device_image< TElement, tDim >::device_image (const device_image< TElement, tDim > &) delete
Member Function Documentation
template<typename TElement, int tDim = 2> const_view_t cugip::device_image< TElement, tDim >::const_view () const inline
Definition at line 73 of file image.hpp.
template<typename TElement, int tDim = 2> CUGIP_DECL_HYBRID extents_t cugip::device_image< TElement, tDim >::dimensions () const inline
Definition at line 62 of file image.hpp.
Referenced by cugip::device_image< simple_vector< float, tDimension >, tDimension >::const_view(), and cugip::device_image< simple_vector< float, tDimension >, tDimension >::view().
template<typename TElement, int tDim = 2> device_image& cugip::device_image< TElement, tDim >::operator= (device_image< TElement, tDim > && aOther) default
Referenced by cugip::device_image< simple_vector< float, tDimension >, tDimension >::device_image().
template<typename TElement, int tDim = 2> device_image& cugip::device_image< TElement, tDim >::operator= (const device_image< TElement, tDim > &) delete
template<typename TElement, int tDim = 2> value_type* cugip::device_image< TElement, tDim >::pointer () const inline
Definition at line 80 of file image.hpp.
Referenced by cugip::device_image< simple_vector< float, tDimension >, tDimension >::const_view(), and cugip::device_image< simple_vector< float, tDimension >, tDimension >::view().
template<typename TElement, int tDim = 2> void cugip::device_image< TElement, tDim >::reset () inline
Definition at line 99 of file image.hpp.
template<typename TElement, int tDim = 2> void cugip::device_image< TElement, tDim >::resize (extents_t aExtents) inline
Definition at line 93 of file image.hpp.
template<typename TElement, int tDim = 2> extents_t cugip::device_image< TElement, tDim >::strides () const inline
Definition at line 86 of file image.hpp.
Referenced by cugip::device_image< simple_vector< float, tDimension >, tDimension >::const_view(), and cugip::device_image< simple_vector< float, tDimension >, tDimension >::view().
template<typename TElement, int tDim = 2> view_t cugip::device_image< TElement, tDim >::view () inline
Definition at line 66 of file image.hpp.
Member Data Documentation
template<typename TElement, int tDim = 2> memory_management<TElement, tDim>::device_memory_owner cugip::device_image< TElement, tDim >::mData protected
Definition at line 106 of file image.hpp.
Referenced by cugip::device_image< simple_vector< float, tDimension >, tDimension >::dimensions(), cugip::device_image< simple_vector< float, tDimension >, tDimension >::pointer(), cugip::device_image< simple_vector< float, tDimension >, tDimension >::reset(), cugip::device_image< simple_vector< float, tDimension >, tDimension >::resize(), and cugip::device_image< simple_vector< float, tDimension >, tDimension >::strides().
The documentation for this class was generated from the following file:
/home/johny/programming/git/MedV4D/extern/cugip/include/cugip/image.hpp