var dir_259520fd8c10d66b753d6da228310ad1 =
[
    [ "advanced_operations", "dir_0f572a35ef5e44b2b3aaf46079e5721e.html", "dir_0f572a35ef5e44b2b3aaf46079e5721e" ],
    [ "algebra", "dir_fb9f978a02080b5a9c59a1d3ce0add5d.html", "dir_fb9f978a02080b5a9c59a1d3ce0add5d" ],
    [ "basic_filters", "dir_4e723222579e3ff6577339876efac82b.html", "dir_4e723222579e3ff6577339876efac82b" ],
    [ "cellular_automata", "dir_20845e848c7895a7fdfee49e8bb74793.html", "dir_20845e848c7895a7fdfee49e8bb74793" ],
    [ "detail", "dir_b26d35d49736a50a4a36bb863f17c415.html", "dir_b26d35d49736a50a4a36bb863f17c415" ],
    [ "math", "dir_f488eaee5102920fcb2176703d2f15a2.html", "dir_f488eaee5102920fcb2176703d2f15a2" ],
    [ "access_utils.hpp", "access__utils_8hpp.html", "access__utils_8hpp" ],
    [ "copy.hpp", "copy_8hpp.html", "copy_8hpp" ],
    [ "cuda_utils.hpp", "cuda__utils_8hpp.html", "cuda__utils_8hpp" ],
    [ "device_flag.hpp", "device__flag_8hpp.html", [
      [ "device_flag_view", "structcugip_1_1device__flag__view.html", "structcugip_1_1device__flag__view" ],
      [ "device_flag", "structcugip_1_1device__flag.html", "structcugip_1_1device__flag" ]
    ] ],
    [ "element.hpp", "element_8hpp.html", "element_8hpp" ],
    [ "equivalence_management.hpp", "equivalence__management_8hpp.html", "equivalence__management_8hpp" ],
    [ "exception.hpp", "exception_8hpp.html", "exception_8hpp" ],
    [ "fill.hpp", "fill_8hpp.html", "fill_8hpp" ],
    [ "filter.hpp", "filter_8hpp.html", "filter_8hpp" ],
    [ "for_each.hpp", "for__each_8hpp.html", "for__each_8hpp" ],
    [ "functors.hpp", "functors_8hpp.html", [
      [ "negate", "structcugip_1_1negate.html", "structcugip_1_1negate" ],
      [ "mandelbrot_ftor", "structcugip_1_1mandelbrot__ftor.html", "structcugip_1_1mandelbrot__ftor" ],
      [ "grayscale_ftor", "structcugip_1_1grayscale__ftor.html", "structcugip_1_1grayscale__ftor" ],
      [ "thresholding_ftor", "structcugip_1_1thresholding__ftor.html", "structcugip_1_1thresholding__ftor" ],
      [ "gradient_magnitude", "structcugip_1_1gradient__magnitude.html", "structcugip_1_1gradient__magnitude" ],
      [ "convert_float_and_byte", "structcugip_1_1convert__float__and__byte.html", "structcugip_1_1convert__float__and__byte" ],
      [ "assign_color_ftor", "structcugip_1_1assign__color__ftor.html", "structcugip_1_1assign__color__ftor" ],
      [ "generate_basins_ftor", "structcugip_1_1generate__basins__ftor.html", "structcugip_1_1generate__basins__ftor" ],
      [ "generate_spiral_ftor", "structcugip_1_1generate__spiral__ftor.html", "structcugip_1_1generate__spiral__ftor" ],
      [ "SquareFunctor", "structcugip_1_1_square_functor.html", "structcugip_1_1_square_functor" ],
      [ "SquareRootFunctor", "structcugip_1_1_square_root_functor.html", "structcugip_1_1_square_root_functor" ],
      [ "MinFunctor", "structcugip_1_1_min_functor.html", "structcugip_1_1_min_functor" ],
      [ "MaxFunctor", "structcugip_1_1_max_functor.html", "structcugip_1_1_max_functor" ],
      [ "MultiplyByFactorFunctor", "structcugip_1_1_multiply_by_factor_functor.html", "structcugip_1_1_multiply_by_factor_functor" ],
      [ "AddValueFunctor", "structcugip_1_1_add_value_functor.html", "structcugip_1_1_add_value_functor" ],
      [ "AbsFunctor", "structcugip_1_1_abs_functor.html", "structcugip_1_1_abs_functor" ],
      [ "SumValuesFunctor", "structcugip_1_1_sum_values_functor.html", "structcugip_1_1_sum_values_functor" ],
      [ "ChannelSumFunctor", "structcugip_1_1_channel_sum_functor.html", "structcugip_1_1_channel_sum_functor" ],
      [ "LowerLimitFunctor", "structcugip_1_1_lower_limit_functor.html", "structcugip_1_1_lower_limit_functor" ],
      [ "UpperLimitFunctor", "structcugip_1_1_upper_limit_functor.html", "structcugip_1_1_upper_limit_functor" ],
      [ "LowerLimitReplacementFunctor", "structcugip_1_1_lower_limit_replacement_functor.html", "structcugip_1_1_lower_limit_replacement_functor" ],
      [ "UpperLimitReplacementFunctor", "structcugip_1_1_upper_limit_replacement_functor.html", "structcugip_1_1_upper_limit_replacement_functor" ],
      [ "LocalMinimumLabel", "structcugip_1_1_local_minimum_label.html", "structcugip_1_1_local_minimum_label" ],
      [ "HasSmallerNeighbor", "structcugip_1_1_has_smaller_neighbor.html", "structcugip_1_1_has_smaller_neighbor" ],
      [ "HandlePlateauBorder", "structcugip_1_1_handle_plateau_border.html", "structcugip_1_1_handle_plateau_border" ],
      [ "ZipValues", "structcugip_1_1_zip_values.html", "structcugip_1_1_zip_values" ],
      [ "GetChannel", "structcugip_1_1_get_channel.html", "structcugip_1_1_get_channel" ]
    ] ],
    [ "gil_utils.hpp", "gil__utils_8hpp.html", "gil__utils_8hpp" ],
    [ "host_image.hpp", "host__image_8hpp.html", "host__image_8hpp" ],
    [ "host_image_view.hpp", "host__image__view_8hpp.html", "host__image__view_8hpp" ],
    [ "image.hpp", "image_8hpp.html", "image_8hpp" ],
    [ "image_locator.hpp", "image__locator_8hpp.html", "image__locator_8hpp" ],
    [ "image_view.hpp", "image__view_8hpp.html", "image__view_8hpp" ],
    [ "itk_utils.hpp", "itk__utils_8hpp.html", "itk__utils_8hpp" ],
    [ "kernel_execution_utils.hpp", "kernel__execution__utils_8hpp.html", "kernel__execution__utils_8hpp" ],
    [ "math.hpp", "math_8hpp.html", "math_8hpp" ],
    [ "memory.hpp", "memory_8hpp.html", "memory_8hpp" ],
    [ "memory_view.hpp", "memory__view_8hpp.html", [
      [ "memory_view", "classcugip_1_1memory__view.html", "classcugip_1_1memory__view" ],
      [ "const_memory_view", "classcugip_1_1const__memory__view.html", "classcugip_1_1const__memory__view" ],
      [ "dimension< const_memory_view< TElement, tDim > >", "structcugip_1_1dimension_3_01const__memory__view_3_01_t_element_00_01t_dim_01_4_01_4.html", null ],
      [ "is_memory_view", "structcugip_1_1is__memory__view.html", null ],
      [ "is_memory_view< memory_view< TElement, tDim > >", "structcugip_1_1is__memory__view_3_01memory__view_3_01_t_element_00_01t_dim_01_4_01_4.html", null ],
      [ "is_memory_view< const_memory_view< TElement, tDim > >", "structcugip_1_1is__memory__view_3_01const__memory__view_3_01_t_element_00_01t_dim_01_4_01_4.html", null ]
    ] ],
    [ "meta_algorithm.hpp", "meta__algorithm_8hpp.html", null ],
    [ "neighborhood.hpp", "neighborhood_8hpp.html", [
      [ "VonNeumannNeighborhood", "structcugip_1_1_von_neumann_neighborhood.html", null ],
      [ "VonNeumannNeighborhood< 2 >", "structcugip_1_1_von_neumann_neighborhood_3_012_01_4.html", "structcugip_1_1_von_neumann_neighborhood_3_012_01_4" ],
      [ "VonNeumannNeighborhood< 3 >", "structcugip_1_1_von_neumann_neighborhood_3_013_01_4.html", "structcugip_1_1_von_neumann_neighborhood_3_013_01_4" ],
      [ "MooreNeighborhood", "structcugip_1_1_moore_neighborhood.html", null ],
      [ "MooreNeighborhood< 2 >", "structcugip_1_1_moore_neighborhood_3_012_01_4.html", "structcugip_1_1_moore_neighborhood_3_012_01_4" ],
      [ "MooreNeighborhood< 3 >", "structcugip_1_1_moore_neighborhood_3_013_01_4.html", "structcugip_1_1_moore_neighborhood_3_013_01_4" ],
      [ "NeighborhoodAccessor", "structcugip_1_1_neighborhood_accessor.html", "structcugip_1_1_neighborhood_accessor" ]
    ] ],
    [ "neighborhood_accessor.hpp", "neighborhood__accessor_8hpp.html", "neighborhood__accessor_8hpp" ],
    [ "parallel_queue.hpp", "parallel__queue_8hpp.html", [
      [ "ParallelQueueView", "classcugip_1_1_parallel_queue_view.html", "classcugip_1_1_parallel_queue_view" ],
      [ "ParallelQueue", "classcugip_1_1_parallel_queue.html", "classcugip_1_1_parallel_queue" ]
    ] ],
    [ "procedural_views.hpp", "procedural__views_8hpp.html", "procedural__views_8hpp" ],
    [ "reduce.hpp", "reduce_8hpp.html", "reduce_8hpp" ],
    [ "region.hpp", "region_8hpp.html", "region_8hpp" ],
    [ "scan.hpp", "scan_8hpp.html", "scan_8hpp" ],
    [ "static_int_sequence.hpp", "static__int__sequence_8hpp.html", "static__int__sequence_8hpp" ],
    [ "static_memory_block.hpp", "static__memory__block_8hpp.html", [
      [ "static_memory_block", "structcugip_1_1static__memory__block.html", "structcugip_1_1static__memory__block" ]
    ] ],
    [ "subview.hpp", "subview_8hpp.html", "subview_8hpp" ],
    [ "texture.hpp", "texture_8hpp.html", "texture_8hpp" ],
    [ "timers.hpp", "timers_8hpp.html", [
      [ "DurationRecord", "structcugip_1_1_duration_record.html", "structcugip_1_1_duration_record" ],
      [ "MultiIntervalMeasurement", "classcugip_1_1_multi_interval_measurement.html", "classcugip_1_1_multi_interval_measurement" ],
      [ "IntervalMeasurement", "classcugip_1_1_interval_measurement.html", "classcugip_1_1_interval_measurement" ],
      [ "AggregatingTimerSet", "classcugip_1_1_aggregating_timer_set.html", "classcugip_1_1_aggregating_timer_set" ]
    ] ],
    [ "traits.hpp", "traits_8hpp.html", [
      [ "IntValue", "structcugip_1_1_int_value.html", "structcugip_1_1_int_value" ],
      [ "dimension_1d_tag", "structcugip_1_1dimension__1d__tag.html", null ],
      [ "dimension_2d_tag", "structcugip_1_1dimension__2d__tag.html", null ],
      [ "dimension_3d_tag", "structcugip_1_1dimension__3d__tag.html", null ],
      [ "dimension_4d_tag", "structcugip_1_1dimension__4d__tag.html", null ],
      [ "dimension_helper", "structcugip_1_1dimension__helper.html", null ],
      [ "dimension_helper< 1 >", "structcugip_1_1dimension__helper_3_011_01_4.html", "structcugip_1_1dimension__helper_3_011_01_4" ],
      [ "dimension_helper< 2 >", "structcugip_1_1dimension__helper_3_012_01_4.html", "structcugip_1_1dimension__helper_3_012_01_4" ],
      [ "dimension_helper< 3 >", "structcugip_1_1dimension__helper_3_013_01_4.html", "structcugip_1_1dimension__helper_3_013_01_4" ],
      [ "dimension_helper< 4 >", "structcugip_1_1dimension__helper_3_014_01_4.html", "structcugip_1_1dimension__helper_3_014_01_4" ]
    ] ],
    [ "transform.hpp", "transform_8hpp.html", "transform_8hpp" ],
    [ "tuple.hpp", "tuple_8hpp.html", "tuple_8hpp" ],
    [ "union_find.hpp", "union__find_8hpp.html", [
      [ "device_union_find_view", "classcugip_1_1device__union__find__view.html", "classcugip_1_1device__union__find__view" ],
      [ "device_union_find", "classcugip_1_1device__union__find.html", "classcugip_1_1device__union__find" ]
    ] ],
    [ "utils.hpp", "utils_8hpp.html", "utils_8hpp" ],
    [ "view_arithmetics.hpp", "view__arithmetics_8hpp.html", "view__arithmetics_8hpp" ]
];