var files =
[
    [ "/home/johny/Dropbox/programming/git/cugip/include/cugip/access_utils.hpp", "access__utils_8hpp.html", "access__utils_8hpp" ],
    [ "/home/johny/Dropbox/programming/git/cugip/include/cugip/copy.hpp", "copy_8hpp.html", "copy_8hpp" ],
    [ "/home/johny/Dropbox/programming/git/cugip/include/cugip/device_flag.hpp", "device__flag_8hpp.html", "device__flag_8hpp" ],
    [ "/home/johny/Dropbox/programming/git/cugip/include/cugip/exception.hpp", "exception_8hpp.html", "exception_8hpp" ],
    [ "/home/johny/Dropbox/programming/git/cugip/include/cugip/fill.hpp", "fill_8hpp.html", "fill_8hpp" ],
    [ "/home/johny/Dropbox/programming/git/cugip/include/cugip/filter.hpp", "filter_8hpp.html", "filter_8hpp" ],
    [ "/home/johny/Dropbox/programming/git/cugip/include/cugip/for_each.hpp", "for__each_8hpp.html", "for__each_8hpp" ],
    [ "/home/johny/Dropbox/programming/git/cugip/include/cugip/functors.hpp", "functors_8hpp.html", null ],
    [ "/home/johny/Dropbox/programming/git/cugip/include/cugip/gil_utils.hpp", "gil__utils_8hpp.html", null ],
    [ "/home/johny/Dropbox/programming/git/cugip/include/cugip/image.hpp", "image_8hpp.html", "image_8hpp" ],
    [ "/home/johny/Dropbox/programming/git/cugip/include/cugip/image_locator.hpp", "image__locator_8hpp.html", "image__locator_8hpp" ],
    [ "/home/johny/Dropbox/programming/git/cugip/include/cugip/image_view.hpp", "image__view_8hpp.html", "image__view_8hpp" ],
    [ "/home/johny/Dropbox/programming/git/cugip/include/cugip/math.hpp", "math_8hpp.html", "math_8hpp" ],
    [ "/home/johny/Dropbox/programming/git/cugip/include/cugip/memory.hpp", "memory_8hpp.html", "memory_8hpp" ],
    [ "/home/johny/Dropbox/programming/git/cugip/include/cugip/meta_algorithm.hpp", "meta__algorithm_8hpp.html", null ],
    [ "/home/johny/Dropbox/programming/git/cugip/include/cugip/neighborhood_accessor.hpp", "neighborhood__accessor_8hpp.html", null ],
    [ "/home/johny/Dropbox/programming/git/cugip/include/cugip/traits.hpp", "traits_8hpp.html", null ],
    [ "/home/johny/Dropbox/programming/git/cugip/include/cugip/transform.hpp", "transform_8hpp.html", "transform_8hpp" ],
    [ "/home/johny/Dropbox/programming/git/cugip/include/cugip/utils.hpp", "utils_8hpp.html", "utils_8hpp" ],
    [ "/home/johny/Dropbox/programming/git/cugip/include/cugip/advanced_operations/coherence_enhancing_diffusion.hpp", "coherence__enhancing__diffusion_8hpp.html", "coherence__enhancing__diffusion_8hpp" ],
    [ "/home/johny/Dropbox/programming/git/cugip/include/cugip/algebra/arithmetics.hpp", "arithmetics_8hpp.html", "arithmetics_8hpp" ],
    [ "/home/johny/Dropbox/programming/git/cugip/include/cugip/basic_filters/connected_component_labeling.hpp", "connected__component__labeling_8hpp.html", "connected__component__labeling_8hpp" ],
    [ "/home/johny/Dropbox/programming/git/cugip/include/cugip/basic_filters/convolution.hpp", "convolution_8hpp.html", "convolution_8hpp" ],
    [ "/home/johny/Dropbox/programming/git/cugip/include/cugip/basic_filters/gaussian.hpp", "gaussian_8hpp.html", null ],
    [ "/home/johny/Dropbox/programming/git/cugip/include/cugip/basic_filters/gradient.hpp", "gradient_8hpp.html", null ],
    [ "/home/johny/Dropbox/programming/git/cugip/include/cugip/basic_filters/local_extremas.hpp", "local__extremas_8hpp.html", "local__extremas_8hpp" ],
    [ "/home/johny/Dropbox/programming/git/cugip/include/cugip/basic_filters/thresholding.hpp", "thresholding_8hpp.html", "thresholding_8hpp" ],
    [ "/home/johny/Dropbox/programming/git/cugip/include/cugip/basic_filters/watershed_transformation.hpp", "watershed__transformation_8hpp.html", "watershed__transformation_8hpp" ],
    [ "/home/johny/Dropbox/programming/git/cugip/include/cugip/detail/include.hpp", "include_8hpp.html", "include_8hpp" ],
    [ "/home/johny/Dropbox/programming/git/cugip/test/main.cpp", "main_8cpp.html", "main_8cpp" ]
];