CUGIP: /home/johny/programming/git/MedV4D/extern/cugip/test/generate_image.cpp File Reference
generate_image.cpp File Reference
#include <boost/gil/extension/io/jpeg_dynamic_io.hpp>
Functions
void generate_spiral (boost::gil::gray8_image_t::view_t aOut)
void generate_basins (boost::gil::gray8_image_t::view_t aOut)
int main ()
Function Documentation
void generate_basins (boost::gil::gray8_image_t::view_t aOut)
Referenced by main().
void generate_spiral (boost::gil::gray8_image_t::view_t aOut)
Referenced by main().
int main ()
Definition at line 12 of file generate_image.cpp.
References cugip::const_view(), generate_basins(), generate_spiral(), and cugip::view().