CUGIP: Math
Math
Classes
struct cugip::AsyncCellOperationWithGlobalState< TNeighborhood, TRule, TGlobalState >
class cugip::AsyncCellularAutomatonWithGlobalState< TGrid, TNeighborhood, TRule, TGlobalState, TSemiGlobalState >
class cugip::AsyncCellularAutomatonWithGlobalStateAndPointer< TGrid, TNeighborhood, TRule, TGlobalState, TSemiGlobalState >
struct cugip::Options
struct cugip::is_callable< PotentiallyCallable, Args >
struct cugip::CellOperation< TNeighborhood, TRule >
struct cugip::CellOperationWithGlobalState< TNeighborhood, TRule, TGlobalState >
struct cugip::Grid< TElement, tDim >
class cugip::CellularAutomatonBaseCRTP< TDerived, TRule, TState, tBufferCount >
class cugip::CellularAutomaton< TGrid, TNeighborhood, TRule >
class cugip::CellularAutomatonWithGlobalState< TGrid, TNeighborhood, TRule, TGlobalState >
struct cugip::DummyGlobalState
struct cugip::DeviceFlagMixin< TBaseClass >
struct cugip::ConwayRule
struct cugip::ConnectedComponentLabelingRule
struct cugip::EquivalenceGlobalState
struct cugip::LocalMinimaEquivalenceGlobalState< TId >
struct cugip::ConnectedComponentLabelingRule2
struct cugip::LocalMinimaConnectedComponentRule
struct cugip::WatershedRule
struct cugip::WatershedSteepestDescentRuleBase
struct cugip::WatershedSteepestDescentRule
struct cugip::WatershedSteepestDescentGlobalStateRule
struct cugip::Watershed2RuleBase
struct cugip::Watershed2Rule
struct cugip::Watershed2GlobalStateRule
struct cugip::Watershed3Rule
struct cugip::ReactionDiffusionRule
struct cugip::FillFlag
class cugip::simple_vector< TCoordinateType, tDim >
struct cugip::static_vector_traits< TVector >
struct cugip::static_vector_traits< simple_vector< TValue, tDimension > >
Macros
#define M_SQRT3 1.73205080756887729352744634151
Typedefs
typedef DeviceFlagMixin< DummyGlobalState > cugip::ConvergenceFlag
typedef LocalMinimaEquivalenceGlobalState< int > cugip::Watershed2EquivalenceGlobalState
Functions
template<typename TInView , typename TOutView , typename TRule , typename TPolicy , typename TSemiGlobalState >
CUGIP_GLOBAL void cugip::kernel_hidden_updates (TInView aInView, TOutView aOutView, TRule aRule, TPolicy aPolicy)
template<typename TInView , typename TOutView , typename TRule , typename TSemiGlobalState >
void cugip::hidden_updates (TInView aInView, TOutView aOutView, TRule aRule, cudaStream_t aCudaStream=0)
CUGIP_DECL_HYBRID simple_vector< float, 3 > cugip::eigen_values (const symmetric_tensor< float, 3 > &aTensor)
template<int tCol1, int tCol2>
CUGIP_DECL_HYBRID simple_vector< float, 3 > cugip::eigen_vector (float aEigenValue, const symmetric_tensor< float, 3 > &aMatrix, const float aThreshold)
CUGIP_DECL_HYBRID matrix< float, 3, 3 > cugip::eigen_vectors (const symmetric_tensor< float, 3 > &aTensor, const simple_vector< float, 3 > &aEigenValues)
CUGIP_DECL_HYBRID symmetric_tensor< float, 3 > cugip::matrix_from_eigen_vectors_and_values (const matrix< float, 3, 3 > &aEigenVectors, const simple_vector< float, 3 > &aEigenValues)
template<typename TType >
CUGIP_DECL_HYBRID constexpr TType cugip::zero ()
template<>
constexpr int cugip::zero< int > ()
template<>
constexpr float cugip::zero< float > ()
template<typename TCoordType1 , typename TCoordType2 , int tDim>
CUGIP_DECL_HYBRID simple_vector< typename std::common_type< TCoordType1, TCoordType2 >::type, tDim > cugip::operator+ (const simple_vector< TCoordType1, tDim > &aArg1, const simple_vector< TCoordType2, tDim > &aArg2)
template<typename TFactor , typename TVector >
CUGIP_DECL_HYBRID std::enable_if< static_vector_traits< TVector >::is_vector, simple_vector< decltype(std::declval< TFactor >)*std::declval< TVector >)[0]), static_vector_traits< TVector >::dimension > >::type cugip::operator* (const TFactor &aFactor, const TVector &aArg)
template<typename TFactor , typename TVector >
CUGIP_DECL_HYBRID std::enable_if< static_vector_traits< TVector >::is_vector, simple_vector< decltype(std::declval< TFactor >)*std::declval< TVector >)[0]), static_vector_traits< TVector >::dimension > >::type cugip::operator* (const TVector &aArg, const TFactor &aFactor)
template<typename TCoordType1 , typename TCoordType2 , int tDim>
CUGIP_DECL_HYBRID simple_vector< typename std::common_type< TCoordType1, TCoordType2 >::type, tDim > cugip::operator- (const simple_vector< TCoordType1, tDim > &aArg1, const simple_vector< TCoordType2, tDim > &aArg2)
template<typename TCoordType1 , typename TCoordType2 , int tDim>
CUGIP_DECL_HYBRID bool cugip::operator== (const simple_vector< TCoordType1, tDim > &aArg1, const simple_vector< TCoordType2, tDim > &aArg2)
template<typename TCoordType1 , typename TCoordType2 , int tDim>
CUGIP_DECL_HYBRID bool cugip::operator!= (const simple_vector< TCoordType1, tDim > &aArg1, const simple_vector< TCoordType2, tDim > &aArg2)
template<typename TCoordType1 , typename TCoordType2 , int tDim>
CUGIP_DECL_HYBRID bool cugip::less (const simple_vector< TCoordType1, tDim > &aA, const simple_vector< TCoordType2, tDim > &aB)
template<typename TCoordType1 , typename TCoordType2 , int tDim>
CUGIP_DECL_HYBRID bool cugip::operator< (const simple_vector< TCoordType1, tDim > &aA, const simple_vector< TCoordType2, tDim > &aB)
template<typename TCoordType1 , typename TCoordType2 , int tDim>
CUGIP_DECL_HYBRID bool cugip::operator<= (const simple_vector< TCoordType1, tDim > &aA, const simple_vector< TCoordType2, tDim > &aB)
template<typename TCoordType1 , typename TCoordType2 , int tDim>
CUGIP_DECL_HYBRID bool cugip::operator>= (const simple_vector< TCoordType1, tDim > &aA, const simple_vector< TCoordType2, tDim > &aB)
template<typename TCoordType1 , typename TCoordType2 , int tDim>
CUGIP_DECL_HYBRID simple_vector< typename std::common_type< TCoordType1, TCoordType2 >::type, tDim > cugip::max_coords (const simple_vector< TCoordType1, tDim > &aArg1, const simple_vector< TCoordType2, tDim > &aArg2)
template<typename TCoordType1 , typename TCoordType2 , int tDim>
CUGIP_DECL_HYBRID simple_vector< typename std::common_type< TCoordType1, TCoordType2 >::type, tDim > cugip::min_coords (const simple_vector< TCoordType1, tDim > &aArg1, const simple_vector< TCoordType2, tDim > &aArg2)
template<typename TType , int tDim>
CUGIP_DECL_HOST std::ostream & cugip::operator<< (std::ostream &stream, const simple_vector< TType, tDim > &v)
template<typename TVector1 , typename TVector2 >
CUGIP_DECL_HYBRID std::enable_if< static_vector_traits< TVector1 >::is_vector &&static_vector_traits< TVector2 >::is_vector, decltype(std::declval< TVector1 >)[0]*std::declval< TVector2 >)[0])>::type cugip::dot (const TVector1 &aVector1, const TVector2 &aVector2)
template<typename TType >
CUGIP_DECL_HYBRID std::enable_if< std::is_fundamental< TType >::value, TType >::type cugip::dot (const TType &aValue1, const TType &aValue2)
template<typename TCoordType , int tDim>
CUGIP_DECL_HYBRID simple_vector< TCoordType, tDim > cugip::product (simple_vector< TCoordType, tDim > aVector1, const simple_vector< TCoordType, tDim > &aVector2)
template<typename TVector1 , typename TVector2 >
CUGIP_DECL_HYBRID std::enable_if< static_vector_traits< TVector1 >::is_vector &&static_vector_traits< TVector2 >::is_vector, simple_vector< decltype(std::declval< TVector1 >)[0]*std::declval< TVector2 >)[0]), 3 > >::type cugip::cross (const TVector1 &aVector1, const TVector2 &aVector2)
template<typename TType >
CUGIP_DECL_HYBRID auto cugip::squared_magnitude (const TType &aVector) -> decltype(dot(aVector, aVector))
template<typename TType >
CUGIP_DECL_HYBRID TType::coord_t cugip::magnitude (const TType &aVector)
template<typename TType >
CUGIP_DECL_HYBRID TType cugip::normalize (const TType &aVector)
template<typename TCoordType , int tDim>
CUGIP_DECL_HYBRID TCoordType cugip::multiply (const simple_vector< TCoordType, tDim > &aVector)
Detailed Description
Mathematical structures and operations
Macro Definition Documentation
#define M_SQRT3 1.73205080756887729352744634151
Todo:
handle constants properly
Definition at line 14 of file eigen.hpp.
Referenced by cugip::eigen_values().
Typedef Documentation
typedef DeviceFlagMixin<DummyGlobalState> cugip::ConvergenceFlag
Definition at line 64 of file global_state.hpp.
typedef LocalMinimaEquivalenceGlobalState<int> cugip::Watershed2EquivalenceGlobalState
Definition at line 286 of file rules.hpp.
Function Documentation
template<typename TVector1 , typename TVector2 > CUGIP_DECL_HYBRID std::enable_if< static_vector_traits<TVector1>::is_vector && static_vector_traits<TVector2>::is_vector, simple_vector<decltype(std::declval<TVector1>)[0] * std::declval<TVector2>)[0]), 3> >::type cugip::cross (const TVector1 & aVector1, const TVector2 & aVector2) inline
Definition at line 427 of file math.hpp.
References CUGIP_DECL_HYBRID.
Referenced by cugip::eigen_vector(), and cugip::eigen_vectors().
template<typename TVector1 , typename TVector2 > CUGIP_DECL_HYBRID std::enable_if< static_vector_traits<TVector1>::is_vector && static_vector_traits<TVector2>::is_vector, decltype(std::declval<TVector1>)[0] * std::declval<TVector2>)[0])>::type cugip::dot (const TVector1 & aVector1, const TVector2 & aVector2) inline
Todo:
optimize
Definition at line 380 of file math.hpp.
References CUGIP_DECL_HYBRID.
Referenced by cugip::matrix_from_eigen_vectors_and_values(), cugip::sobel_weighted_divergence< tDimension >::operator()(), cugip::host_image_view< TElement, tDim >::operator[](), cugip::device_image_view< TElement, tDim >::operator[](), cugip::const_host_image_view< TElement, tDim >::operator[](), cugip::const_device_image_view< TElement, tDim >::operator[](), cugip::squared_magnitude(), cugip::device_image_view< TElement, tDim >::subview(), and cugip::const_device_image_view< TElement, tDim >::subview().
template<typename TType > CUGIP_DECL_HYBRID std::enable_if<std::is_fundamental<TType>::value, TType>::type cugip::dot (const TType & aValue1, const TType & aValue2)
Definition at line 393 of file math.hpp.
References CUGIP_DECL_HYBRID.
CUGIP_DECL_HYBRID simple_vector<float, 3> cugip::eigen_values (const symmetric_tensor< float, 3 > & aTensor)
Definition at line 17 of file eigen.hpp.
References CUGIP_DECL_HYBRID, M_SQRT3, cugip::matrix_trace(), and cugip::sqr().
Referenced by cugip::compute_diffusion_tensor_ftor::operator()().
template<int tCol1, int tCol2> CUGIP_DECL_HYBRID simple_vector<float, 3> cugip::eigen_vector (float aEigenValue, const symmetric_tensor< float, 3 > & aMatrix, const float aThreshold)
Definition at line 60 of file eigen.hpp.
References cugip::symmetric_tensor< TType, tDimension >::column(), cugip::cross(), CUGIP_DECL_HYBRID, EPSILON, cugip::sqr(), and cugip::squared_magnitude().
CUGIP_DECL_HYBRID matrix<float, 3, 3> cugip::eigen_vectors (const symmetric_tensor< float, 3 > & aTensor, const simple_vector< float, 3 > & aEigenValues)
Based on implementation for paper: 'Efficient numerical diagonalization of hermitian 3x3 matrices' by Joachim Kopp
Definition at line 100 of file eigen.hpp.
References cugip::abs(), cugip::matrix< TType, tRowCount, tColCount >::column(), cugip::cross(), CUGIP_DECL_HYBRID, EPSILON, cugip::find_orthonormal(), cugip::max(), cugip::sqr(), and cugip::squared_magnitude().
Referenced by cugip::compute_diffusion_tensor_ftor::operator()().
template<typename TInView , typename TOutView , typename TRule , typename TSemiGlobalState > void cugip::hidden_updates (TInView aInView, TOutView aOutView, TRule aRule, cudaStream_t aCudaStream = 0)
Todo:
do this only in code processed by nvcc
Definition at line 111 of file async_cellular_automata.hpp.
Referenced by cugip::AsyncCellularAutomatonWithGlobalState< TGrid, TNeighborhood, TRule, TGlobalState, TSemiGlobalState >::computeNextIteration(), and cugip::AsyncCellularAutomatonWithGlobalStateAndPointer< TGrid, TNeighborhood, TRule, TGlobalState, TSemiGlobalState >::computeNextIteration().
template<typename TInView , typename TOutView , typename TRule , typename TPolicy , typename TSemiGlobalState > CUGIP_GLOBAL void cugip::kernel_hidden_updates (TInView aInView, TOutView aOutView, TRule aRule, TPolicy aPolicy)
Definition at line 61 of file async_cellular_automata.hpp.
References cugip::makeDeviceImageView(), and cugip::to_vector().
template<typename TCoordType1 , typename TCoordType2 , int tDim> CUGIP_DECL_HYBRID bool cugip::less (const simple_vector< TCoordType1, tDim > & aA, const simple_vector< TCoordType2, tDim > & aB) inline
Definition at line 304 of file math.hpp.
References CUGIP_DECL_HYBRID, and cugip::simple_vector< TCoordinateType, tDim >::mValues.
Referenced by cugip::operator<().
template<typename TType > CUGIP_DECL_HYBRID TType::coord_t cugip::magnitude (const TType & aVector) inline
Definition at line 449 of file math.hpp.
References CUGIP_DECL_HYBRID, and cugip::squared_magnitude().
Referenced by cugip::normalize(), cugip::gradient_magnitude_symmetric_difference< TInputType, TOutputType >::operator()(), and cugip::sobel_gradient_magnitude< tDimension >::operator()().
CUGIP_DECL_HYBRID symmetric_tensor<float, 3> cugip::matrix_from_eigen_vectors_and_values (const matrix< float, 3, 3 > & aEigenVectors, const simple_vector< float, 3 > & aEigenValues)
Definition at line 139 of file eigen.hpp.
References cugip::dot(), cugip::symmetric_tensor< TType, tDimension >::get(), cugip::product(), and cugip::matrix< TType, tRowCount, tColCount >::row().
Referenced by cugip::compute_diffusion_tensor_ftor::operator()().
template<typename TCoordType1 , typename TCoordType2 , int tDim> CUGIP_DECL_HYBRID simple_vector<typename std::common_type<TCoordType1, TCoordType2>::type, tDim> cugip::max_coords (const simple_vector< TCoordType1, tDim > & aArg1, const simple_vector< TCoordType2, tDim > & aArg2) inline
Definition at line 344 of file math.hpp.
References CUGIP_DECL_HYBRID, and cugip::simple_vector< TCoordinateType, tDim >::mValues.
template<typename TCoordType1 , typename TCoordType2 , int tDim> CUGIP_DECL_HYBRID simple_vector<typename std::common_type<TCoordType1, TCoordType2>::type, tDim> cugip::min_coords (const simple_vector< TCoordType1, tDim > & aArg1, const simple_vector< TCoordType2, tDim > & aArg2) inline
Definition at line 355 of file math.hpp.
References CUGIP_DECL_HOST, and cugip::simple_vector< TCoordinateType, tDim >::mValues.
template<typename TCoordType , int tDim> CUGIP_DECL_HYBRID TCoordType cugip::multiply (const simple_vector< TCoordType, tDim > & aVector) inline
Definition at line 463 of file math.hpp.
template<typename TType > CUGIP_DECL_HYBRID TType cugip::normalize (const TType & aVector) inline
Definition at line 456 of file math.hpp.
References CUGIP_DECL_HYBRID, and cugip::magnitude().
template<typename TCoordType1 , typename TCoordType2 , int tDim> CUGIP_DECL_HYBRID bool cugip::operator!= (const simple_vector< TCoordType1, tDim > & aArg1, const simple_vector< TCoordType2, tDim > & aArg2) inline
Definition at line 297 of file math.hpp.
References CUGIP_DECL_HYBRID.
template<typename TFactor , typename TVector > CUGIP_DECL_HYBRID std::enable_if< static_vector_traits<TVector>::is_vector, simple_vector< decltype(std::declval<TFactor>) * std::declval<TVector>)[0]), static_vector_traits<TVector>::dimension> >::type cugip::operator* (const TFactor & aFactor, const TVector & aArg) inline
Definition at line 242 of file math.hpp.
References CUGIP_DECL_HYBRID.
template<typename TFactor , typename TVector > CUGIP_DECL_HYBRID std::enable_if< static_vector_traits<TVector>::is_vector, simple_vector< decltype(std::declval<TFactor>) * std::declval<TVector>)[0]), static_vector_traits<TVector>::dimension> >::type cugip::operator* (const TVector & aArg, const TFactor & aFactor) inline
Definition at line 259 of file math.hpp.
References CUGIP_DECL_HYBRID, and cugip::operator*().
template<typename TCoordType1 , typename TCoordType2 , int tDim> CUGIP_DECL_HYBRID simple_vector<typename std::common_type<TCoordType1, TCoordType2>::type, tDim> cugip::operator+ (const simple_vector< TCoordType1, tDim > & aArg1, const simple_vector< TCoordType2, tDim > & aArg2) inline
Definition at line 229 of file math.hpp.
References CUGIP_DECL_HYBRID.
template<typename TCoordType1 , typename TCoordType2 , int tDim> CUGIP_DECL_HYBRID simple_vector<typename std::common_type<TCoordType1, TCoordType2>::type, tDim> cugip::operator- (const simple_vector< TCoordType1, tDim > & aArg1, const simple_vector< TCoordType2, tDim > & aArg2) inline
Definition at line 277 of file math.hpp.
References CUGIP_DECL_HYBRID.
template<typename TCoordType1 , typename TCoordType2 , int tDim> CUGIP_DECL_HYBRID bool cugip::operator< (const simple_vector< TCoordType1, tDim > & aA, const simple_vector< TCoordType2, tDim > & aB) inline
Definition at line 317 of file math.hpp.
References CUGIP_DECL_HYBRID, and cugip::less().
template<typename TType , int tDim> CUGIP_DECL_HOST std::ostream& cugip::operator<< (std::ostream & stream, const simple_vector< TType, tDim > & v) inline
Definition at line 366 of file math.hpp.
References CUGIP_DECL_HYBRID.
template<typename TCoordType1 , typename TCoordType2 , int tDim> CUGIP_DECL_HYBRID bool cugip::operator<= (const simple_vector< TCoordType1, tDim > & aA, const simple_vector< TCoordType2, tDim > & aB) inline
Definition at line 324 of file math.hpp.
References CUGIP_DECL_HYBRID.
template<typename TCoordType1 , typename TCoordType2 , int tDim> CUGIP_DECL_HYBRID bool cugip::operator== (const simple_vector< TCoordType1, tDim > & aArg1, const simple_vector< TCoordType2, tDim > & aArg2) inline
Definition at line 285 of file math.hpp.
References CUGIP_DECL_HYBRID, and cugip::simple_vector< TCoordinateType, tDim >::mValues.
template<typename TCoordType1 , typename TCoordType2 , int tDim> CUGIP_DECL_HYBRID bool cugip::operator>= (const simple_vector< TCoordType1, tDim > & aA, const simple_vector< TCoordType2, tDim > & aB) inline
Definition at line 337 of file math.hpp.
References CUGIP_DECL_HYBRID.
template<typename TCoordType , int tDim> CUGIP_DECL_HYBRID simple_vector<TCoordType, tDim> cugip::product (simple_vector< TCoordType, tDim > aVector1, const simple_vector< TCoordType, tDim > & aVector2) inline
Todo:
optimize
Definition at line 400 of file math.hpp.
References CUGIP_DECL_HYBRID.
template<typename TType > CUGIP_DECL_HYBRID auto cugip::squared_magnitude (const TType & aVector) -> decltype(dot(aVector, aVector)) inline
Definition at line 442 of file math.hpp.
References CUGIP_DECL_HYBRID, and cugip::dot().
Referenced by cugip::eigen_vector(), cugip::eigen_vectors(), and cugip::magnitude().
template<typename TType > CUGIP_DECL_HYBRID constexpr TType cugip::zero ()
Definition at line 18 of file math.hpp.
template<> constexpr float cugip::zero< float > () inline
Definition at line 30 of file math.hpp.
template<> constexpr int cugip::zero< int > () inline
Definition at line 24 of file math.hpp.