CUGIP: Views
Views
Classes
class cugip::subimage_view< TView, tIsDeviceView >
Wrapper limiting access to the wrapped view.
class cugip::bordered_subimage_view< TView, tIsDeviceView >
class cugip::subimage_view< TView, false >
class cugip::bordered_subimage_view< TView, false >
class cugip::slice_image_view< TView, tSliceDimension, tIsDeviceView >
class cugip::slice_image_view< TView, tSliceDimension, false >
Functions
cugip::CUGIP_DECLARE_VIEW_TRAITS ((subimage_view< TView, tIsDeviceView >), dimension< TView >::value, tIsDeviceView,(!tIsDeviceView), typename TView, bool tIsDeviceView)
cugip::CUGIP_DECLARE_VIEW_TRAITS ((bordered_subimage_view< TView, tIsDeviceView >), dimension< TView >::value, tIsDeviceView,(!tIsDeviceView), typename TView, bool tIsDeviceView)
template<typename TView , bool tIsDeviceView>
CUGIP_HD_WARNING_DISABLE CUGIP_DECL_HYBRID region< dimension< TView >::value > cugip::valid_region (const bordered_subimage_view< TView, tIsDeviceView > &view)
template<typename TView >
auto cugip::subview (const TView &view, const simple_vector< int, dimension< TView >::value > &corner, const simple_vector< int, dimension< TView >::value > &size) -> typename detail::SubviewGenerator< TView, is_memory_based< TView >::value >::ResultView
template<typename TView >
auto cugip::bordered_subview (const TView &view, const simple_vector< int, dimension< TView >::value > &corner, const simple_vector< int, dimension< TView >::value > &size) -> bordered_subimage_view< TView, is_device_view< TView >::value >
template<int tSliceDimension, typename TView >
auto cugip::slice (const TView &view, int slice) -> typename detail::SliceGenerator< TView, tSliceDimension, is_memory_based< TView >::value >::ResultView
Detailed Description
Function Documentation
template<typename TView > auto cugip::bordered_subview (const TView & view, const simple_vector< int, dimension< TView >::value > & corner, const simple_vector< int, dimension< TView >::value > & size) -> bordered_subimage_view<TView, is_device_view<TView>::value>
Creates view for part of the original image view (device or host). In behavior same as the normal subview, but read access to elements outside its domain is valid, as long as it is valid in the original image view.
Parameters
view Original image view.
corner Index of view corner (zero coordinates in new view)
size Size of the subview
Definition at line 307 of file subview.hpp.
References CUGIP_THROW, and cugip::view().
cugip::CUGIP_DECLARE_VIEW_TRAITS ((subimage_view< TView, tIsDeviceView >) , dimension< TView >::value , tIsDeviceView , (!tIsDeviceView) , typename TView , bool tIsDeviceView)
Referenced by cugip::MultiplicationImageView< TView1, TView2 >::operator[](), and cugip::DivisionImageView< TView1, TView2 >::operator[]().
cugip::CUGIP_DECLARE_VIEW_TRAITS ((bordered_subimage_view< TView, tIsDeviceView >) , dimension< TView >::value , tIsDeviceView , (!tIsDeviceView) , typename TView , bool tIsDeviceView)
template<int tSliceDimension, typename TView > auto cugip::slice (const TView & view, int slice) -> typename detail::SliceGenerator<TView, tSliceDimension, is_memory_based<TView>::value>::ResultView
Creates slice view (view of smaller dimension).
Template Parameters
tSliceDimension Which axis is perpendicular to the cut
Todo:
(johny) - generic slicing
Definition at line 330 of file subview.hpp.
References CUGIP_ASSERT, CUGIP_THROW, and cugip::view().
template<typename TView > auto cugip::subview (const TView & view, const simple_vector< int, dimension< TView >::value > & corner, const simple_vector< int, dimension< TView >::value > & size) -> typename detail::SubviewGenerator<TView, is_memory_based<TView>::value>::ResultView
Creates view for part of the original image view (device or host). When the original view is not memory based it returns view wrapper.
Parameters
view Original image view.
corner Index of view corner (zero coordinates in new view)
size Size of the subview
Definition at line 282 of file subview.hpp.
References CUGIP_THROW, and cugip::view().
template<typename TView , bool tIsDeviceView> CUGIP_HD_WARNING_DISABLE CUGIP_DECL_HYBRID region<dimension<TView>::value> cugip::valid_region (const bordered_subimage_view< TView, tIsDeviceView > & view)
Definition at line 161 of file subview.hpp.
References cugip::region< tDimension >::corner, and cugip::valid_region().