CUGIP: Meta_algorithm
Meta_algorithm
Classes
struct cugip::DefaultForEachPolicy< TView >
struct cugip::DefaultTransformLocatorPolicy< TView1, TView2 >
struct cugip::PreloadingTransformLocatorPolicy< TView, tRadius >
Functions
template<int tDimension, typename TFunctor >
TFunctor cugip::for_each (region< tDimension > aRegion, TFunctor aOperator)
template<typename TView , typename TFunctor >
void cugip::for_each (TView aView, TFunctor aOperator, cudaStream_t aCudaStream=0)
template<typename TView , typename TFunctor , typename TPolicy >
void cugip::for_each (TView aView, TFunctor aOperator, TPolicy aPolicy, cudaStream_t aCudaStream=0)
template<typename TView , typename TFunctor >
void cugip::for_each_position (TView aView, TFunctor aOperator, cudaStream_t aCudaStream=0)
template<typename TView , typename TFunctor , typename TPolicy >
void cugip::for_each_position (TView aView, TFunctor aOperator, TPolicy aPolicy, cudaStream_t aCudaStream=0)
template<typename TView , typename TOutputValue , typename TOperator >
TOutputValue cugip::reduce (TView view, TOutputValue initial_value, TOperator reduction_operator)
template<typename TView , class = typename std::enable_if<is_image_view<TView>::value>::type>
TView::value_type cugip::min (TView view)
template<typename TView , class = typename std::enable_if<is_image_view<TView>::value>::type>
TView::value_type cugip::max (TView view)
template<typename TView , typename TOutputValue , class = typename std::enable_if<is_image_view<TView>::value>::type>
TOutputValue cugip::sum (TView view, TOutputValue initial_value)
template<typename TView , class = typename std::enable_if<is_image_view<TView>::value>::type>
TView::value_type cugip::sum (TView view)
template<typename TView1 , typename TView2 , typename TOutputValue , class = typename std::enable_if<is_image_view<TView1>::value && is_image_view<TView2>::value>::type>
TOutputValue cugip::sum_differences (TView1 view1, TView2 view2, TOutputValue initial_value)
template<typename TInputView , typename TOutputView , typename TOperator >
void cugip::scan (TInputView aInput, TOutputView aOutput, TOutputView aTmpView, TOperator aOperator)
template<typename TInView , typename TOutView , typename TFunctor , typename TPolicy >
void cugip::transform (TInView aInView, TOutView aOutView, TFunctor aOperator, TPolicy aPolicy, cudaStream_t aCudaStream=0)
template<typename TInView , typename TOutView , typename TFunctor >
void cugip::transform (TInView aInView, TOutView aOutView, TFunctor aOperator, cudaStream_t aCudaStream=0)
template<typename TInView1 , typename TInView2 , typename TOutView , typename TFunctor , typename TPolicy >
void cugip::transform2 (TInView1 aInView1, TInView2 aInView2, TOutView aOutView, TFunctor aOperator, TPolicy aPolicy, cudaStream_t aCudaStream=0)
template<typename TInView1 , typename TInView2 , typename TOutView , typename TFunctor >
void cugip::transform2 (TInView1 aInView1, TInView2 aInView2, TOutView aOutView, TFunctor aOperator, cudaStream_t aCudaStream=0)
template<typename TInView , typename TOutView , typename TFunctor , typename TPolicy >
void cugip::transform_position (TInView aInView, TOutView aOutView, TFunctor aOperator, TPolicy aPolicy, cudaStream_t aCudaStream=0)
template<typename TInView , typename TOutView , typename TFunctor >
void cugip::transform_position (TInView aInView, TOutView aOutView, TFunctor aOperator, cudaStream_t aCudaStream=0)
template<typename TInView , typename TOutView , typename TOperator >
void cugip::transform_locator (TInView aInView, TOutView aOutView, TOperator aOperator, cudaStream_t aCudaStream=0)
template<typename TInView , typename TOutView , typename TOperator , typename TPolicy >
void cugip::transform_locator (TInView aInView, TOutView aOutView, TOperator aOperator, TPolicy aPolicy, cudaStream_t aCudaStream=0)
template<typename TInView , typename TOutView , typename TOperator , typename TAssignOperation >
void cugip::transform_locator_assign (TInView aInView, TOutView aOutView, TOperator aOperator, TAssignOperation aAssignOperation, cudaStream_t aCudaStream=0)
template<typename TInView , typename TOutView , typename TOperator , typename TAssignOperation , typename TPolicy >
void cugip::transform_locator_assign (TInView aInView, TOutView aOutView, TOperator aOperator, TAssignOperation aAssignOperation, TPolicy aPolicy, cudaStream_t aCudaStream=0)
template<typename TInView , typename TOutView , typename TFunctor >
void cugip::filter (TInView aInView, TOutView aOutView, TFunctor aOperator)
Detailed Description
Generic algorithms
Function Documentation
template<typename TInView , typename TOutView , typename TFunctor > void cugip::filter (TInView aInView, TOutView aOutView, TFunctor aOperator)
Definition at line 33 of file filter.hpp.
References D_PRINT.
Referenced by cugip::local_minima_detection(), and cugip::watershed_transformation1().
template<int tDimension, typename TFunctor > TFunctor cugip::for_each (region< tDimension > aRegion, TFunctor aOperator)
Definition at line 38 of file for_each.hpp.
Referenced by cugip::add(), cugip::compute_diffusion_tensor(), cugip::init_watershed_buffers(), cugip::multiply(), cugip::EquivalenceGlobalState::postprocess(), and cugip::LocalMinimaEquivalenceGlobalState< TId >::postprocess().
template<typename TView , typename TFunctor > void cugip::for_each (TView aView, TFunctor aOperator, cudaStream_t aCudaStream = 0)
Definition at line 61 of file for_each.hpp.
References cugip::isEmpty().
template<typename TView , typename TFunctor , typename TPolicy > void cugip::for_each (TView aView, TFunctor aOperator, TPolicy aPolicy, cudaStream_t aCudaStream = 0)
Definition at line 74 of file for_each.hpp.
References cugip::isEmpty().
template<typename TView , typename TFunctor > void cugip::for_each_position (TView aView, TFunctor aOperator, cudaStream_t aCudaStream = 0)
Definition at line 87 of file for_each.hpp.
References cugip::isEmpty().
Referenced by cugip::init_watershed_from_plateaus_labels(), and cugip::init_watershed_labels().
template<typename TView , typename TFunctor , typename TPolicy > void cugip::for_each_position (TView aView, TFunctor aOperator, TPolicy aPolicy, cudaStream_t aCudaStream = 0)
Definition at line 100 of file for_each.hpp.
References CUGIP_GLOBAL, D_PRINT, and cugip::isEmpty().
template<typename TView , class = typename std::enable_if<is_image_view<TView>::value>::type> TView::value_type cugip::max (TView view)
template<typename TView , class = typename std::enable_if<is_image_view<TView>::value>::type> TView::value_type cugip::min (TView view)
template<typename TView , typename TOutputValue , typename TOperator > TOutputValue cugip::reduce (TView view, TOutputValue initial_value, TOperator reduction_operator)
Implements parallel reduction - application of associative operator on all image elements. For example to sum all values in integer image:
sum = reduce(view, 0, thrust::plus<int>());
Parameters
view Processed image view - only constant element access needed.
initial_value Value used for result initialization (0 for sums, 1 for products, etc.)
reduction_operator Associative operator - it must be callable on device like this: result = reduction_operator(val1, val2).
Returns
Result of the operation.
Referenced by cugip::MinCut< TGraphData, TPolicy, TTraceObject >::computeFlowThroughSinkFrontier().
template<typename TInputView , typename TOutputView , typename TOperator > void cugip::scan (TInputView aInput, TOutputView aOutput, TOutputView aTmpView, TOperator aOperator)
Definition at line 226 of file scan.hpp.
template<typename TView , typename TOutputValue , class = typename std::enable_if<is_image_view<TView>::value>::type> TOutputValue cugip::sum (TView view, TOutputValue initial_value)
template<typename TView , class = typename std::enable_if<is_image_view<TView>::value>::type> TView::value_type cugip::sum (TView view)
WARNING: as a result type is used element type of the passed view, so be aware of possible overflow if summing large view of small type elements (int8_t, int16_t, ...) When in doubt use Sum(view, initial_value); and pass initial value of bigger type to prevent overflows.
template<typename TView1 , typename TView2 , typename TOutputValue , class = typename std::enable_if<is_image_view<TView1>::value && is_image_view<TView2>::value>::type> TOutputValue cugip::sum_differences (TView1 view1, TView2 view2, TOutputValue initial_value)
template<typename TInView , typename TOutView , typename TFunctor , typename TPolicy > void cugip::transform (TInView aInView, TOutView aOutView, TFunctor aOperator, TPolicy aPolicy, cudaStream_t aCudaStream = 0)
Definition at line 76 of file transform.hpp.
References CUGIP_ASSERT, and cugip::isEmpty().
Referenced by cugip::compute_structural_tensor(), cugip::Graph< TFlow >::fill_segments(), cugip::threshold_masking(), and cugip::transform().
template<typename TInView , typename TOutView , typename TFunctor > void cugip::transform (TInView aInView, TOutView aOutView, TFunctor aOperator, cudaStream_t aCudaStream = 0)
Definition at line 92 of file transform.hpp.
References cugip::transform().
template<typename TInView1 , typename TInView2 , typename TOutView , typename TFunctor , typename TPolicy > void cugip::transform2 (TInView1 aInView1, TInView2 aInView2, TOutView aOutView, TFunctor aOperator, TPolicy aPolicy, cudaStream_t aCudaStream = 0)
Definition at line 99 of file transform.hpp.
References CUGIP_ASSERT, and cugip::isEmpty().
Referenced by cugip::apply_diffusion_tensor(), and cugip::transform2().
template<typename TInView1 , typename TInView2 , typename TOutView , typename TFunctor > void cugip::transform2 (TInView1 aInView1, TInView2 aInView2, TOutView aOutView, TFunctor aOperator, cudaStream_t aCudaStream = 0)
Definition at line 117 of file transform.hpp.
References cugip::transform2().
template<typename TInView , typename TOutView , typename TOperator > void cugip::transform_locator (TInView aInView, TOutView aOutView, TOperator aOperator, cudaStream_t aCudaStream = 0)
Definition at line 202 of file transform.hpp.
References CUGIP_ASSERT, and cugip::isEmpty().
Referenced by cugip::compute_gradient(), cugip::CellularAutomaton< TGrid, TNeighborhood, TRule >::computeNextIteration(), cugip::CellularAutomatonWithGlobalState< TGrid, TNeighborhood, TRule, TGlobalState >::computeNextIteration(), and cugip::convolution().
template<typename TInView , typename TOutView , typename TOperator , typename TPolicy > void cugip::transform_locator (TInView aInView, TOutView aOutView, TOperator aOperator, TPolicy aPolicy, cudaStream_t aCudaStream = 0)
Definition at line 219 of file transform.hpp.
References CUGIP_ASSERT, and cugip::isEmpty().
template<typename TInView , typename TOutView , typename TOperator , typename TAssignOperation > void cugip::transform_locator_assign (TInView aInView, TOutView aOutView, TOperator aOperator, TAssignOperation aAssignOperation, cudaStream_t aCudaStream = 0)
Definition at line 236 of file transform.hpp.
References CUGIP_ASSERT, and cugip::isEmpty().
Referenced by cugip::apply_diffusion_tensor().
template<typename TInView , typename TOutView , typename TOperator , typename TAssignOperation , typename TPolicy > void cugip::transform_locator_assign (TInView aInView, TOutView aOutView, TOperator aOperator, TAssignOperation aAssignOperation, TPolicy aPolicy, cudaStream_t aCudaStream = 0)
Definition at line 253 of file transform.hpp.
References CUGIP_ASSERT, and cugip::isEmpty().
template<typename TInView , typename TOutView , typename TFunctor , typename TPolicy > void cugip::transform_position (TInView aInView, TOutView aOutView, TFunctor aOperator, TPolicy aPolicy, cudaStream_t aCudaStream = 0)
Definition at line 124 of file transform.hpp.
References CUGIP_ASSERT, and cugip::isEmpty().
Referenced by cugip::assign_masked_ids(), and cugip::transform_position().
template<typename TInView , typename TOutView , typename TFunctor > void cugip::transform_position (TInView aInView, TOutView aOutView, TFunctor aOperator, cudaStream_t aCudaStream = 0)
Definition at line 140 of file transform.hpp.
References cugip::transform_position().