CUGIP: cugip Namespace Reference
cugip Namespace Reference
Classes
struct AbsFunctor
class AccessDimensionImageView
struct AddValueFunctor
class AggregatingTimerSet
struct apply_diffusion_tensor_ftor
struct assign_color_ftor
struct assign_masked_id_functor
struct AsyncCellOperationWithGlobalState
class AsyncCellularAutomatonWithGlobalState
class AsyncCellularAutomatonWithGlobalStateAndPointer
class BinaryOperatorDeviceImageView
Base class for image views implementing lazy evaluation of operators working on two image views.
struct BlockedAccessIndex
class bordered_subimage_view
class bordered_subimage_view< TView, false >
struct BorderHandlingTraits
struct BorderHandlingTraits< border_handling_enum::MIRROR >
struct BorderHandlingTraits< border_handling_enum::REPEAT >
struct BorderHandlingTraits< border_handling_enum::ZERO >
struct CellOperation
struct CellOperationWithGlobalState
class CellularAutomaton
class CellularAutomatonBaseCRTP
class CellularAutomatonWithGlobalState
struct ChannelSumFunctor
class CheckerBoardImageView
Procedural image view, which generates checker board like image.
struct Choose
struct Choose< 0, H, T... >
struct Choose< N, H, T... >
struct clear_nonminima_plateaus_ftor
class coherence_enhancing_diffusion
class column_accessor
struct compute_diffusion_tensor_ftor
struct compute_structural_tensor_ftor
struct ConnectedComponentLabelingRule
struct ConnectedComponentLabelingRule2
class const_device_image_view
struct const_device_memory_1d
struct const_device_memory_2d
struct const_device_memory_3d
struct const_device_ptr
class const_host_image_view
struct const_host_memory_1d
struct const_host_memory_2d
struct const_host_memory_3d
class const_memory_view
class ConstantDeviceImageView
Procedural image view, which returns same value for all indices.
struct convert_float_and_byte
struct convolution_kernel
struct convolution_kernel< TType, StaticSize< tSize > >
struct convolution_operator
struct ConwayRule
struct CopyDirectionTag
struct DefaultForEachPolicy
struct DefaultTransformLocatorPolicy
struct DefaultTransformPolicy
struct device_base_ptr
struct device_flag
struct device_flag_view
class device_image
class device_image_view
class device_image_view_base
class device_image_view_crtp
struct device_linear_access_view
struct device_memory_1d
struct device_memory_1d_owner
struct device_memory_2d
struct device_memory_2d_owner
struct device_memory_3d
struct device_memory_3d_owner
struct device_ptr
class device_union_find
class device_union_find_view
struct DeviceFlagMixin
struct dim_traits
struct dim_traits< 1 >
struct dimension
struct dimension< const_memory_view< TElement, tDim > >
struct dimension< device_image< TElement, tDim > >
struct dimension< device_image_view_base< tDim > >
struct dimension< element< TType, tDim > >
struct dimension< host_image< TElement, tDim > >
struct dimension< image_locator< TImageView, TBorderHandling > >
struct dimension< intraits_1d< tWidth > >
struct dimension< intraits_2d< tWidth, tHeight > >
struct dimension< intraits_3d< tWidth, tHeight, tDepth > >
struct dimension< memory_view< TElement, tDim > >
struct dimension< simple_vector< TCoordinateType, tDim > >
struct dimension< texture_image< TElement, tDim > >
struct dimension_1d_tag
struct dimension_2d_tag
struct dimension_3d_tag
struct dimension_4d_tag
struct dimension_helper
struct dimension_helper< 1 >
struct dimension_helper< 2 >
struct dimension_helper< 3 >
struct dimension_helper< 4 >
struct divergence
class DivisionImageView
struct DummyGlobalState
struct DummyTraceObject
struct DurationRecord
struct EdgeForwardTraversable
struct EdgeRecord
struct EdgeResidualsRecord
struct EdgeReverseTraversable
struct element
struct EquivalenceGlobalState
class EquivalenceManager
class ExceptionBase
struct FillFlag
struct FillStaticSize
struct FillStaticSize< 2, tValue >
struct FillStaticSize< 3, tValue >
struct fold_and
struct fold_and< TBoolTrait, THead >
struct generate_basins_ftor
struct generate_spiral_ftor
struct GenerateIntSequence
struct get_neighborhood_accessor
struct get_policy
struct get_policy2
struct get_policy2< tIdx1, tIdx2, const matrix< TType, tRowCount, tColCount > >
struct get_policy2< tIdx1, tIdx2, const symmetric_tensor< TType, tDimension > >
struct get_policy2< tIdx1, tIdx2, matrix< TType, tRowCount, tColCount > >
struct get_policy2< tIdx1, tIdx2, symmetric_tensor< TType, tDimension > >
struct get_policy< tIdx, const simple_vector< TType, tChannelCount > >
struct get_policy< tIdx, const Tuple< TType... > >
struct get_policy< tIdx, simple_vector< TType, tChannelCount > >
struct get_policy< tIdx, Tuple< TType... > >
struct GetChannel
struct GetCopyDirection
struct GetCopyDirection< false, true, true, false >
struct GetCopyDirection< tFromIsDevice, true, false, true >
struct GetCopyDirection< true, false, false, true >
struct GetCopyDirection< true, tFromIsHost, true, false >
struct GetPositionInIntSequence
struct gradient_magnitude
struct gradient_magnitude_symmetric_difference
struct gradient_symmetric_difference
class Graph
struct GraphCutData
struct GraphCutPolicy
struct GraphData
struct grayscale_ftor
struct Grid
struct HandlePlateauBorder
struct HasSmallerNeighbor
class host_image
class host_image_view
class host_image_view_base
struct host_linear_access_view
struct host_memory_1d
struct host_memory_2d
struct host_memory_3d
struct Id
class image_locator
class IncompatibleViewSizes
struct init_watershed_labels_from_plateaus_ftor
struct init_watershed_labels_ftor
struct init_wsheds_ftor
class IntervalMeasurement
struct intraits_1d
struct intraits_2d
struct intraits_3d
class IntSequence
struct IntValue
struct is_callable
struct is_device_view
struct is_host_view
struct is_image_view
struct is_memory_based
struct is_memory_based< const_device_image_view< TElement, tDim > >
struct is_memory_based< const_host_image_view< TElement, tDim > >
struct is_memory_based< device_image_view< TElement, tDim > >
struct is_memory_based< host_image_view< TElement, tDim > >
struct is_memory_view
struct is_memory_view< const_memory_view< TElement, tDim > >
struct is_memory_view< memory_view< TElement, tDim > >
struct IsValueInIntSequence
struct LastItemInIntSequence
struct LinearAccessIndex
class LinearCombinationImageView
struct local_minima_detection_ftor
struct LocalMinimaConnectedComponentRule
struct LocalMinimaEquivalenceGlobalState
struct LocalMinimumLabel
struct LowerLimitFunctor
struct LowerLimitReplacementFunctor
struct mandelbrot_ftor
class MaskedImageView
class matrix
struct MaxFunctor
struct memory_management
struct memory_management< TElement, 1 >
struct memory_management< TElement, 2 >
struct memory_management< TElement, 3 >
class memory_view
class MeshGridView
struct MinCut
struct MinFunctor
class MinimalGraphCutComputation
class MirrorImageView
struct MooreNeighborhood
struct MooreNeighborhood< 2 >
struct MooreNeighborhood< 3 >
class MultiIntervalMeasurement
class MultiplicationImageView
struct MultiplyByFactorFunctor
struct MultiViewTraits
struct NaiveSweepPass
struct NaiveSweepPass2
struct NaiveWorkDistribution
class NAryOperatorDeviceImageView
struct negate
struct neighborhood_4
struct neighborhood_4_tag
class neighborhood_accessor
struct NeighborhoodAccessor
struct nl_means_parameters
struct Options
class PaddedImageView
class ParallelQueue
class ParallelQueueView
struct PreloadingTransformLocatorPolicy
struct ProductOfIntSequence
struct Push
struct PushPolicy
struct Range
struct Range< L, I, Sizes< N... > >
struct Range< L, L, Sizes< N... > >
struct ReactionDiffusionRule
struct region
struct Relabel
struct RelabelPolicy
struct scan_image_for_wshed_path_ftor
struct separable_convolution_operator
struct SetMask
class simple_vector
struct Sizes
class slice_image_view
class slice_image_view< TView, tSliceDimension, false >
struct sobel_gradient
struct sobel_gradient_magnitude
struct sobel_weighted_divergence
struct SquareFunctor
Usable in device/host code.
struct SquareRootFunctor
Usable in device/host code.
struct static_matrix_traits
struct static_matrix_traits< matrix< TType, tRowCount, tColCount > >
struct static_matrix_traits< symmetric_tensor< TType, tDimension > >
struct static_memory_block
struct static_vector_traits
struct static_vector_traits< column_accessor< TMatrix > >
struct static_vector_traits< simple_vector< TValue, tDimension > >
struct StaticSize
struct step1_ftor
class subimage_view
Wrapper limiting access to the wrapped view.
class subimage_view< TView, false >
struct SumValuesFunctor
struct SweepPass
class symmetric_tensor
class texture_image
class texture_view
struct thresholding_ftor
struct Tile
struct TileProcessor
struct transform_update_add
struct transform_update_assign
struct Tuple
class TupleElem
class TupleImpl
class TupleImpl< Sizes< N... >, T... >
class UnaryOperatorImageView
class UnaryOperatorOnLocatorImageView
class UnaryOperatorOnPositionImageView
class UniqueIdDeviceImageView
struct UpperLimitFunctor
struct UpperLimitReplacementFunctor
struct VonNeumannNeighborhood
struct VonNeumannNeighborhood< 2 >
struct VonNeumannNeighborhood< 3 >
struct Watershed2GlobalStateRule
struct Watershed2Rule
struct Watershed2RuleBase
struct Watershed3Rule
struct WatershedRule
struct WatershedSteepestDescentGlobalStateRule
struct WatershedSteepestDescentRule
struct WatershedSteepestDescentRuleBase
struct WorkDistribution
struct WorkLimits
struct ZipValues
Typedefs
typedef unsigned NodeId
typedef unsigned long CombinedNodeId
typedef DeviceFlagMixin< DummyGlobalState > ConvergenceFlag
typedef LocalMinimaEquivalenceGlobalState< int > Watershed2EquivalenceGlobalState
typedef CopyDirectionTag< true, true > DeviceToDeviceTag
typedef CopyDirectionTag< true, false > DeviceToHostTag
typedef CopyDirectionTag< false, false > HostToHostTag
typedef CopyDirectionTag< false, true > HostToDeviceTag
typedef element< unsigned char, 3 > element_rgb8_t
typedef unsigned char element_gray8_t
typedef char element_gray8s_t
typedef element< signed char, 2 > element_channel2_8s_t
typedef boost::error_info< struct tag_message, std::string > MessageErrorInfo
typedef boost::error_info< struct tag_filename, boost::filesystem::path > FilenameErrorInfo
Error info containing file path.
typedef simple_vector< float, 2 > intervalf_t
typedef simple_vector< double, 2 > intervald_t
typedef simple_vector< float, 2 > vect2f_t
typedef simple_vector< float, 3 > vect3f_t
typedef simple_vector< int, 2 > vect2i_t
typedef simple_vector< int, 3 > vect3i_t
typedef simple_vector< int, 2 > size2_t
typedef simple_vector< int, 3 > size3_t
typedef simple_vector< int, 2 > Int2
typedef simple_vector< int, 3 > Int3
typedef simple_vector< float, 2 > Float2
typedef simple_vector< float, 3 > Float3
template<int tSize>
using MakeIntSequence = typename GenerateIntSequence< tSize >::Type
template<typename T >
using type_of = typename T::type
template<size_t N, typename... T>
using choose = type_of< Choose< N, T... >>
template<size_t L>
using range = type_of< Range< L >>
Enumerations
enum { CONNECTION_VERTEX = 1 << 31, CONNECTION_INDEX_MASK = ~CONNECTION_VERTEX }
enum RelabelImplementation { RelabelImplementation::Default, RelabelImplementation::Naive, RelabelImplementation::OptimizedNaive }
enum PreflowInitialization { PreflowInitialization::Default, PreflowInitialization::Push }
enum TLinkType : int { TLinkType::Source = 0, TLinkType::Sink = 1 }
enum border_handling_enum {
border_handling_enum::NONE, border_handling_enum::MIRROR, border_handling_enum::REPEAT, border_handling_enum::PERIODIC,
border_handling_enum::ZERO
}
Functions
CUGIP_DECL_HYBRID Int2 stridesFromSize (Int2 size)
CUGIP_DECL_HYBRID Int3 stridesFromSize (Int3 size)
CUGIP_DECL_HYBRID int stridesFromSize (int size)
template<int tDimension>
CUGIP_HD_WARNING_DISABLE CUGIP_DECL_HYBRID simple_vector< int, tDimension > index_from_linear_access_index (const simple_vector< int, tDimension > &aExtents, int aIdx)
template<typename TImageView >
CUGIP_HD_WARNING_DISABLE CUGIP_DECL_HYBRID auto index_from_linear_access_index (const TImageView &aView, int aIdx) -> typename TImageView::coord_t
template<typename TImageView >
CUGIP_HD_WARNING_DISABLE CUGIP_DECL_HYBRID auto linear_access (const TImageView &aView, int aIdx) -> typename TImageView::accessed_type
template<typename TExtents , typename TCoordinates >
CUGIP_DECL_HYBRID int64_t linear_index_from_strides (TExtents aStrides, TCoordinates aCoordinates)
template<typename TExtents , typename TCoordinates >
CUGIP_DECL_HYBRID int get_linear_access_index (TExtents aExtents, TCoordinates aCoordinates)
template<typename TImageView >
host_linear_access_view< TImageView > linear_access_view (TImageView aView)
uint64_t splitBy3 (unsigned int a)
template<typename TExtents , typename TCoordinates >
CUGIP_DECL_HYBRID int get_zorder_access_index (TExtents aExtents, TCoordinates aCoordinates)
template<int tBlockSize, typename TExtents , typename TCoordinates >
CUGIP_DECL_HYBRID int get_blocked_order_access_index (TExtents aExtents, TCoordinates aCoordinates)
template<typename TInView , typename TGradientView >
void compute_gradient (TInView aInput, TGradientView aGradient)
template<typename TGradientView , typename TTensorView >
void compute_structural_tensor (TGradientView aGradient, TTensorView aStructuralTensor)
template<typename TInputTensorView , typename TOutputTensorView , typename TTmpTensorView >
void blur_structural_tensor (TInputTensorView aStructuralTensor, TOutputTensorView aBluredStructuralTensor, TTmpTensorView aTmpTensorView)
template<typename TTensorView >
void compute_diffusion_tensor (TTensorView aDiffusionTensor, float aAlpha, float aContrast)
template<typename TTensorView , typename TGradientView , typename TOutputView >
void apply_diffusion_tensor (TTensorView aDiffusionTensor, TGradientView aGradient, TOutputView aOutput, float aTimeStep)
template<typename TInView , typename TGradientView , typename TOutView , typename TTensorView >
void coherence_enhancing_diffusion_step (TInView aInput, TOutView aOutput, TGradientView aGradient, TTensorView aStructuralTensor, TTensorView aDiffusionTensor, TTensorView aTmpTensor, float aTimeStep, float aAlpha, float aContrast)
__device__ __inline__ int32_t ld_gbl_cg (const int32_t *addr)
__device__ __inline__ double ld_gbl_cg (const double *addr)
template<typename TFlow , typename TFunctor >
CUGIP_GLOBAL void forEachVertexKernel (GraphCutData< TFlow > aGraph, TFunctor aFunctor)
template<typename TFlow , typename TFunctor >
void for_each_vertex (GraphCutData< TFlow > &aGraph, TFunctor aFunctor)
template<typename TFlow >
void assignLabelByDistance (GraphCutData< TFlow > &aGraphData, ParallelQueueView< int > aVertices)
template<typename TFlow >
CUGIP_GLOBAL void maxFlowIterationsKernel (GraphCutData< TFlow > aGraph, ParallelQueueView< int > aVertices)
template<typename TFlow >
CUGIP_GLOBAL void initResidualsKernel (TFlow *aWeightsForward, TFlow *aWeightsBackward, EdgeResidualsRecord< TFlow > *aResiduals, int aSize)
template<typename TGraph , typename TGraphCutData >
void graphCutDataFromGraph (TGraph &aGraph, TGraphCutData &aGraphData)
template<typename TFlow >
CUGIP_GLOBAL void pushThroughTLinksFromSourceKernel (GraphCutData< TFlow > aGraph)
template<typename TFlow >
CUGIP_GLOBAL void pushThroughTLinksToSinkKernel (GraphCutData< TFlow > aGraph)
template<typename TFlow >
CUGIP_DECL_DEVICE TFlow tryPull (GraphCutData< TFlow > &aGraph, int aFrom, int aTo, TFlow aCapacity)
template<typename TFlow >
CUGIP_DECL_DEVICE bool tryPullPush (GraphCutData< TFlow > &aGraph, int aFrom, int aTo, int aConnectionIndex, bool aConnectionSide)
template<typename TFlow >
CUGIP_DECL_DEVICE void pushImplementation (GraphCutData< TFlow > &aGraph, ParallelQueueView< int > &aVertices, int index, int aCurrentLevel, device_flag_view &aPushSuccessfulFlag)
template<typename TGraph , typename TPolicy >
CUGIP_GLOBAL void pushKernel (TGraph aGraph, ParallelQueueView< int > aVertices, int aLevelStart, int aLevelEnd, int aCurrentLevel, device_flag_view aPushSuccessfulFlag)
template<typename TGraph , typename TPolicy >
CUGIP_GLOBAL void pushKernelMultiLevel (TGraph aGraph, ParallelQueueView< int > aVertices, int *aLevelStarts, int aLevelCount, int aCurrentLevel, device_ptr< int > aLastProcessedLevel, device_flag_view aPushSuccessfulFlag)
template<typename TGraph , typename TPolicy >
CUGIP_GLOBAL void pushKernelMultiLevelGlobalSync (TGraph aGraph, ParallelQueueView< int > aVertices, int *aLevelStarts, int aLevelCount, int aCurrentLevel, device_ptr< int > aLastProcessedLevel, device_flag_view aPushSuccessfulFlag, cub::GridBarrier barrier)
template<typename TGraph >
CUGIP_GLOBAL void pushKernel2 (TGraph aGraph, ParallelQueueView< int > aVertices, int *aLevelStarts, int aLevelCount, device_flag_view aPushSuccessfulFlag)
template<typename TGraph , typename TPolicy >
CUGIP_GLOBAL void initBFSKernel (ParallelQueueView< int > aVertices, TGraph aGraph)
template<typename TGraph , typename TPolicy >
CUGIP_DECL_DEVICE void propagateFromVertex (int vertex, ParallelQueueView< int > &aVertices, TGraph &aGraph, int aCurrentLevel, const TPolicy &aPolicy)
template<typename TGraph , typename TPolicy >
CUGIP_DECL_DEVICE void propagateFromVertex2 (int vertex, const int *aStartEnd, ParallelQueueView< int > &aVertices, TGraph &aGraph, int aCurrentLevel, const TPolicy &aPolicy)
template<typename TGraph >
CUGIP_DECL_DEVICE void printTile (const Tile< TGraph > &aTile)
CUGIP_DECL_DEVICE void printWorkLimits (const WorkLimits &aLimits)
template<typename TGraph , typename TSweepOperator , typename TWorkDistribution >
CUGIP_GLOBAL void bfsPropagationSingleIterationKernel (ParallelQueueView< int > aVertices, TWorkDistribution aWorkDistribution, TGraph aGraph, int aCurrentLevel, TSweepOperator aSweepOperator)
template<typename TGraph , typename TSweepOperator , typename TWorkDistribution >
CUGIP_GLOBAL void bfsPropagationSingleIterationKernel2 (ParallelQueueView< int > aVertices, TWorkDistribution aWorkDistribution, TGraph aGraph, int aCurrentLevel, TSweepOperator aSweepOperator)
template<typename TGraph , typename TSweepOperator , typename TWorkDistribution , typename TPolicy >
CUGIP_GLOBAL void bfsPropagationMultiIterationKernel (ParallelQueueView< int > aVertices, int aStart, int aCount, ParallelQueueView< int > aLevelStarts, TGraph aGraph, int aCurrentLevel, TSweepOperator aSweepOperator)
template<typename TGraph , typename TSweepOperator , typename TWorkDistribution , typename TPolicy >
CUGIP_GLOBAL void bfsPropagationMultiIterationGlobalSyncKernel (ParallelQueueView< int > aVertices, int aStart, int aCount, ParallelQueueView< int > aLevelStarts, TGraph aGraph, int aCurrentLevel, TSweepOperator aSweepOperator, cub::GridBarrier barrier)
template<typename TGraphData , typename TPolicy >
CUGIP_GLOBAL void relabel_compute_dynamic (TGraphData aGraph, ParallelQueueView< int > aVertexQueue, ParallelQueueView< int > aLevelStarts, TPolicy aPolicy)
template<typename TInImageView , typename TOutImageView , typename TParameters >
void nonlocal_means (TInImageView aIn, TOutImageView aOut, TParameters aParameters)
template<typename TArg1View , typename TArg21View , typename TWeight >
void add (TArg1View aArg1View, TWeight aWeight, TArg21View aArg2View)
template<typename TArg1View , typename TArg21View >
void subtract (TArg1View aArg1View, TArg21View aArg2View)
template<typename TView , typename TType >
void multiply (TView aView, TType aFactor)
template<typename TImageView , typename TLUTBufferView >
void connected_component_labeling (TImageView aImageView, TLUTBufferView aLUT)
template<typename TInImageView , typename TOutImageView >
void assign_masked_ids (TInImageView aInput, TOutImageView aOutput)
template<int tDimension>
convolution_kernel< simple_vector< float, tDimension >, typename FillStaticSize< tDimension, 3 >::Type > sobel_gradient_kernel ()
template<int tRadius>
convolution_kernel< float, StaticSize< 2 *tRadius+1 > > gaussian_kernel ()
template<typename TLocator , typename TKernel , typename TResult >
CUGIP_DECL_HYBRID void apply_convolution_kernel (TLocator aLocator, TKernel aKernel, TResult &aResult)
template<typename TInputView , typename TOutputView , typename TKernel >
void convolution (TInputView aInView, TOutputView aOutView, TKernel aKernel)
template<typename TInputView , typename TOutputView , typename TTmpView , typename TKernel >
void separable_convolution (TInputView aInView, TOutputView aOutView, TTmpView aTmpView, TKernel aKernel)
template<typename TInView , typename TOutView >
void local_minima (TInView aInView, TOutView aOutView)
template<typename TImageView , typename TIdImageView , typename TUnionFind >
void clear_nonminima_plateaus (TImageView aImageView, TIdImageView aIdImageView, TUnionFind aUnionFind)
template<typename TImageView , typename TIdImageView , typename TUnionFind >
void local_minima_detection (TImageView aImageView, TIdImageView aIdImageView, TUnionFind aUnionFind)
template<typename TInView , typename TOutView >
void threshold_masking (TInView aInView, TOutView aOutView, typename TInView::value_type aThreshold, typename TOutView::value_type aMaskValue, typename TOutView::value_type aNonMaskValue=0)
template<typename TImageView , typename TIdImageView >
void step1 (TImageView aImageView, TIdImageView aIdImageView)
template<typename TImageView , typename TIdImageView >
void step2 (TImageView aImageView, TIdImageView aIdImageView)
template<typename TImageView , typename TIdImageView >
void step3 (TImageView aImageView, TIdImageView aIdImageView)
template<typename TImageView , typename TIdImageView >
void step4 (TImageView aImageView, TIdImageView aIdImageView)
template<typename TImageView , typename TIdImageView >
void watershed_transformation (TImageView aImageView, TIdImageView aIdImageView, TIdImageView aTmpIdImageView)
template<typename TIdImageView , typename TDistanceView >
void init_watershed_buffers (TIdImageView aIdImageView, TDistanceView aDistanceView)
template<typename TImageView , typename TIdImageView , typename TDistanceView >
CUGIP_GLOBAL void watershed_evolution_kernel (TImageView aImageView, TIdImageView aIdImageView, TIdImageView aTmpIdImageView, TDistanceView aDistanceView1, TDistanceView aDistanceView2, device_flag_view aUpdateFlag)
template<typename TImageView , typename TIdImageView , typename TDistanceView >
void watershed_evolution (TImageView aImageView, TIdImageView aIdImageView, TIdImageView aTmpIdImageView, TDistanceView aDistanceView1, TDistanceView aDistanceView2, device_flag_view aUpdateFlag)
template<typename TImageView , typename TIdImageView , typename TDistanceView >
void watershed_transformation2 (TImageView aImageView, TIdImageView aIdImageView, TIdImageView aTmpIdImageView, TDistanceView aDistanceView1, TDistanceView aDistanceView2)
template<typename TIdImageView , typename TUnionFind >
void init_watershed_labels (TIdImageView aIdImageView, TUnionFind aUnionFind)
template<typename TIdImageView , typename TUnionFind >
void init_watershed_from_plateaus_labels (TIdImageView aIdImageView, TUnionFind aUnionFind)
template<typename TImageView , typename TIdImageView , typename TUnionFind >
void scan_image_for_wshed_path (TImageView aImageView, TIdImageView aIdImageView, TUnionFind aUnionFind, device_flag_view aUpdatedFlag)
template<typename TImageView , typename TIdImageView , typename TUnionFind >
void watershed_transformation1 (TImageView aImageView, TIdImageView aIdImageView, TUnionFind aUnionFind)
template<typename TInView , typename TOutView , typename TRule , typename TPolicy , typename TSemiGlobalState >
CUGIP_GLOBAL void kernel_hidden_updates (TInView aInView, TOutView aOutView, TRule aRule, TPolicy aPolicy)
template<typename TInView , typename TOutView , typename TRule , typename TSemiGlobalState >
void hidden_updates (TInView aInView, TOutView aOutView, TRule aRule, cudaStream_t aCudaStream=0)
template<typename TFromView , typename TToView >
void copyAsync (TFromView from_view, TToView to_view, cudaStream_t cuda_stream=0)
template<typename TFromView , typename TToView >
void copy (TFromView from_view, TToView to_view)
template<typename TFromView , typename TToView >
CUGIP_GLOBAL void copyKernel (TFromView from_view, TToView to_view)
template<typename TFromView , typename TToView >
void copyDeviceToDeviceAsync (TFromView from_view, TToView to_view, cudaStream_t cuda_stream)
template<typename TFromView , typename TToView >
void copyHostToHost (TFromView from_view, TToView to_view)
template<typename TFromView , typename TToView >
void copyDeviceToHostAsync (TFromView from_view, TToView to_view, cudaStream_t cuda_stream)
template<typename TFromView , typename TToView >
void copyHostToDeviceAsync (TFromView from_view, TToView to_view, cudaStream_t cuda_stream)
template<typename TFromView , typename TToView >
void asyncCopyHelper (TFromView from_view, TToView to_view, DeviceToDeviceTag, cudaStream_t cuda_stream)
template<typename TFromView , typename TToView >
void asyncCopyHelper (TFromView from_view, TToView to_view, DeviceToHostTag, cudaStream_t cuda_stream)
template<typename TFromView , typename TToView >
void asyncCopyHelper (TFromView from_view, TToView to_view, HostToDeviceTag, cudaStream_t cuda_stream)
template<typename TFromView , typename TToView >
void asyncCopyHelper (TFromView from_view, TToView to_view, HostToHostTag, cudaStream_t cuda_stream)
cudaExtent makeCudaExtent (int bytes, Int2 size)
cudaExtent makeCudaExtent (int bytes, Int3 size)
template<int tDimension>
simple_vector< int, tDimension > pitchedPtrToStrides (int bytes, cudaPitchedPtr pitched_ptr)
template<>
Int2 pitchedPtrToStrides< 2 > (int bytes, cudaPitchedPtr pitched_ptr)
template<>
Int3 pitchedPtrToStrides< 3 > (int bytes, cudaPitchedPtr pitched_ptr)
template<typename TElement >
cudaPitchedPtr stridesToPitchedPtr (TElement *ptr, Int2 size, Int2 strides)
template<typename TElement >
cudaPitchedPtr stridesToPitchedPtr (TElement *ptr, Int3 size, Int3 strides)
template<int tDimension>
CUGIP_DECL_DEVICE cugip::simple_vector< int, tDimension > mapBlockIdxAndThreadIdxToViewCoordinates ()
Get 1 to 1 mapping between cuda threads in grid and view coordinates.
template<>
CUGIP_DECL_DEVICE cugip::simple_vector< int, 2 > mapBlockIdxAndThreadIdxToViewCoordinates< 2 > ()
template<>
CUGIP_DECL_DEVICE cugip::simple_vector< int, 3 > mapBlockIdxAndThreadIdxToViewCoordinates< 3 > ()
template<int tDimension>
CUGIP_DECL_DEVICE cugip::simple_vector< int, tDimension > mapBlockIdxToViewCoordinates ()
template<>
CUGIP_DECL_DEVICE cugip::simple_vector< int, 2 > mapBlockIdxToViewCoordinates< 2 > ()
template<>
CUGIP_DECL_DEVICE cugip::simple_vector< int, 3 > mapBlockIdxToViewCoordinates< 3 > ()
CUGIP_DECL_DEVICE int threadOrderFromIndex ()
CUGIP_DECL_DEVICE int currentBlockSize ()
CUGIP_DECL_DEVICE vect3i_t currentThreadIndex ()
CUGIP_DECL_DEVICE bool is_in_block (int aX, int aY, int aZ)
CUGIP_DECL_DEVICE bool is_in_thread (int aX, int aY, int aZ)
template<int tDimension>
CUGIP_DECL_HYBRID simple_vector< int, tDimension > dim3_to_vector (dim3)
template<>
CUGIP_DECL_HYBRID simple_vector< int, 2 > dim3_to_vector< 2 > (dim3 aValue)
template<>
CUGIP_DECL_HYBRID simple_vector< int, 3 > dim3_to_vector< 3 > (dim3 aValue)
template<typename TView >
CUGIP_HD_WARNING_DISABLE CUGIP_DECL_HYBRID region< dimension< TView >::value > valid_region (const TView &view)
template<typename TView >
CUGIP_HD_WARNING_DISABLE CUGIP_DECL_HYBRID int elementCount (const TView &aView)
template<typename TView >
CUGIP_HD_WARNING_DISABLE CUGIP_DECL_HYBRID bool isEmpty (const TView &aView)
template<int tIdx, typename TType , int tChannelCount>
CUGIP_DECL_HYBRID TType & get (element< TType, tChannelCount > &aArg)
template<int tIdx, typename TType , int tChannelCount>
CUGIP_DECL_HYBRID const TType & get (const element< TType, tChannelCount > &aArg)
template<typename TClassId >
CUGIP_GLOBAL void kernelCompaction (TClassId *aBuffer, int aSize)
template<typename TClassId >
CUGIP_GLOBAL void kernelInitialization (TClassId *aBuffer, int aSize)
template<typename TView , typename TType >
void fill (TView aView, TType aValue)
template<int tDimension, typename TFunctor >
TFunctor for_each (region< tDimension > aRegion, TFunctor aOperator)
template<typename TView , typename TFunctor >
void for_each (TView aView, TFunctor aOperator, cudaStream_t aCudaStream=0)
template<typename TView , typename TFunctor , typename TPolicy >
void for_each (TView aView, TFunctor aOperator, TPolicy aPolicy, cudaStream_t aCudaStream=0)
template<typename TView , typename TFunctor >
void for_each_position (TView aView, TFunctor aOperator, cudaStream_t aCudaStream=0)
template<typename TView , typename TFunctor , typename TPolicy >
void for_each_position (TView aView, TFunctor aOperator, TPolicy aPolicy, cudaStream_t aCudaStream=0)
template<typename TLoc , typename TToView >
void copy (boost::gil::image_view< TLoc > from_view, TToView to_view)
template<typename TImage >
TImage::view_t view (TImage &aImage)
template<typename TImage >
TImage::const_view_t const_view (TImage &aImage)
template<typename TElement , int tDim>
host_image< TElement, tDim >::view_t view (host_image< TElement, tDim > &aImage)
template<typename TElement , int tDim>
host_image< TElement, tDim >::const_view_t const_view (const host_image< TElement, tDim > &aImage)
CUGIP_DECLARE_HOST_VIEW_TRAITS ((host_image_view< TElement, tDim >), tDim, typename TElement, int tDim)
CUGIP_DECLARE_HOST_VIEW_TRAITS ((const_host_image_view< TElement, tDim >), tDim, typename TElement, int tDim)
template<typename TElement , int tDimension>
const_host_image_view< const TElement, tDimension > makeConstHostImageView (const TElement *buffer, simple_vector< int, tDimension > size)
template<typename TElement , int tDimension>
const_host_image_view< const TElement, tDimension > makeConstHostImageView (const TElement *buffer, simple_vector< int, tDimension > size, simple_vector< int, tDimension > strides)
template<typename TElement , int tDimension>
host_image_view< TElement, tDimension > makeHostImageView (TElement *buffer, simple_vector< int, tDimension > size)
template<typename TElement , int tDimension>
host_image_view< TElement, tDimension > makeHostImageView (TElement *buffer, simple_vector< int, tDimension > size, simple_vector< int, tDimension > strides)
CUGIP_DECLARE_DEVICE_VIEW_TRAITS ((device_image_view< TElement, tDim >), tDim, typename TElement, int tDim)
CUGIP_DECLARE_DEVICE_VIEW_TRAITS ((const_device_image_view< TElement, tDim >), tDim, typename TElement, int tDim)
template<typename TElement , int tDimension>
CUGIP_DECL_HYBRID const_device_image_view< const TElement, tDimension > makeConstDeviceImageView (const TElement *buffer, simple_vector< int, tDimension > size)
template<typename TElement , int tDimension>
CUGIP_DECL_HYBRID const_device_image_view< const TElement, tDimension > makeConstDeviceImageView (const TElement *buffer, simple_vector< int, tDimension > size, simple_vector< int, tDimension > strides)
template<typename TElement , int tDimension>
CUGIP_DECL_HYBRID device_image_view< TElement, tDimension > makeDeviceImageView (TElement *buffer, simple_vector< int, tDimension > size)
template<typename TElement , int tDimension>
CUGIP_DECL_HYBRID device_image_view< TElement, tDimension > makeDeviceImageView (TElement *buffer, simple_vector< int, tDimension > size, simple_vector< int, tDimension > strides)
template<typename TElement >
host_image_view< TElement, 3 > view (itk::Image< TElement, 3 > &aImage)
template<typename TElement >
host_image_view< TElement, 2 > view (itk::Image< TElement, 2 > &aImage)
template<typename TElement >
const_host_image_view< const TElement, 3 > const_view (const itk::Image< TElement, 3 > &aImage)
template<typename TElement >
const_host_image_view< const TElement, 2 > const_view (const itk::Image< TElement, 2 > &aImage)
template<typename TImageSize >
cugip::simple_vector< int, 3 > compute_grid_size (const dim3 &aBlockSize, const TImageSize &aImageSize)
template<typename TImageSize >
dim3 compute_grid_size_dim3 (const dim3 &aBlockSize, const TImageSize &aImageSize)
template<typename TCoords >
CUGIP_DECL_DEVICE TCoords corner_coords_from_block_dim ()
template<typename TCoords >
CUGIP_DECL_DEVICE TCoords coords_from_block_dim ()
CUGIP_DECL_HYBRID simple_vector< float, 3 > eigen_values (const symmetric_tensor< float, 3 > &aTensor)
template<int tCol1, int tCol2>
CUGIP_DECL_HYBRID simple_vector< float, 3 > eigen_vector (float aEigenValue, const symmetric_tensor< float, 3 > &aMatrix, const float aThreshold)
CUGIP_DECL_HYBRID matrix< float, 3, 3 > eigen_vectors (const symmetric_tensor< float, 3 > &aTensor, const simple_vector< float, 3 > &aEigenValues)
CUGIP_DECL_HYBRID symmetric_tensor< float, 3 > matrix_from_eigen_vectors_and_values (const matrix< float, 3, 3 > &aEigenVectors, const simple_vector< float, 3 > &aEigenValues)
template<typename TType , int tRowCount>
CUGIP_DECL_HYBRID TType matrix_trace (const matrix< TType, tRowCount, tRowCount > &aMatrix)
template<typename TMatrix1 , typename TMatrix2 >
CUGIP_DECL_HYBRID std::enable_if< static_matrix_traits< TMatrix1 >::is_matrix &&static_matrix_traits< TMatrix2 >::is_matrix, matrix< decltype(std::declval< typename static_matrix_traits< TMatrix1 >::element_type >)*std::declval< typename static_matrix_traits< TMatrix1 >::element_type >)), static_matrix_traits< TMatrix1 >::row_count, static_matrix_traits< TMatrix2 >::col_count > >::type product (const TMatrix1 &aMatrix1, const TMatrix1 &aMatrix2)
template<typename TMatrix , typename TVector >
CUGIP_DECL_HYBRID std::enable_if< static_matrix_traits< TMatrix >::is_matrix &&static_vector_traits< TVector >::is_vector, simple_vector< decltype(std::declval< typename static_matrix_traits< TMatrix >::element_type >)*std::declval< typename static_vector_traits< TVector >::element_type >)), static_matrix_traits< TMatrix >::row_count > >::type product (const TMatrix &aMatrix, const TVector &aVector)
template<typename TType , int tDimension>
CUGIP_DECL_HYBRID TType matrix_trace (const symmetric_tensor< TType, tDimension > &aMatrix)
template<typename TFactor , typename TElement , int tDimension>
CUGIP_DECL_HYBRID symmetric_tensor< decltype(std::declval< TFactor >)*std::declval< TElement >)), tDimension > operator* (const TFactor &aFactor, const symmetric_tensor< TElement, tDimension > &aArg)
template<typename TFactor , typename TElement , int tDimension>
CUGIP_DECL_HYBRID symmetric_tensor< decltype(std::declval< TFactor >)*std::declval< TElement >)), tDimension > operator* (const symmetric_tensor< TElement, tDimension > &aArg, const TFactor &aFactor)
template<typename TType >
CUGIP_DECL_HYBRID constexpr TType zero ()
template<>
constexpr int zero< int > ()
template<>
constexpr float zero< float > ()
template<typename TCoordType1 , typename TCoordType2 , int tDim>
CUGIP_DECL_HYBRID simple_vector< typename std::common_type< TCoordType1, TCoordType2 >::type, tDim > operator+ (const simple_vector< TCoordType1, tDim > &aArg1, const simple_vector< TCoordType2, tDim > &aArg2)
template<typename TFactor , typename TVector >
CUGIP_DECL_HYBRID std::enable_if< static_vector_traits< TVector >::is_vector, simple_vector< decltype(std::declval< TFactor >)*std::declval< TVector >)[0]), static_vector_traits< TVector >::dimension > >::type operator* (const TFactor &aFactor, const TVector &aArg)
template<typename TFactor , typename TVector >
CUGIP_DECL_HYBRID std::enable_if< static_vector_traits< TVector >::is_vector, simple_vector< decltype(std::declval< TFactor >)*std::declval< TVector >)[0]), static_vector_traits< TVector >::dimension > >::type operator* (const TVector &aArg, const TFactor &aFactor)
template<typename TCoordType1 , typename TCoordType2 , int tDim>
CUGIP_DECL_HYBRID simple_vector< typename std::common_type< TCoordType1, TCoordType2 >::type, tDim > operator- (const simple_vector< TCoordType1, tDim > &aArg1, const simple_vector< TCoordType2, tDim > &aArg2)
template<typename TCoordType1 , typename TCoordType2 , int tDim>
CUGIP_DECL_HYBRID bool operator== (const simple_vector< TCoordType1, tDim > &aArg1, const simple_vector< TCoordType2, tDim > &aArg2)
template<typename TCoordType1 , typename TCoordType2 , int tDim>
CUGIP_DECL_HYBRID bool operator!= (const simple_vector< TCoordType1, tDim > &aArg1, const simple_vector< TCoordType2, tDim > &aArg2)
template<typename TCoordType1 , typename TCoordType2 , int tDim>
CUGIP_DECL_HYBRID bool less (const simple_vector< TCoordType1, tDim > &aA, const simple_vector< TCoordType2, tDim > &aB)
template<typename TCoordType1 , typename TCoordType2 , int tDim>
CUGIP_DECL_HYBRID bool operator< (const simple_vector< TCoordType1, tDim > &aA, const simple_vector< TCoordType2, tDim > &aB)
template<typename TCoordType1 , typename TCoordType2 , int tDim>
CUGIP_DECL_HYBRID bool operator<= (const simple_vector< TCoordType1, tDim > &aA, const simple_vector< TCoordType2, tDim > &aB)
template<typename TCoordType1 , typename TCoordType2 , int tDim>
CUGIP_DECL_HYBRID bool operator>= (const simple_vector< TCoordType1, tDim > &aA, const simple_vector< TCoordType2, tDim > &aB)
template<typename TCoordType1 , typename TCoordType2 , int tDim>
CUGIP_DECL_HYBRID simple_vector< typename std::common_type< TCoordType1, TCoordType2 >::type, tDim > max_coords (const simple_vector< TCoordType1, tDim > &aArg1, const simple_vector< TCoordType2, tDim > &aArg2)
template<typename TCoordType1 , typename TCoordType2 , int tDim>
CUGIP_DECL_HYBRID simple_vector< typename std::common_type< TCoordType1, TCoordType2 >::type, tDim > min_coords (const simple_vector< TCoordType1, tDim > &aArg1, const simple_vector< TCoordType2, tDim > &aArg2)
template<typename TType , int tDim>
CUGIP_DECL_HOST std::ostream & operator<< (std::ostream &stream, const simple_vector< TType, tDim > &v)
template<typename TVector1 , typename TVector2 >
CUGIP_DECL_HYBRID std::enable_if< static_vector_traits< TVector1 >::is_vector &&static_vector_traits< TVector2 >::is_vector, decltype(std::declval< TVector1 >)[0]*std::declval< TVector2 >)[0])>::type dot (const TVector1 &aVector1, const TVector2 &aVector2)
template<typename TType >
CUGIP_DECL_HYBRID std::enable_if< std::is_fundamental< TType >::value, TType >::type dot (const TType &aValue1, const TType &aValue2)
template<typename TCoordType , int tDim>
CUGIP_DECL_HYBRID simple_vector< TCoordType, tDim > product (simple_vector< TCoordType, tDim > aVector1, const simple_vector< TCoordType, tDim > &aVector2)
template<typename TVector1 , typename TVector2 >
CUGIP_DECL_HYBRID std::enable_if< static_vector_traits< TVector1 >::is_vector &&static_vector_traits< TVector2 >::is_vector, simple_vector< decltype(std::declval< TVector1 >)[0]*std::declval< TVector2 >)[0]), 3 > >::type cross (const TVector1 &aVector1, const TVector2 &aVector2)
template<typename TType >
CUGIP_DECL_HYBRID auto squared_magnitude (const TType &aVector) -> decltype(dot(aVector, aVector))
template<typename TType >
CUGIP_DECL_HYBRID TType::coord_t magnitude (const TType &aVector)
template<typename TType >
CUGIP_DECL_HYBRID TType normalize (const TType &aVector)
template<typename TCoordType , int tDim>
CUGIP_DECL_HYBRID TCoordType multiply (const simple_vector< TCoordType, tDim > &aVector)
template<typename TType , int tDimension>
CUGIP_DECL_HYBRID simple_vector< TType, tDimension+1 > insert_dimension (const simple_vector< TType, tDimension > &v, TType inserted_coordinate, int dimension)
template<typename TType >
CUGIP_DECL_HYBRID TType sqr (TType aValue)
template<typename TType >
CUGIP_DECL_HYBRID TType abs (TType aValue)
template<typename TType , int tDimension>
CUGIP_DECL_HYBRID simple_vector< TType, tDimension > abs (simple_vector< TType, tDimension > aValue)
template<typename TType >
CUGIP_DECL_HYBRID TType max (TType aValue1, TType aValue2)
template<typename TType , int tDimension>
CUGIP_DECL_HYBRID TType max (simple_vector< TType, tDimension > aValue)
template<typename TType >
CUGIP_DECL_HYBRID TType min (TType aValue1, TType aValue2)
template<typename TType , int tDimension>
CUGIP_DECL_HYBRID TType min (simple_vector< TType, tDimension > aValue)
template<typename TType , int tDimension>
CUGIP_DECL_HYBRID simple_vector< TType, tDimension > min_per_element (simple_vector< TType, tDimension > aVector1, const simple_vector< TType, tDimension > &aVector2)
template<typename TType , int tDimension>
CUGIP_DECL_HYBRID simple_vector< TType, tDimension > max_per_element (simple_vector< TType, tDimension > aVector1, const simple_vector< TType, tDimension > &aVector2)
template<typename TType , int tDimension>
CUGIP_DECL_HYBRID TType sum (const simple_vector< TType, tDimension > &aVector)
template<typename TType , int tDimension>
CUGIP_DECL_HYBRID simple_vector< TType, tDimension > div (const simple_vector< TType, tDimension > &aVector1, TType aValue)
template<typename TType , int tDimension>
CUGIP_DECL_HYBRID simple_vector< TType, tDimension > div (const simple_vector< TType, tDimension > &aVector1, const simple_vector< TType, tDimension > &aVector2)
template<typename TType , int tDimension>
CUGIP_DECL_HYBRID TType product (const simple_vector< TType, tDimension > &aVector)
template<typename TType >
CUGIP_DECL_HYBRID std::enable_if< std::is_fundamental< TType >::value, TType >::type product (const TType &aValue)
template<typename TCoordType , int tDim>
CUGIP_DECL_HYBRID void sort (simple_vector< TCoordType, tDim > &aVector)
template<typename TVector >
CUGIP_DECL_HYBRID std::enable_if< static_vector_traits< TVector >::is_vector, simple_vector< typename static_vector_traits< TVector >::element_type, 3 > >::type find_orthonormal (const TVector &aVector)
template<typename TType >
std::ostream & operator<< (std::ostream &s, const device_base_ptr< TType > &aPtr)
template<typename TType >
device_memory_1d< TType > view (const device_memory_1d_owner< TType > &aBuffer)
template<typename TCallable >
CUGIP_HD_WARNING_DISABLE CUGIP_DECL_HYBRID void for_each_neighbor (simple_vector< int, 2 > aRadius, TCallable aCallable)
template<typename TCallable >
CUGIP_HD_WARNING_DISABLE CUGIP_DECL_HYBRID void for_each_neighbor (simple_vector< int, 3 > aRadius, TCallable aCallable)
template<typename TCallable >
CUGIP_HD_WARNING_DISABLE CUGIP_DECL_HYBRID void for_each_neighbor (simple_vector< int, 2 > aFrom, simple_vector< int, 2 > aTo, TCallable aCallable)
template<typename TCallable >
CUGIP_HD_WARNING_DISABLE CUGIP_DECL_HYBRID void for_each_neighbor (simple_vector< int, 3 > aFrom, simple_vector< int, 3 > aTo, TCallable aCallable)
template<int tRadius, typename TCallable >
CUGIP_HD_WARNING_DISABLE CUGIP_DECL_DEVICE void for_each_in_radius (TCallable aCallable)
template<int tRadius, typename TCallable >
CUGIP_HD_WARNING_DISABLE CUGIP_DECL_DEVICE void for_each_in_radius2 (TCallable aCallable)
CUGIP_DECLARE_HYBRID_VIEW_TRAITS ((ConstantDeviceImageView< TElement, tDim >), tDim, typename TElement, int tDim)
template<typename TElement , int tDimension>
ConstantDeviceImageView< TElement, tDimension > constantImage (TElement value, simple_vector< int, tDimension > size)
Utility function to create ConstantDeviceImageView without the need to specify template parameters.
CUGIP_DECLARE_HYBRID_VIEW_TRAITS ((CheckerBoardImageView< TElement, tDim >), tDim, typename TElement, int tDim)
template<typename TElement , int tDimension>
CheckerBoardImageView< TElement, tDimension > checkerBoard (TElement white, TElement black, const simple_vector< int, tDimension > &tile_size, const simple_vector< int, tDimension > &size)
Utility function to create CheckerBoardImageView without the need to specify template parameters.
CUGIP_DECLARE_HYBRID_VIEW_TRAITS ((UniqueIdDeviceImageView< tDimension, TId >), tDimension, int tDimension, typename TId)
CUGIP_DECLARE_HYBRID_VIEW_TRAITS ((MeshGridView< tDimension >), tDimension, int tDimension)
template<int tDimension>
std::array< MeshGridView< tDimension >, tDimension > meshGrid (simple_vector< int, tDimension > from, simple_vector< int, tDimension > to)
template<typename TView , typename TOutputValue , typename TOperator >
TOutputValue reduce (TView view, TOutputValue initial_value, TOperator reduction_operator)
template<typename TView , class = typename std::enable_if<is_image_view<TView>::value>::type>
TView::value_type min (TView view)
template<typename TView , class = typename std::enable_if<is_image_view<TView>::value>::type>
TView::value_type max (TView view)
template<typename TView , typename TOutputValue , class = typename std::enable_if<is_image_view<TView>::value>::type>
TOutputValue sum (TView view, TOutputValue initial_value)
template<typename TView , class = typename std::enable_if<is_image_view<TView>::value>::type>
TView::value_type sum (TView view)
template<typename TView1 , typename TView2 , typename TOutputValue , class = typename std::enable_if<is_image_view<TView1>::value && is_image_view<TView2>::value>::type>
TOutputValue sum_differences (TView1 view1, TView2 view2, TOutputValue initial_value)
template<int tDimension>
CUGIP_DECL_HYBRID bool isInsideRegion (const simple_vector< int, tDimension > &aSize, const simple_vector< int, tDimension > &aCoords)
template<int tDimension>
CUGIP_DECL_HYBRID bool isInsideRegion (const region< tDimension > &aRegion, const simple_vector< int, tDimension > &aCoords)
template<int tDimension>
CUGIP_HD_WARNING_DISABLE CUGIP_DECL_HYBRID auto region_linear_access (const region< tDimension > &aRegion, int aIdx) -> simple_vector< int, tDimension >
template<typename TInputView , typename TOutputView , typename TOperator >
void scan (TInputView aInput, TOutputView aOutput, TOutputView aTmpView, TOperator aOperator)
template<typename... TArgs>
void ignoreReturnValues (TArgs...)
template<int... tValues>
std::ostream & operator<< (std::ostream &stream, const IntSequence< tValues... > &)
template<int... tSize>
CUGIP_DECL_HYBRID simple_vector< int, sizeof...(tSize)> to_vector (IntSequence< tSize... >)
CUGIP_DECLARE_VIEW_TRAITS ((subimage_view< TView, tIsDeviceView >), dimension< TView >::value, tIsDeviceView,(!tIsDeviceView), typename TView, bool tIsDeviceView)
CUGIP_DECLARE_VIEW_TRAITS ((bordered_subimage_view< TView, tIsDeviceView >), dimension< TView >::value, tIsDeviceView,(!tIsDeviceView), typename TView, bool tIsDeviceView)
template<typename TView , bool tIsDeviceView>
CUGIP_HD_WARNING_DISABLE CUGIP_DECL_HYBRID region< dimension< TView >::value > valid_region (const bordered_subimage_view< TView, tIsDeviceView > &view)
template<typename TView >
auto subview (const TView &view, const simple_vector< int, dimension< TView >::value > &corner, const simple_vector< int, dimension< TView >::value > &size) -> typename detail::SubviewGenerator< TView, is_memory_based< TView >::value >::ResultView
template<typename TView >
auto bordered_subview (const TView &view, const simple_vector< int, dimension< TView >::value > &corner, const simple_vector< int, dimension< TView >::value > &size) -> bordered_subimage_view< TView, is_device_view< TView >::value >
template<int tSliceDimension, typename TView >
auto slice (const TView &view, int slice) -> typename detail::SliceGenerator< TView, tSliceDimension, is_memory_based< TView >::value >::ResultView
CUGIP_DECLARE_DEVICE_VIEW_TRAITS ((texture_view< TElement, tDim >), tDim, typename TElement, int tDim)
template<typename TElement , int tDim>
texture_image< TElement, tDim >::view_t view (texture_image< TElement, tDim > &aImage)
template<typename TElement , int tDim>
texture_image< TElement, tDim >::view_t const_view (const texture_image< TElement, tDim > &aImage)
template<typename TInView , typename TOutView , typename TFunctor , typename TPolicy >
void transform (TInView aInView, TOutView aOutView, TFunctor aOperator, TPolicy aPolicy, cudaStream_t aCudaStream=0)
template<typename TInView , typename TOutView , typename TFunctor >
void transform (TInView aInView, TOutView aOutView, TFunctor aOperator, cudaStream_t aCudaStream=0)
template<typename TInView1 , typename TInView2 , typename TOutView , typename TFunctor , typename TPolicy >
void transform2 (TInView1 aInView1, TInView2 aInView2, TOutView aOutView, TFunctor aOperator, TPolicy aPolicy, cudaStream_t aCudaStream=0)
template<typename TInView1 , typename TInView2 , typename TOutView , typename TFunctor >
void transform2 (TInView1 aInView1, TInView2 aInView2, TOutView aOutView, TFunctor aOperator, cudaStream_t aCudaStream=0)
template<typename TInView , typename TOutView , typename TFunctor , typename TPolicy >
void transform_position (TInView aInView, TOutView aOutView, TFunctor aOperator, TPolicy aPolicy, cudaStream_t aCudaStream=0)
template<typename TInView , typename TOutView , typename TFunctor >
void transform_position (TInView aInView, TOutView aOutView, TFunctor aOperator, cudaStream_t aCudaStream=0)
template<typename TInView , typename TOutView , typename TOperator >
void transform_locator (TInView aInView, TOutView aOutView, TOperator aOperator, cudaStream_t aCudaStream=0)
template<typename TInView , typename TOutView , typename TOperator , typename TPolicy >
void transform_locator (TInView aInView, TOutView aOutView, TOperator aOperator, TPolicy aPolicy, cudaStream_t aCudaStream=0)
template<typename TInView , typename TOutView , typename TOperator , typename TAssignOperation >
void transform_locator_assign (TInView aInView, TOutView aOutView, TOperator aOperator, TAssignOperation aAssignOperation, cudaStream_t aCudaStream=0)
template<typename TInView , typename TOutView , typename TOperator , typename TAssignOperation , typename TPolicy >
void transform_locator_assign (TInView aInView, TOutView aOutView, TOperator aOperator, TAssignOperation aAssignOperation, TPolicy aPolicy, cudaStream_t aCudaStream=0)
template<int tIdx, typename TType >
CUGIP_DECL_HYBRID get_policy< tIdx, typename std::remove_reference< TType >::type >::return_type get (TType &aArg)
template<int tIdx1, int tIdx2, typename TType >
CUGIP_DECL_HYBRID float get (TType &aArg)
CUGIP_DECLARE_VIEW_TRAITS ((LinearCombinationImageView< TFactor1, TView1, TFactor2, TView2 >), dimension< TView1 >::value,(is_device_view< TView1 >::value &&is_device_view< TView2 >::value),(is_host_view< TView1 >::value &&is_host_view< TView2 >::value), typename TFactor1, typename TView1, typename TFactor2, typename TView2)
template<typename TFactor1 , typename TView1 , typename TFactor2 , typename TView2 >
LinearCombinationImageView< TFactor1, TView1, TFactor2, TView2 > linearCombination (TFactor1 factor1, TView1 view1, TFactor2 factor2, TView2 view2)
Utility function to create LinearCombinationImageView without the need to specify template parameters.
template<typename TView1 , typename TView2 >
LinearCombinationImageView< int, TView1, int, TView2 > add (TView1 view1, TView2 view2)
Utility function wrapping two image addition.
template<typename TView1 , typename TView2 >
LinearCombinationImageView< int, TView1, int, TView2 > subtract (TView1 view1, TView2 view2)
Utility function wrapping two image subtraction.
CUGIP_DECLARE_VIEW_TRAITS ((MultiplicationImageView< TView1, TView2 >), dimension< TView1 >::value,(is_device_view< TView1 >::value &&is_device_view< TView2 >::value),(is_host_view< TView1 >::value &&is_host_view< TView2 >::value), typename TView1, typename TView2)
template<typename TView1 , typename TView2 >
MultiplicationImageView< TView1, TView2 > multiply (TView1 view1, TView2 view2)
Utility function to create MultiplicationImageView without the need to specify template parameters.
CUGIP_DECLARE_VIEW_TRAITS ((MaskedImageView< TView1, TView2 >), dimension< TView1 >::value,(is_device_view< TView1 >::value &&is_device_view< TView2 >::value),(is_host_view< TView1 >::value &&is_host_view< TView2 >::value), typename TView1, typename TView2)
template<typename TView1 , typename TView2 >
MaskedImageView< TView1, TView2 > maskView (TView1 view1, TView2 view2, typename TView1::value_type aDefaultValue)
Utility function to create MultiplicationImageView without the need to specify template parameters.
CUGIP_DECLARE_VIEW_TRAITS ((DivisionImageView< TView1, TView2 >), dimension< TView1 >::value,(is_device_view< TView1 >::value &&is_device_view< TView2 >::value),(is_host_view< TView1 >::value &&is_host_view< TView2 >::value), typename TView1, typename TView2)
template<typename TView1 , typename TView2 >
DivisionImageView< TView1, TView2 > divide (TView1 view1, TView2 view2)
Utility function to create DivisionImageView without the need to specify template parameters.
CUGIP_DECLARE_VIEW_TRAITS ((MirrorImageView< TView >), dimension< TView >::value,(is_device_view< TView >::value),(is_host_view< TView >::value), typename TView)
template<typename TView >
MirrorImageView< TView > mirror (TView view, simple_vector< bool, TView::kDimension > flips)
Create mirror views with fliped axes specification.
CUGIP_DECLARE_VIEW_TRAITS ((PaddedImageView< TView >), dimension< TView >::value,(is_device_view< TView >::value),(is_host_view< TView >::value), typename TView)
template<typename TView >
PaddedImageView< TView > padView (TView view, simple_vector< int, dimension< TView >::value > size, simple_vector< int, dimension< TView >::value > offset, typename TView::value_type fill_value)
Create padded view.
CUGIP_DECLARE_VIEW_TRAITS ((UnaryOperatorImageView< TView, TOperator >), dimension< TView >::value,(is_device_view< TView >::value),(is_host_view< TView >::value), typename TView, typename TOperator)
template<typename TView >
UnaryOperatorImageView< TView, SquareFunctor > square (TView view)
Creates view which returns squared values from the original view.
template<typename TView >
UnaryOperatorImageView< TView, AbsFunctor > abs_view (TView view)
template<typename TView >
UnaryOperatorImageView< TView, SquareRootFunctor > squareRoot (TView view)
Creates view which returns square root of the values from the original view.
template<typename TFactor , typename TView >
UnaryOperatorImageView< TView, MultiplyByFactorFunctor< TFactor > > multiplyByFactor (TFactor factor, TView view)
Utility function to create multiplied view without the need to specify template parameters.
template<typename TType , typename TView >
UnaryOperatorImageView< TView, AddValueFunctor< TType > > addValue (TType value, TView view)
Creates view returning values from the original view with value added.
template<typename TType , typename TView >
UnaryOperatorImageView< TView, LowerLimitFunctor< TType > > lowerLimit (TType limit, TView view)
Returns view returning values from the original view with values lower then limit replaced by the limit.
template<typename TType , typename TView >
UnaryOperatorImageView< TView, LowerLimitReplacementFunctor< TType > > lowerLimit (TType limit, TType replacement, TView view)
Returns view returning values from the original view with values lower then limit replaced by the specified replacement.
template<typename TType , typename TView >
UnaryOperatorImageView< TView, UpperLimitFunctor< TType > > upperLimit (TType limit, TView view)
Returns view returning values from the original view with values bigger then limit replaced by the limit.
template<typename TType , typename TView >
UnaryOperatorImageView< TView, UpperLimitReplacementFunctor< TType > > upperLimit (TType limit, TType replacement, TView view)
Returns view returning values from the original view with values bigger then limit replaced by the specified replacement.
template<typename TFunctor , typename TView >
UnaryOperatorImageView< TView, TFunctor > unaryOperator (TView view, TFunctor functor)
CUGIP_DECLARE_VIEW_TRAITS ((UnaryOperatorOnPositionImageView< TView, TOperator >), dimension< TView >::value,(is_device_view< TView >::value),(is_host_view< TView >::value), typename TView, typename TOperator)
template<typename TFunctor , typename TView >
UnaryOperatorOnPositionImageView< TView, TFunctor > unaryOperatorOnPosition (TView view, TFunctor functor)
CUGIP_DECLARE_VIEW_TRAITS ((UnaryOperatorOnLocatorImageView< TView, TOperator, TBorderHandling >), dimension< TView >::value,(is_device_view< TView >::value),(is_host_view< TView >::value), typename TView, typename TOperator, typename TBorderHandling)
template<typename TFunctor , typename TView >
UnaryOperatorOnLocatorImageView< TView, TFunctor > unaryOperatorOnLocator (TView view, TFunctor functor)
CUGIP_DECLARE_VIEW_TRAITS ((NAryOperatorDeviceImageView< TOperator, TView, TViews... >), dimension< TView >::value,(MultiViewTraits< TView, TViews... >::cIsDeviceView),(MultiViewTraits< TView, TViews... >::cIsHostView), typename TOperator, typename TView, typename...TViews)
template<typename TFunctor , typename TView , typename... TViews>
NAryOperatorDeviceImageView< TFunctor, TView, TViews... > nAryOperator (TFunctor functor, TView view, TViews...views)
template<typename TView , typename... TViews>
NAryOperatorDeviceImageView< ZipValues, TView, TViews... > zipViews (TView view, TViews...views)
CUGIP_DECLARE_VIEW_TRAITS ((AccessDimensionImageView< TView, tIndex >), dimension< TView >::value,(is_device_view< TView >::value),(is_host_view< TView >::value), typename TView, int tIndex)
template<typename TView , typename TDimension >
AccessDimensionImageView< TView, TDimension::value > getDimension (TView view, TDimension)
Creates view which returns squared values from the original view.
template<typename TInView , typename TOutView , typename TFunctor >
void filter (TInView aInView, TOutView aOutView, TFunctor aOperator)
template<typename TImageView , typename TBorderHandling >
CUGIP_DECL_HYBRID image_locator< TImageView, TBorderHandling > create_locator (TImageView aView, typename TImageView::coord_t aCoords)
template<typename TElement , int tDim, typename TToView >
void asyncCopyHelper (texture_view< TElement, tDim > from_view, TToView to_view, DeviceToHostTag, cudaStream_t cuda_stream)
template<typename TFromView , typename TElement , int tDim>
void asyncCopyHelper (TFromView from_view, texture_view< TElement, tDim > to_view, HostToDeviceTag, cudaStream_t cuda_stream)
Detailed Description
Todo:
delate this file when not needed
Typedef Documentation
template<size_t N, typename... T> using cugip::choose = typedef type_of<Choose<N, T...>>
Definition at line 28 of file tuple.hpp.
typedef unsigned long cugip::CombinedNodeId
Definition at line 9 of file edge_record.hpp.
typedef CopyDirectionTag<true, true> cugip::DeviceToDeviceTag
Definition at line 213 of file copy.hpp.
typedef CopyDirectionTag<true, false> cugip::DeviceToHostTag
Definition at line 214 of file copy.hpp.
typedef element<signed char, 2> cugip::element_channel2_8s_t
Definition at line 100 of file element.hpp.
typedef unsigned char cugip::element_gray8_t
Definition at line 98 of file element.hpp.
typedef char cugip::element_gray8s_t
Definition at line 99 of file element.hpp.
typedef element<unsigned char, 3> cugip::element_rgb8_t
Definition at line 96 of file element.hpp.
typedef boost::error_info<struct tag_filename, boost::filesystem::path> cugip::FilenameErrorInfo
Error info containing file path.
Definition at line 18 of file exception.hpp.
typedef simple_vector<float, 2> cugip::Float2
Definition at line 514 of file math.hpp.
typedef simple_vector<float, 3> cugip::Float3
Definition at line 515 of file math.hpp.
typedef CopyDirectionTag<false, true> cugip::HostToDeviceTag
Definition at line 216 of file copy.hpp.
typedef CopyDirectionTag<false, false> cugip::HostToHostTag
Definition at line 215 of file copy.hpp.
typedef simple_vector<int, 2> cugip::Int2
Definition at line 511 of file math.hpp.
typedef simple_vector<int, 3> cugip::Int3
Definition at line 512 of file math.hpp.
typedef simple_vector<double, 2> cugip::intervald_t
Definition at line 500 of file math.hpp.
typedef simple_vector<float, 2> cugip::intervalf_t
Definition at line 499 of file math.hpp.
template<int tSize> using cugip::MakeIntSequence = typedef typename GenerateIntSequence<tSize>::Type
Definition at line 129 of file static_int_sequence.hpp.
typedef boost::error_info<struct tag_message, std::string> cugip::MessageErrorInfo
Definition at line 15 of file exception.hpp.
typedef unsigned cugip::NodeId
Definition at line 8 of file edge_record.hpp.
template<size_t L> using cugip::range = typedef type_of<Range <L>>
Definition at line 41 of file tuple.hpp.
typedef simple_vector<int, 2> cugip::size2_t
Definition at line 508 of file math.hpp.
typedef simple_vector<int, 3> cugip::size3_t
Definition at line 509 of file math.hpp.
template<typename T > using cugip::type_of = typedef typename T::type
Definition at line 12 of file tuple.hpp.
typedef simple_vector<float, 2> cugip::vect2f_t
Definition at line 502 of file math.hpp.
typedef simple_vector<int, 2> cugip::vect2i_t
Definition at line 505 of file math.hpp.
typedef simple_vector<float, 3> cugip::vect3f_t
Definition at line 503 of file math.hpp.
typedef simple_vector<int, 3> cugip::vect3i_t
Definition at line 506 of file math.hpp.
Enumeration Type Documentation
anonymous enum
Enumerator
CONNECTION_VERTEX
CONNECTION_INDEX_MASK
Definition at line 31 of file edge_record.hpp.
enum cugip::border_handling_enum strong
Enumerator
NONE
MIRROR
REPEAT
PERIODIC
ZERO
Definition at line 12 of file image_locator.hpp.
enum cugip::PreflowInitialization strong
Enumerator
Default
Push
Definition at line 13 of file graph_cut_policies.hpp.
enum cugip::RelabelImplementation strong
Enumerator
Default
Naive
OptimizedNaive
Definition at line 7 of file graph_cut_policies.hpp.
enum cugip::TLinkType : int strong
Enumerator
Source
Sink
Definition at line 18 of file graph_cut_policies.hpp.
Function Documentation
template<typename TType > CUGIP_DECL_HYBRID TType cugip::abs (TType aValue) inline
Definition at line 622 of file math.hpp.
References CUGIP_DECL_HYBRID.
Referenced by abs(), eigen_vectors(), cugip::gradient_magnitude< TInputType, TOutputType >::operator()(), cugip::generate_basins_ftor::operator()(), and cugip::AbsFunctor::operator()().
template<typename TType , int tDimension> CUGIP_DECL_HYBRID simple_vector<TType, tDimension> cugip::abs (simple_vector< TType, tDimension > aValue) inline
Definition at line 631 of file math.hpp.
References abs(), and CUGIP_DECL_HYBRID.
template<typename TView > UnaryOperatorImageView<TView, AbsFunctor> cugip::abs_view (TView view)
Definition at line 372 of file view_arithmetics.hpp.
References view().
template<typename TArg1View , typename TArg21View , typename TWeight > void cugip::add (TArg1View aArg1View, TWeight aWeight, TArg21View aArg2View)
Definition at line 26 of file arithmetics.hpp.
References CUGIP_ASSERT, and for_each().
template<typename TView1 , typename TView2 > LinearCombinationImageView<int, TView1, int, TView2> cugip::add (TView1 view1, TView2 view2)
Utility function wrapping two image addition.
Todo:
(johny) - possible more efficient implementation
Definition at line 87 of file view_arithmetics.hpp.
template<typename TType , typename TView > UnaryOperatorImageView<TView, AddValueFunctor<TType> > cugip::addValue (TType value, TView view)
Creates view returning values from the original view with value added.
Definition at line 394 of file view_arithmetics.hpp.
References view().
template<typename TLocator , typename TKernel , typename TResult > CUGIP_DECL_HYBRID void cugip::apply_convolution_kernel (TLocator aLocator, TKernel aKernel, TResult & aResult)
Definition at line 123 of file convolution.hpp.
References for_each_neighbor().
Referenced by cugip::sobel_gradient_magnitude< tDimension >::operator()(), cugip::convolution_operator< TKernel >::operator()(), and cugip::sobel_gradient< tDimension >::operator()().
template<typename TTensorView , typename TGradientView , typename TOutputView > void cugip::apply_diffusion_tensor (TTensorView aDiffusionTensor, TGradientView aGradient, TOutputView aOutput, float aTimeStep)
Definition at line 143 of file coherence_enhancing_diffusion.hpp.
References transform2(), and transform_locator_assign().
Referenced by coherence_enhancing_diffusion_step().
template<typename TInImageView , typename TOutImageView > void cugip::assign_masked_ids (TInImageView aInput, TOutImageView aOutput)
Definition at line 208 of file connected_component_labeling.hpp.
References transform_position().
template<typename TFlow > void cugip::assignLabelByDistance (GraphCutData< TFlow > & aGraphData, ParallelQueueView< int > aVertices)
Definition at line 8 of file graph_cut_dynpar.hpp.
References CUGIP_GLOBAL, and cugip::GraphCutData< TFlow >::vertexCount().
Referenced by maxFlowIterationsKernel().
template<typename TElement , int tDim, typename TToView > void cugip::asyncCopyHelper (texture_view< TElement, tDim > from_view, TToView to_view, DeviceToHostTag , cudaStream_t cuda_stream)
Definition at line 122 of file texture.hpp.
References CUGIP_ASSERT.
template<typename TFromView , typename TElement , int tDim> void cugip::asyncCopyHelper (TFromView from_view, texture_view< TElement, tDim > to_view, HostToDeviceTag , cudaStream_t cuda_stream)
Definition at line 134 of file texture.hpp.
References CUGIP_ASSERT.
template<typename TFromView , typename TToView > void cugip::asyncCopyHelper (TFromView from_view, TToView to_view, DeviceToDeviceTag , cudaStream_t cuda_stream)
Definition at line 345 of file copy.hpp.
References copyDeviceToDeviceAsync().
Referenced by copyAsync().
template<typename TFromView , typename TToView > void cugip::asyncCopyHelper (TFromView from_view, TToView to_view, DeviceToHostTag , cudaStream_t cuda_stream)
Definition at line 356 of file copy.hpp.
References copyDeviceToHostAsync().
template<typename TFromView , typename TToView > void cugip::asyncCopyHelper (TFromView from_view, TToView to_view, HostToDeviceTag , cudaStream_t cuda_stream)
Definition at line 367 of file copy.hpp.
References copyHostToDeviceAsync().
template<typename TFromView , typename TToView > void cugip::asyncCopyHelper (TFromView from_view, TToView to_view, HostToHostTag , cudaStream_t cuda_stream)
Todo:
async version
Definition at line 377 of file copy.hpp.
References copyHostToHost().
template<typename TGraph , typename TSweepOperator , typename TWorkDistribution , typename TPolicy > CUGIP_GLOBAL void cugip::bfsPropagationMultiIterationGlobalSyncKernel (ParallelQueueView< int > aVertices, int aStart, int aCount, ParallelQueueView< int > aLevelStarts, TGraph aGraph, int aCurrentLevel, TSweepOperator aSweepOperator, cub::GridBarrier barrier)
Definition at line 719 of file graph_cut_relabeling.hpp.
References cugip::ParallelQueueView< TType >::append(), CUGIP_GLOBAL, and cugip::ParallelQueueView< TType >::device_size().
template<typename TGraph , typename TSweepOperator , typename TWorkDistribution , typename TPolicy > CUGIP_GLOBAL void cugip::bfsPropagationMultiIterationKernel (ParallelQueueView< int > aVertices, int aStart, int aCount, ParallelQueueView< int > aLevelStarts, TGraph aGraph, int aCurrentLevel, TSweepOperator aSweepOperator)
Definition at line 686 of file graph_cut_relabeling.hpp.
References cugip::ParallelQueueView< TType >::append(), CUGIP_GLOBAL, and cugip::ParallelQueueView< TType >::device_size().
template<typename TGraph , typename TSweepOperator , typename TWorkDistribution > CUGIP_GLOBAL void cugip::bfsPropagationSingleIterationKernel (ParallelQueueView< int > aVertices, TWorkDistribution aWorkDistribution, TGraph aGraph, int aCurrentLevel, TSweepOperator aSweepOperator)
Definition at line 653 of file graph_cut_relabeling.hpp.
References CUGIP_GLOBAL.
template<typename TGraph , typename TSweepOperator , typename TWorkDistribution > CUGIP_GLOBAL void cugip::bfsPropagationSingleIterationKernel2 (ParallelQueueView< int > aVertices, TWorkDistribution aWorkDistribution, TGraph aGraph, int aCurrentLevel, TSweepOperator aSweepOperator)
Definition at line 669 of file graph_cut_relabeling.hpp.
References CUGIP_GLOBAL.
template<typename TInputTensorView , typename TOutputTensorView , typename TTmpTensorView > void cugip::blur_structural_tensor (TInputTensorView aStructuralTensor, TOutputTensorView aBluredStructuralTensor, TTmpTensorView aTmpTensorView)
Definition at line 118 of file coherence_enhancing_diffusion.hpp.
References separable_convolution().
Referenced by coherence_enhancing_diffusion_step().
template<typename TElement , int tDimension> CheckerBoardImageView<TElement, tDimension> cugip::checkerBoard (TElement white, TElement black, const simple_vector< int, tDimension > & tile_size, const simple_vector< int, tDimension > & size)
Utility function to create CheckerBoardImageView without the need to specify template parameters.
Definition at line 76 of file procedural_views.hpp.
template<typename TImageView , typename TIdImageView , typename TUnionFind > void cugip::clear_nonminima_plateaus (TImageView aImageView, TIdImageView aIdImageView, TUnionFind aUnionFind)
Definition at line 67 of file local_minima_detection.hpp.
Referenced by local_minima_detection().
template<typename TInView , typename TGradientView , typename TOutView , typename TTensorView > void cugip::coherence_enhancing_diffusion_step (TInView aInput, TOutView aOutput, TGradientView aGradient, TTensorView aStructuralTensor, TTensorView aDiffusionTensor, TTensorView aTmpTensor, float aTimeStep, float aAlpha, float aContrast)
Todo:
check requirements
Definition at line 157 of file coherence_enhancing_diffusion.hpp.
References apply_diffusion_tensor(), blur_structural_tensor(), compute_diffusion_tensor(), compute_gradient(), and compute_structural_tensor().
Referenced by cugip::coherence_enhancing_diffusion< tDimension >::iteration().
template<typename TTensorView > void cugip::compute_diffusion_tensor (TTensorView aDiffusionTensor, float aAlpha, float aContrast)
Definition at line 127 of file coherence_enhancing_diffusion.hpp.
References for_each().
Referenced by coherence_enhancing_diffusion_step().
template<typename TInView , typename TGradientView > void cugip::compute_gradient (TInView aInput, TGradientView aGradient)
Definition at line 13 of file coherence_enhancing_diffusion.hpp.
References transform_locator().
Referenced by coherence_enhancing_diffusion_step().
template<typename TImageSize > cugip::simple_vector<int, 3> cugip::compute_grid_size (const dim3 & aBlockSize, const TImageSize & aImageSize)
Definition at line 11 of file kernel_execution_utils.hpp.
template<typename TImageSize > dim3 cugip::compute_grid_size_dim3 (const dim3 & aBlockSize, const TImageSize & aImageSize)
Definition at line 24 of file kernel_execution_utils.hpp.
References CUGIP_DECL_DEVICE.
template<typename TGradientView , typename TTensorView > void cugip::compute_structural_tensor (TGradientView aGradient, TTensorView aStructuralTensor)
Definition at line 112 of file coherence_enhancing_diffusion.hpp.
References transform().
Referenced by coherence_enhancing_diffusion_step().
template<typename TImageView , typename TLUTBufferView > void cugip::connected_component_labeling (TImageView aImageView, TLUTBufferView aLUT)
Definition at line 162 of file connected_component_labeling.hpp.
References cugip::device_flag_view::check_host(), D_PRINT, cugip::device_flag_view::reset_host(), and cugip::device_flag::view().
Referenced by local_minima_detection(), and watershed_transformation1().
template<typename TImage > TImage::const_view_t cugip::const_view (TImage & aImage)
Definition at line 121 of file image.hpp.
Referenced by cugip::CellularAutomatonBaseCRTP< AsyncCellularAutomatonWithGlobalState< TGrid, TNeighborhood, TRule, TGlobalState, TSemiGlobalState >, TRule, device_image< TGrid::Element, TGrid::cDimension >, 2 >::currentInputView(), and cugip::CellularAutomatonBaseCRTP< AsyncCellularAutomatonWithGlobalState< TGrid, TNeighborhood, TRule, TGlobalState, TSemiGlobalState >, TRule, device_image< TGrid::Element, TGrid::cDimension >, 2 >::getCurrentState().
template<typename TElement > const_host_image_view<const TElement, 3> cugip::const_view (const itk::Image< TElement, 3 > & aImage)
Definition at line 33 of file itk_utils.hpp.
template<typename TElement > const_host_image_view<const TElement, 2> cugip::const_view (const itk::Image< TElement, 2 > & aImage)
Definition at line 45 of file itk_utils.hpp.
template<typename TElement , int tDim> texture_image<TElement, tDim>::view_t cugip::const_view (const texture_image< TElement, tDim > & aImage)
Definition at line 109 of file texture.hpp.
References cugip::texture_image< TElement, tDim >::view().
template<typename TElement , int tDim> host_image<TElement, tDim>::const_view_t cugip::const_view (const host_image< TElement, tDim > & aImage)
Definition at line 123 of file host_image.hpp.
References cugip::host_image< TElement, tDim >::const_view().
template<typename TElement , int tDimension> ConstantDeviceImageView<TElement, tDimension> cugip::constantImage (TElement value, simple_vector< int, tDimension > size)
Utility function to create ConstantDeviceImageView without the need to specify template parameters.
Definition at line 39 of file procedural_views.hpp.
template<typename TInputView , typename TOutputView , typename TKernel > void cugip::convolution (TInputView aInView, TOutputView aOutView, TKernel aKernel)
Definition at line 169 of file convolution.hpp.
References transform_locator().
template<typename TCoords > CUGIP_DECL_DEVICE TCoords cugip::coords_from_block_dim ()
Definition at line 51 of file kernel_execution_utils.hpp.
template<typename TLoc , typename TToView > void cugip::copy (boost::gil::image_view< TLoc > from_view, TToView to_view)
Definition at line 11 of file gil_utils.hpp.
References D_PRINT.
template<typename TFromView , typename TToView > void cugip::copy (TFromView from_view, TToView to_view)
Synchronous copy between compatible image views.
See also
CopyAsync()
Definition at line 440 of file copy.hpp.
References copyAsync().
Referenced by cugip::ParallelQueue< int >::fill_host(), cugip::Graph< TFlow >::fill_segments(), cugip::CellularAutomatonBaseCRTP< AsyncCellularAutomatonWithGlobalState< TGrid, TNeighborhood, TRule, TGlobalState, TSemiGlobalState >, TRule, device_image< TGrid::Element, TGrid::cDimension >, 2 >::initialize(), cugip::Graph< TFlow >::set_nweights(), and cugip::Graph< TFlow >::set_tweights().
template<typename TFromView , typename TToView > void cugip::copyAsync (TFromView from_view, TToView to_view, cudaStream_t cuda_stream = 0)
Asynchronous copy between compatible image views. Device/host direction is defined by the type of these views. Copying views between host <-> device must be done through memory based views.
Parameters
from_view Source
to_view Target
cuda_stream Selected CUDA stream.
Definition at line 417 of file copy.hpp.
References asyncCopyHelper(), CUGIP_DFORMAT, and CUGIP_THROW.
Referenced by copy().
template<typename TFromView , typename TToView > void cugip::copyDeviceToDeviceAsync (TFromView from_view, TToView to_view, cudaStream_t cuda_stream)
Todo:
(johny) - use memcpy for memory based views
Definition at line 265 of file copy.hpp.
Referenced by asyncCopyHelper().
template<typename TFromView , typename TToView > void cugip::copyDeviceToHostAsync (TFromView from_view, TToView to_view, cudaStream_t cuda_stream)
Definition at line 299 of file copy.hpp.
References CUGIP_DFORMAT, makeCudaExtent(), and stridesToPitchedPtr().
Referenced by asyncCopyHelper().
template<typename TFromView , typename TToView > void cugip::copyHostToDeviceAsync (TFromView from_view, TToView to_view, cudaStream_t cuda_stream)
Definition at line 322 of file copy.hpp.
References CUGIP_DFORMAT, makeCudaExtent(), and stridesToPitchedPtr().
Referenced by asyncCopyHelper().
template<typename TFromView , typename TToView > void cugip::copyHostToHost (TFromView from_view, TToView to_view)
Todo:
(johny) - use memcpy for memory based views
Definition at line 287 of file copy.hpp.
References elementCount(), and linear_access().
Referenced by asyncCopyHelper().
template<typename TFromView , typename TToView > CUGIP_GLOBAL void cugip::copyKernel (TFromView from_view, TToView to_view)
Todo:
(reorganize)
Definition at line 241 of file copy.hpp.
template<typename TCoords > CUGIP_DECL_DEVICE TCoords cugip::corner_coords_from_block_dim ()
Definition at line 38 of file kernel_execution_utils.hpp.
References CUGIP_DECL_DEVICE.
template<typename TImageView , typename TBorderHandling > CUGIP_DECL_HYBRID image_locator<TImageView, TBorderHandling> cugip::create_locator (TImageView aView, typename TImageView::coord_t aCoords)
Definition at line 208 of file image_locator.hpp.
cugip::CUGIP_DECLARE_DEVICE_VIEW_TRAITS ((texture_view< TElement, tDim >) , tDim , typename TElement , int tDim)
cugip::CUGIP_DECLARE_DEVICE_VIEW_TRAITS ((device_image_view< TElement, tDim >) , tDim , typename TElement , int tDim)
cugip::CUGIP_DECLARE_DEVICE_VIEW_TRAITS ((const_device_image_view< TElement, tDim >) , tDim , typename TElement , int tDim)
cugip::CUGIP_DECLARE_HOST_VIEW_TRAITS ((host_image_view< TElement, tDim >) , tDim , typename TElement , int tDim)
cugip::CUGIP_DECLARE_HOST_VIEW_TRAITS ((const_host_image_view< TElement, tDim >) , tDim , typename TElement , int tDim)
cugip::CUGIP_DECLARE_HYBRID_VIEW_TRAITS ((ConstantDeviceImageView< TElement, tDim >) , tDim , typename TElement , int tDim)
Referenced by cugip::UniqueIdDeviceImageView< tDimension, TIdGenerator >::operator[]().
cugip::CUGIP_DECLARE_HYBRID_VIEW_TRAITS ((CheckerBoardImageView< TElement, tDim >) , tDim , typename TElement , int tDim)
cugip::CUGIP_DECLARE_HYBRID_VIEW_TRAITS ((UniqueIdDeviceImageView< tDimension, TId >) , tDimension , int tDimension, typename TId)
cugip::CUGIP_DECLARE_HYBRID_VIEW_TRAITS ((MeshGridView< tDimension >) , tDimension , int tDimension)
cugip::CUGIP_DECLARE_VIEW_TRAITS ((LinearCombinationImageView< TFactor1, TView1, TFactor2, TView2 >) , dimension< TView1 >::value , (is_device_view< TView1 >::value &&is_device_view< TView2 >::value) , (is_host_view< TView1 >::value &&is_host_view< TView2 >::value) , typename TFactor1 , typename TView1 , typename TFactor2 , typename TView2)
cugip::CUGIP_DECLARE_VIEW_TRAITS ((MultiplicationImageView< TView1, TView2 >) , dimension< TView1 >::value , (is_device_view< TView1 >::value &&is_device_view< TView2 >::value) , (is_host_view< TView1 >::value &&is_host_view< TView2 >::value) , typename TView1 , typename TView2)
cugip::CUGIP_DECLARE_VIEW_TRAITS ((MaskedImageView< TView1, TView2 >) , dimension< TView1 >::value , (is_device_view< TView1 >::value &&is_device_view< TView2 >::value) , (is_host_view< TView1 >::value &&is_host_view< TView2 >::value) , typename TView1 , typename TView2)
cugip::CUGIP_DECLARE_VIEW_TRAITS ((DivisionImageView< TView1, TView2 >) , dimension< TView1 >::value , (is_device_view< TView1 >::value &&is_device_view< TView2 >::value) , (is_host_view< TView1 >::value &&is_host_view< TView2 >::value) , typename TView1 , typename TView2)
cugip::CUGIP_DECLARE_VIEW_TRAITS ((MirrorImageView< TView >) , dimension< TView >::value , (is_device_view< TView >::value) , (is_host_view< TView >::value) , typename TView)
cugip::CUGIP_DECLARE_VIEW_TRAITS ((PaddedImageView< TView >) , dimension< TView >::value , (is_device_view< TView >::value) , (is_host_view< TView >::value) , typename TView)
cugip::CUGIP_DECLARE_VIEW_TRAITS ((UnaryOperatorImageView< TView, TOperator >) , dimension< TView >::value , (is_device_view< TView >::value) , (is_host_view< TView >::value) , typename TView , typename TOperator)
cugip::CUGIP_DECLARE_VIEW_TRAITS ((UnaryOperatorOnPositionImageView< TView, TOperator >) , dimension< TView >::value , (is_device_view< TView >::value) , (is_host_view< TView >::value) , typename TView , typename TOperator)
cugip::CUGIP_DECLARE_VIEW_TRAITS ((UnaryOperatorOnLocatorImageView< TView, TOperator, TBorderHandling >) , dimension< TView >::value , (is_device_view< TView >::value) , (is_host_view< TView >::value) , typename TView , typename TOperator , typename TBorderHandling)
cugip::CUGIP_DECLARE_VIEW_TRAITS ((NAryOperatorDeviceImageView< TOperator, TView, TViews... >) , dimension< TView >::value , (MultiViewTraits< TView, TViews... >::cIsDeviceView) , (MultiViewTraits< TView, TViews... >::cIsHostView) , typename TOperator , typename TView , typename... TViews)
cugip::CUGIP_DECLARE_VIEW_TRAITS ((AccessDimensionImageView< TView, tIndex >) , dimension< TView >::value , (is_device_view< TView >::value) , (is_host_view< TView >::value) , typename TView , int tIndex)
CUGIP_DECL_DEVICE int cugip::currentBlockSize () inline
Definition at line 115 of file cuda_utils.hpp.
References CUGIP_DECL_DEVICE.
CUGIP_DECL_DEVICE vect3i_t cugip::currentThreadIndex () inline
Definition at line 121 of file cuda_utils.hpp.
References CUGIP_DECL_DEVICE.
template<int tDimension> CUGIP_DECL_HYBRID simple_vector<int, tDimension> cugip::dim3_to_vector (dim3)
Referenced by is_in_thread().
template<> CUGIP_DECL_HYBRID simple_vector<int, 2> cugip::dim3_to_vector< 2 > (dim3 aValue)
Definition at line 144 of file cuda_utils.hpp.
References CUGIP_ASSERT, and CUGIP_DECL_HYBRID.
template<> CUGIP_DECL_HYBRID simple_vector<int, 3> cugip::dim3_to_vector< 3 > (dim3 aValue)
Definition at line 152 of file cuda_utils.hpp.
template<typename TType , int tDimension> CUGIP_DECL_HYBRID simple_vector<TType, tDimension> cugip::div (const simple_vector< TType, tDimension > & aVector1, TType aValue) inline
Definition at line 704 of file math.hpp.
References CUGIP_DECL_HYBRID.
Referenced by get_blocked_order_access_index(), and cugip::CheckerBoardImageView< TElement, tDimension >::operator[]().
template<typename TType , int tDimension> CUGIP_DECL_HYBRID simple_vector<TType, tDimension> cugip::div (const simple_vector< TType, tDimension > & aVector1, const simple_vector< TType, tDimension > & aVector2) inline
Definition at line 715 of file math.hpp.
References CUGIP_DECL_HYBRID.
template<typename TView1 , typename TView2 > DivisionImageView<TView1, TView2> cugip::divide (TView1 view1, TView2 view2)
Utility function to create DivisionImageView without the need to specify template parameters.
Definition at line 216 of file view_arithmetics.hpp.
template<typename TView > CUGIP_HD_WARNING_DISABLE CUGIP_DECL_HYBRID int cugip::elementCount (const TView & aView)
Definition at line 80 of file view_declaration_utils.hpp.
References CUGIP_DECL_HYBRID, CUGIP_HD_WARNING_DISABLE, and product().
Referenced by copyHostToHost().
template<typename TView , typename TType > void cugip::fill (TView aView, TType aValue)
Definition at line 27 of file fill.hpp.
References D_PRINT.
Referenced by cugip::Graph< TFlow >::set_tweights().
template<typename TVector > CUGIP_DECL_HYBRID std::enable_if< static_vector_traits<TVector>::is_vector, simple_vector<typename static_vector_traits<TVector>::element_type, 3> >::type cugip::find_orthonormal (const TVector & aVector) inline
Definition at line 762 of file math.hpp.
References sqr().
Referenced by eigen_vectors().
template<int tRadius, typename TCallable > CUGIP_HD_WARNING_DISABLE CUGIP_DECL_DEVICE void cugip::for_each_in_radius (TCallable aCallable)
Todo:
cleanuup the unroll
Definition at line 136 of file neighborhood_accessor.hpp.
References CUGIP_DECL_DEVICE, and CUGIP_HD_WARNING_DISABLE.
template<int tRadius, typename TCallable > CUGIP_HD_WARNING_DISABLE CUGIP_DECL_DEVICE void cugip::for_each_in_radius2 (TCallable aCallable)
Definition at line 153 of file neighborhood_accessor.hpp.
template<typename TCallable > CUGIP_HD_WARNING_DISABLE CUGIP_DECL_HYBRID void cugip::for_each_neighbor (simple_vector< int, 2 > aRadius, TCallable aCallable)
Definition at line 79 of file neighborhood_accessor.hpp.
References CUGIP_DECL_HYBRID, and CUGIP_HD_WARNING_DISABLE.
Referenced by apply_convolution_kernel(), cugip::sobel_weighted_divergence< tDimension >::operator()(), and sobel_gradient_kernel().
template<typename TCallable > CUGIP_HD_WARNING_DISABLE CUGIP_DECL_HYBRID void cugip::for_each_neighbor (simple_vector< int, 3 > aRadius, TCallable aCallable)
Definition at line 92 of file neighborhood_accessor.hpp.
References CUGIP_DECL_HYBRID, and CUGIP_HD_WARNING_DISABLE.
template<typename TCallable > CUGIP_HD_WARNING_DISABLE CUGIP_DECL_HYBRID void cugip::for_each_neighbor (simple_vector< int, 2 > aFrom, simple_vector< int, 2 > aTo, TCallable aCallable)
Definition at line 107 of file neighborhood_accessor.hpp.
References CUGIP_DECL_HYBRID, and CUGIP_HD_WARNING_DISABLE.
template<typename TCallable > CUGIP_HD_WARNING_DISABLE CUGIP_DECL_HYBRID void cugip::for_each_neighbor (simple_vector< int, 3 > aFrom, simple_vector< int, 3 > aTo, TCallable aCallable)
Definition at line 120 of file neighborhood_accessor.hpp.
References CUGIP_DECL_DEVICE, and CUGIP_HD_WARNING_DISABLE.
template<typename TFlow , typename TFunctor > void cugip::for_each_vertex (GraphCutData< TFlow > & aGraph, TFunctor aFunctor)
Definition at line 157 of file graph_cut_data.hpp.
References cugip::GraphCutData< TFlow >::vertexCount().
template<typename TFlow , typename TFunctor > CUGIP_GLOBAL void cugip::forEachVertexKernel (GraphCutData< TFlow > aGraph, TFunctor aFunctor)
Definition at line 144 of file graph_cut_data.hpp.
References cugip::GraphCutData< TFlow >::vertexCount().
template<int tRadius> convolution_kernel<float, StaticSize<2 * tRadius + 1> > cugip::gaussian_kernel ()
Definition at line 101 of file convolution.hpp.
References CUGIP_DECL_HYBRID, cugip::convolution_kernel< TType, TSizeTraits >::get(), cugip::convolution_kernel< TType, TSizeTraits >::offset, sqr(), and sum().
template<int tIdx, typename TType > CUGIP_DECL_HYBRID get_policy<tIdx, typename std::remove_reference<TType>::type >::return_type cugip::get (TType & aArg)
Definition at line 64 of file utils.hpp.
References get().
template<int tIdx1, int tIdx2, typename TType > CUGIP_DECL_HYBRID float cugip::get (TType & aArg)
Definition at line 77 of file utils.hpp.
References CUGIP_DECL_DEVICE, and get().
template<int tIdx, typename TType , int tChannelCount> CUGIP_DECL_HYBRID TType& cugip::get (element< TType, tChannelCount > & aArg)
Definition at line 80 of file element.hpp.
References CUGIP_DECL_HYBRID.
Referenced by cugip::image_locator< TImageView, TBorderHandling >::dim_offset(), get(), and cugip::TupleImpl< Sizes< N... >, T... >::get().
template<int tIdx, typename TType , int tChannelCount> CUGIP_DECL_HYBRID const TType& cugip::get (const element< TType, tChannelCount > & aArg)
Definition at line 87 of file element.hpp.
template<int tBlockSize, typename TExtents , typename TCoordinates > CUGIP_DECL_HYBRID int cugip::get_blocked_order_access_index (TExtents aExtents, TCoordinates aCoordinates)
Definition at line 194 of file access_utils.hpp.
References div(), and min_per_element().
template<typename TExtents , typename TCoordinates > CUGIP_DECL_HYBRID int cugip::get_linear_access_index (TExtents aExtents, TCoordinates aCoordinates)
Definition at line 79 of file access_utils.hpp.
Referenced by cugip::LinearAccessIndex< TId >::compute(), cugip::convolution_kernel< simple_vector< float, tDimension >, typename FillStaticSize< tDimension, 3 >::Type >::get(), cugip::local_minima_detection_ftor< TLabel >::operator()(), cugip::assign_masked_id_functor< TOutputValue, TDimension >::operator()(), cugip::init_watershed_labels_ftor< TUnionFind, TExtents >::operator()(), cugip::init_watershed_labels_from_plateaus_ftor< TUnionFind, TExtents >::operator()(), and cugip::LocalMinimumLabel::operator()().
template<typename TExtents , typename TCoordinates > CUGIP_DECL_HYBRID int cugip::get_zorder_access_index (TExtents aExtents, TCoordinates aCoordinates)
Definition at line 155 of file access_utils.hpp.
References CUGIP_DECL_HYBRID, and splitBy3().
template<typename TView , typename TDimension > AccessDimensionImageView<TView, TDimension::value> cugip::getDimension (TView view, TDimension)
Creates view which returns squared values from the original view.
Definition at line 664 of file view_arithmetics.hpp.
References view().
template<typename TGraph , typename TGraphCutData > void cugip::graphCutDataFromGraph (TGraph & aGraph, TGraphCutData & aGraphData)
Definition at line 44 of file graph_cut_implementation.hpp.
References Sink, and Source.
Referenced by cugip::MinimalGraphCutComputation< TGraph >::setGraph().
template<typename... TArgs> void cugip::ignoreReturnValues (TArgs...)
Definition at line 9 of file static_int_sequence.hpp.
Referenced by cugip::MultiIntervalMeasurement< TTimerSet, tTimerId >::MultiIntervalMeasurement(), cugip::MultiIntervalMeasurement< TTimerSet, tTimerId >::reset(), cugip::MultiIntervalMeasurement< TTimerSet, tTimerId >::stop(), and cugip::MultiIntervalMeasurement< TTimerSet, tTimerId >::stopAll().
template<int tDimension> CUGIP_HD_WARNING_DISABLE CUGIP_DECL_HYBRID simple_vector<int, tDimension> cugip::index_from_linear_access_index (const simple_vector< int, tDimension > & aExtents, int aIdx)
Definition at line 36 of file access_utils.hpp.
References CUGIP_DECL_HYBRID, and CUGIP_HD_WARNING_DISABLE.
Referenced by index_from_linear_access_index(), and linear_access().
template<typename TImageView > CUGIP_HD_WARNING_DISABLE CUGIP_DECL_HYBRID auto cugip::index_from_linear_access_index (const TImageView & aView, int aIdx) -> typename TImageView::coord_t
Definition at line 50 of file access_utils.hpp.
References CUGIP_DECL_HYBRID, CUGIP_HD_WARNING_DISABLE, and index_from_linear_access_index().
template<typename TIdImageView , typename TDistanceView > void cugip::init_watershed_buffers (TIdImageView aIdImageView, TDistanceView aDistanceView)
Todo:
Definition at line 179 of file watershed_transformation.hpp.
References CUGIP_GLOBAL, and for_each().
Referenced by watershed_transformation2().
template<typename TIdImageView , typename TUnionFind > void cugip::init_watershed_from_plateaus_labels (TIdImageView aIdImageView, TUnionFind aUnionFind)
Definition at line 353 of file watershed_transformation.hpp.
References for_each_position().
Referenced by watershed_transformation1().
template<typename TIdImageView , typename TUnionFind > void cugip::init_watershed_labels (TIdImageView aIdImageView, TUnionFind aUnionFind)
Definition at line 318 of file watershed_transformation.hpp.
References for_each_position().
template<typename TGraph , typename TPolicy > CUGIP_GLOBAL void cugip::initBFSKernel (ParallelQueueView< int > aVertices, TGraph aGraph)
Definition at line 49 of file graph_cut_relabeling.hpp.
References cugip::ParallelQueueView< TType >::allocate(), CUGIP_DECL_DEVICE, and cugip::ParallelQueueView< TType >::get_device().
template<typename TFlow > CUGIP_GLOBAL void cugip::initResidualsKernel (TFlow * aWeightsForward, TFlow * aWeightsBackward, EdgeResidualsRecord< TFlow > * aResiduals, int aSize)
Definition at line 30 of file graph_cut_implementation.hpp.
References cugip::EdgeResidualsRecord< TFlow >::residuals.
template<typename TType , int tDimension> CUGIP_DECL_HYBRID simple_vector<TType, tDimension + 1> cugip::insert_dimension (const simple_vector< TType, tDimension > & v, TType inserted_coordinate, int dimension)
Definition at line 597 of file math.hpp.
References CUGIP_ASSERT.
CUGIP_DECL_DEVICE bool cugip::is_in_block (int aX, int aY, int aZ) inline
Definition at line 127 of file cuda_utils.hpp.
References CUGIP_DECL_DEVICE.
CUGIP_DECL_DEVICE bool cugip::is_in_thread (int aX, int aY, int aZ) inline
Definition at line 133 of file cuda_utils.hpp.
References CUGIP_DECL_HYBRID, and dim3_to_vector().
template<typename TView > CUGIP_HD_WARNING_DISABLE CUGIP_DECL_HYBRID bool cugip::isEmpty (const TView & aView)
Definition at line 88 of file view_declaration_utils.hpp.
References product().
Referenced by for_each(), for_each_position(), transform(), transform2(), transform_locator(), transform_locator_assign(), and transform_position().
template<int tDimension> CUGIP_DECL_HYBRID bool cugip::isInsideRegion (const simple_vector< int, tDimension > & aSize, const simple_vector< int, tDimension > & aCoords)
Definition at line 18 of file region.hpp.
References CUGIP_DECL_HYBRID.
Referenced by cugip::NeighborhoodAccessor< TLocator, TNeighborhood >::is_inside_valid_region().
template<int tDimension> CUGIP_DECL_HYBRID bool cugip::isInsideRegion (const region< tDimension > & aRegion, const simple_vector< int, tDimension > & aCoords)
Definition at line 26 of file region.hpp.
References cugip::region< tDimension >::corner, CUGIP_DECL_HYBRID, CUGIP_HD_WARNING_DISABLE, and cugip::region< tDimension >::size.
template<typename TClassId > CUGIP_GLOBAL void cugip::kernelCompaction (TClassId * aBuffer, int aSize)
Definition at line 11 of file equivalence_management.hpp.
References CUGIP_ASSERT, and CUGIP_GLOBAL.
template<typename TClassId > CUGIP_GLOBAL void cugip::kernelInitialization (TClassId * aBuffer, int aSize)
Definition at line 27 of file equivalence_management.hpp.
__device__ __inline__ int32_t cugip::ld_gbl_cg (const int32_t * addr)
Definition at line 8 of file graph_cut_data.hpp.
__device__ __inline__ double cugip::ld_gbl_cg (const double * addr)
Definition at line 14 of file graph_cut_data.hpp.
template<typename TImageView > CUGIP_HD_WARNING_DISABLE CUGIP_DECL_HYBRID auto cugip::linear_access (const TImageView & aView, int aIdx) -> typename TImageView::accessed_type
Definition at line 58 of file access_utils.hpp.
References CUGIP_DECL_HYBRID, and index_from_linear_access_index().
Referenced by copyHostToHost(), cugip::device_linear_access_view< TImageView >::operator[](), and cugip::host_linear_access_view< TImageView >::operator[]().
template<typename TImageView > host_linear_access_view<TImageView> cugip::linear_access_view (TImageView aView)
Todo:
handle device branch
Definition at line 136 of file access_utils.hpp.
template<typename TExtents , typename TCoordinates > CUGIP_DECL_HYBRID int64_t cugip::linear_index_from_strides (TExtents aStrides, TCoordinates aCoordinates) inline
Definition at line 65 of file access_utils.hpp.
References CUGIP_DECL_HYBRID.
template<typename TFactor1 , typename TView1 , typename TFactor2 , typename TView2 > LinearCombinationImageView<TFactor1, TView1, TFactor2, TView2> cugip::linearCombination (TFactor1 factor1, TView1 view1, TFactor2 factor2, TView2 view2)
Utility function to create LinearCombinationImageView without the need to specify template parameters.
Definition at line 79 of file view_arithmetics.hpp.
template<typename TInView , typename TOutView > void cugip::local_minima (TInView aInView, TOutView aOutView)
Definition at line 16 of file local_extremas.hpp.
template<typename TImageView , typename TIdImageView , typename TUnionFind > void cugip::local_minima_detection (TImageView aImageView, TIdImageView aIdImageView, TUnionFind aUnionFind)
Definition at line 80 of file local_minima_detection.hpp.
References clear_nonminima_plateaus(), connected_component_labeling(), and filter().
template<typename TType , typename TView > UnaryOperatorImageView<TView, LowerLimitFunctor<TType> > cugip::lowerLimit (TType limit, TView view)
Returns view returning values from the original view with values lower then limit replaced by the limit.
Definition at line 402 of file view_arithmetics.hpp.
References view().
template<typename TType , typename TView > UnaryOperatorImageView<TView, LowerLimitReplacementFunctor<TType> > cugip::lowerLimit (TType limit, TType replacement, TView view)
Returns view returning values from the original view with values lower then limit replaced by the specified replacement.
Definition at line 410 of file view_arithmetics.hpp.
References view().
template<typename TElement , int tDimension> CUGIP_DECL_HYBRID const_device_image_view<const TElement, tDimension> cugip::makeConstDeviceImageView (const TElement * buffer, simple_vector< int, tDimension > size)
Definition at line 228 of file image_view.hpp.
References CUGIP_DECL_HYBRID, and stridesFromSize().
template<typename TElement , int tDimension> CUGIP_DECL_HYBRID const_device_image_view<const TElement, tDimension> cugip::makeConstDeviceImageView (const TElement * buffer, simple_vector< int, tDimension > size, simple_vector< int, tDimension > strides)
Definition at line 234 of file image_view.hpp.
References CUGIP_DECL_HYBRID, and cugip::device_image_view< TElement, tDim >::strides().
template<typename TElement , int tDimension> const_host_image_view<const TElement, tDimension> cugip::makeConstHostImageView (const TElement * buffer, simple_vector< int, tDimension > size)
Definition at line 136 of file host_image_view.hpp.
References stridesFromSize().
template<typename TElement , int tDimension> const_host_image_view<const TElement, tDimension> cugip::makeConstHostImageView (const TElement * buffer, simple_vector< int, tDimension > size, simple_vector< int, tDimension > strides)
Definition at line 142 of file host_image_view.hpp.
References cugip::host_image_view< TElement, tDim >::strides().
cudaExtent cugip::makeCudaExtent (int bytes, Int2 size) inline
Parameters
bytes Size of array element in bytes.
size Size of 2D array in number of elements.
Definition at line 17 of file cuda_utils.hpp.
Referenced by copyDeviceToHostAsync(), and copyHostToDeviceAsync().
cudaExtent cugip::makeCudaExtent (int bytes, Int3 size) inline
Parameters
bytes Size of array element in bytes.
size Size of 3D array in number of elements.
Definition at line 23 of file cuda_utils.hpp.
References pitchedPtrToStrides().
template<typename TElement , int tDimension> CUGIP_DECL_HYBRID device_image_view<TElement, tDimension> cugip::makeDeviceImageView (TElement * buffer, simple_vector< int, tDimension > size)
Definition at line 241 of file image_view.hpp.
References CUGIP_DECL_HYBRID, and stridesFromSize().
Referenced by kernel_hidden_updates().
template<typename TElement , int tDimension> CUGIP_DECL_HYBRID device_image_view<TElement, tDimension> cugip::makeDeviceImageView (TElement * buffer, simple_vector< int, tDimension > size, simple_vector< int, tDimension > strides)
Definition at line 247 of file image_view.hpp.
References cugip::device_image_view< TElement, tDim >::strides().
template<typename TElement , int tDimension> host_image_view<TElement, tDimension> cugip::makeHostImageView (TElement * buffer, simple_vector< int, tDimension > size)
Definition at line 149 of file host_image_view.hpp.
References stridesFromSize().
template<typename TElement , int tDimension> host_image_view<TElement, tDimension> cugip::makeHostImageView (TElement * buffer, simple_vector< int, tDimension > size, simple_vector< int, tDimension > strides)
Definition at line 155 of file host_image_view.hpp.
References cugip::host_image_view< TElement, tDim >::strides().
template<int tDimension> CUGIP_DECL_DEVICE cugip::simple_vector<int, tDimension> cugip::mapBlockIdxAndThreadIdxToViewCoordinates ()
Get 1 to 1 mapping between cuda threads in grid and view coordinates.
Referenced by stridesToPitchedPtr().
template<> CUGIP_DECL_DEVICE cugip::simple_vector<int, 2> cugip::mapBlockIdxAndThreadIdxToViewCoordinates< 2 > ()
Definition at line 69 of file cuda_utils.hpp.
References CUGIP_ASSERT, and CUGIP_DECL_DEVICE.
template<> CUGIP_DECL_DEVICE cugip::simple_vector<int, 3> cugip::mapBlockIdxAndThreadIdxToViewCoordinates< 3 > ()
Definition at line 79 of file cuda_utils.hpp.
References CUGIP_DECL_DEVICE, and mapBlockIdxToViewCoordinates().
template<int tDimension> CUGIP_DECL_DEVICE cugip::simple_vector<int, tDimension> cugip::mapBlockIdxToViewCoordinates ()
Referenced by mapBlockIdxAndThreadIdxToViewCoordinates< 3 >().
template<> CUGIP_DECL_DEVICE cugip::simple_vector<int, 2> cugip::mapBlockIdxToViewCoordinates< 2 > ()
Definition at line 90 of file cuda_utils.hpp.
References CUGIP_ASSERT, and CUGIP_DECL_DEVICE.
template<> CUGIP_DECL_DEVICE cugip::simple_vector<int, 3> cugip::mapBlockIdxToViewCoordinates< 3 > ()
Definition at line 100 of file cuda_utils.hpp.
References CUGIP_DECL_DEVICE.
template<typename TView1 , typename TView2 > MaskedImageView<TView1, TView2> cugip::maskView (TView1 view1, TView2 view2, typename TView1::value_type aDefaultValue)
Utility function to create MultiplicationImageView without the need to specify template parameters.
Definition at line 172 of file view_arithmetics.hpp.
template<typename TType , int tDimension> CUGIP_DECL_HYBRID TType cugip::matrix_trace (const symmetric_tensor< TType, tDimension > & aMatrix)
Definition at line 77 of file symmetric_tensor.hpp.
References cugip::symmetric_tensor< TType, tDimension >::get().
template<typename TType , int tRowCount> CUGIP_DECL_HYBRID TType cugip::matrix_trace (const matrix< TType, tRowCount, tRowCount > & aMatrix)
Definition at line 133 of file matrix.hpp.
References cugip::matrix< TType, tRowCount, tColCount >::get().
Referenced by eigen_values().
template<typename TType > CUGIP_DECL_HYBRID TType cugip::max (TType aValue1, TType aValue2) inline
Definition at line 642 of file math.hpp.
References CUGIP_DECL_HYBRID.
Referenced by cugip::EdgeRecord::EdgeRecord(), eigen_vectors(), max(), max_per_element(), cugip::EquivalenceManager< int >::merge(), cugip::convert_float_and_byte::operator()(), cugip::generate_basins_ftor::operator()(), cugip::LowerLimitFunctor< TType >::operator()(), cugip::scan_image_for_wshed_path_ftor< TUnionFind >::operator()(), and watershed_evolution_kernel().
template<typename TType , int tDimension> CUGIP_DECL_HYBRID TType cugip::max (simple_vector< TType, tDimension > aValue) inline
Definition at line 648 of file math.hpp.
References CUGIP_DECL_HYBRID, and max().
template<typename TType , int tDimension> CUGIP_DECL_HYBRID simple_vector<TType, tDimension> cugip::max_per_element (simple_vector< TType, tDimension > aVector1, const simple_vector< TType, tDimension > & aVector2) inline
Definition at line 684 of file math.hpp.
References CUGIP_DECL_HYBRID, and max().
Referenced by cugip::BorderHandlingTraits< border_handling_enum::REPEAT >::access(), and cugip::MaxFunctor::operator()().
template<typename TFlow > CUGIP_GLOBAL void cugip::maxFlowIterationsKernel (GraphCutData< TFlow > aGraph, ParallelQueueView< int > aVertices)
Definition at line 31 of file graph_cut_dynpar.hpp.
References assignLabelByDistance().
template<int tDimension> std::array<MeshGridView<tDimension>, tDimension> cugip::meshGrid (simple_vector< int, tDimension > from, simple_vector< int, tDimension > to)
Rectangular grid in N-D space. Inspired by Matlab function of the same name: [X,Y] = MeshGrid(Int2(1, 10), Int2(3, 14)) X = 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 Y = 10 10 10 11 11 11 12 12 12 13 13 13 14 14 14
Definition at line 195 of file procedural_views.hpp.
template<typename TType > CUGIP_DECL_HYBRID TType cugip::min (TType aValue1, TType aValue2) inline
Definition at line 658 of file math.hpp.
References CUGIP_DECL_HYBRID.
Referenced by cugip::EdgeRecord::EdgeRecord(), cugip::EquivalenceManager< int >::merge(), min(), min_per_element(), cugip::convert_float_and_byte::operator()(), cugip::UpperLimitFunctor< TType >::operator()(), cugip::scan_image_for_wshed_path_ftor< TUnionFind >::operator()(), and tryPull().
template<typename TType , int tDimension> CUGIP_DECL_HYBRID TType cugip::min (simple_vector< TType, tDimension > aValue) inline
Definition at line 664 of file math.hpp.
References CUGIP_DECL_HYBRID, and min().
template<typename TType , int tDimension> CUGIP_DECL_HYBRID simple_vector<TType, tDimension> cugip::min_per_element (simple_vector< TType, tDimension > aVector1, const simple_vector< TType, tDimension > & aVector2) inline
Definition at line 674 of file math.hpp.
References CUGIP_DECL_HYBRID, and min().
Referenced by cugip::BorderHandlingTraits< border_handling_enum::REPEAT >::access(), get_blocked_order_access_index(), and cugip::MinFunctor::operator()().
template<typename TView > MirrorImageView<TView> cugip::mirror (TView view, simple_vector< bool, TView::kDimension > flips)
Create mirror views with fliped axes specification.
Definition at line 268 of file view_arithmetics.hpp.
References view().
template<typename TView , typename TType > void cugip::multiply (TView aView, TType aFactor)
Definition at line 63 of file arithmetics.hpp.
References for_each().
template<typename TView1 , typename TView2 > MultiplicationImageView<TView1, TView2> cugip::multiply (TView1 view1, TView2 view2)
Utility function to create MultiplicationImageView without the need to specify template parameters.
Definition at line 133 of file view_arithmetics.hpp.
template<typename TFactor , typename TView > UnaryOperatorImageView<TView, MultiplyByFactorFunctor<TFactor> > cugip::multiplyByFactor (TFactor factor, TView view)
Utility function to create multiplied view without the need to specify template parameters.
Definition at line 387 of file view_arithmetics.hpp.
References view().
template<typename TFunctor , typename TView , typename... TViews> NAryOperatorDeviceImageView<TFunctor, TView, TViews...> cugip::nAryOperator (TFunctor functor, TView view, TViews... views)
Definition at line 608 of file view_arithmetics.hpp.
References view().
template<typename TInImageView , typename TOutImageView , typename TParameters > void cugip::nonlocal_means (TInImageView aIn, TOutImageView aOut, TParameters aParameters)
Definition at line 244 of file nonlocal_means.hpp.
References D_PRINT, and cugip::AggregatingTimerSet< tTimerCount, TId >::start().
template<typename TFactor , typename TElement , int tDimension> CUGIP_DECL_HYBRID symmetric_tensor< decltype(std::declval<TFactor>) * std::declval<TElement>)), tDimension> cugip::operator* (const TFactor & aFactor, const symmetric_tensor< TElement, tDimension > & aArg) inline
Definition at line 133 of file symmetric_tensor.hpp.
References CUGIP_DECL_HYBRID.
Referenced by operator*().
template<typename TFactor , typename TElement , int tDimension> CUGIP_DECL_HYBRID symmetric_tensor< decltype(std::declval<TFactor>) * std::declval<TElement>)), tDimension> cugip::operator* (const symmetric_tensor< TElement, tDimension > & aArg, const TFactor & aFactor) inline
Definition at line 150 of file symmetric_tensor.hpp.
References operator*().
template<typename TType > std::ostream& cugip::operator<< (std::ostream & s, const device_base_ptr< TType > & aPtr)
Definition at line 34 of file memory.hpp.
template<int... tValues> std::ostream& cugip::operator<< (std::ostream & stream, const IntSequence< tValues... > &)
Definition at line 132 of file static_int_sequence.hpp.
template<typename TView > PaddedImageView<TView> cugip::padView (TView view, simple_vector< int, dimension< TView >::value > size, simple_vector< int, dimension< TView >::value > offset, typename TView::value_type fill_value)
Create padded view.
Definition at line 314 of file view_arithmetics.hpp.
References view().
template<int tDimension> simple_vector<int, tDimension> cugip::pitchedPtrToStrides (int bytes, cudaPitchedPtr pitched_ptr)
Convert cuda pitched pointer to element based strides.
Parameters
bytes Size of element in bytes.
pitched_ptr Actual pitched pointer.
Referenced by makeCudaExtent().
template<> Int2 cugip::pitchedPtrToStrides< 2 > (int bytes, cudaPitchedPtr pitched_ptr) inline
Definition at line 34 of file cuda_utils.hpp.
template<> Int3 cugip::pitchedPtrToStrides< 3 > (int bytes, cudaPitchedPtr pitched_ptr) inline
Definition at line 40 of file cuda_utils.hpp.
template<typename TGraph > CUGIP_DECL_DEVICE void cugip::printTile (const Tile< TGraph > & aTile)
Definition at line 321 of file graph_cut_relabeling.hpp.
References cugip::Tile< TGraph >::listLength, cugip::Tile< TGraph >::listProgress, cugip::Tile< TGraph >::listStart, cugip::Tile< TGraph >::progress, and cugip::Tile< TGraph >::vertexId.
CUGIP_DECL_DEVICE void cugip::printWorkLimits (const WorkLimits & aLimits) inline
Definition at line 349 of file graph_cut_relabeling.hpp.
References cugip::WorkLimits::elements, cugip::WorkLimits::guardedElements, cugip::WorkLimits::guardedOffset, cugip::WorkLimits::offset, and cugip::WorkLimits::outOfBounds.
template<typename TMatrix1 , typename TMatrix2 > CUGIP_DECL_HYBRID std::enable_if< static_matrix_traits<TMatrix1>::is_matrix && static_matrix_traits<TMatrix2>::is_matrix, matrix< decltype(std::declval<typename static_matrix_traits<TMatrix1>::element_type>) * std::declval<typename static_matrix_traits<TMatrix1>::element_type>)), static_matrix_traits<TMatrix1>::row_count, static_matrix_traits<TMatrix2>::col_count> >::type cugip::product (const TMatrix1 & aMatrix1, const TMatrix1 & aMatrix2)
Definition at line 176 of file matrix.hpp.
References CUGIP_DECL_HYBRID.
Referenced by elementCount(), isEmpty(), matrix_from_eigen_vectors_and_values(), cugip::apply_diffusion_tensor_ftor::operator()(), cugip::ReactionDiffusionRule::operator()(), cugip::host_image< TElement, tDim >::reallocate(), cugip::device_linear_access_view< TImageView >::size(), and cugip::host_linear_access_view< TImageView >::size().
template<typename TMatrix , typename TVector > CUGIP_DECL_HYBRID std::enable_if< static_matrix_traits<TMatrix>::is_matrix && static_vector_traits<TVector>::is_vector, simple_vector< decltype(std::declval<typename static_matrix_traits<TMatrix>::element_type>) * std::declval<typename static_vector_traits<TVector>::element_type>)), static_matrix_traits<TMatrix>::row_count> >::type cugip::product (const TMatrix & aMatrix, const TVector & aVector)
Definition at line 201 of file matrix.hpp.
template<typename TType , int tDimension> CUGIP_DECL_HYBRID TType cugip::product (const simple_vector< TType, tDimension > & aVector)
Returns
All vector elements product
Definition at line 728 of file math.hpp.
References CUGIP_DECL_HYBRID.
template<typename TType > CUGIP_DECL_HYBRID std::enable_if<std::is_fundamental<TType>::value, TType>::type cugip::product (const TType & aValue)
Definition at line 739 of file math.hpp.
References CUGIP_DECL_HYBRID.
template<typename TGraph , typename TPolicy > CUGIP_DECL_DEVICE void cugip::propagateFromVertex (int vertex, ParallelQueueView< int > & aVertices, TGraph & aGraph, int aCurrentLevel, const TPolicy & aPolicy)
Definition at line 86 of file graph_cut_relabeling.hpp.
References cugip::ParallelQueueView< TType >::append(), and CUGIP_DECL_DEVICE.
template<typename TGraph , typename TPolicy > CUGIP_DECL_DEVICE void cugip::propagateFromVertex2 (int vertex, const int * aStartEnd, ParallelQueueView< int > & aVertices, TGraph & aGraph, int aCurrentLevel, const TPolicy & aPolicy)
Definition at line 116 of file graph_cut_relabeling.hpp.
References cugip::ParallelQueueView< TType >::append().
template<typename TFlow > CUGIP_DECL_DEVICE void cugip::pushImplementation (GraphCutData< TFlow > & aGraph, ParallelQueueView< int > & aVertices, int index, int aCurrentLevel, device_flag_view & aPushSuccessfulFlag)
Definition at line 162 of file graph_cut_push.hpp.
References cugip::GraphCutData< TFlow >::connectionIndex(), cugip::GraphCutData< TFlow >::connectionSide(), CUGIP_ASSERT, CUGIP_GLOBAL, cugip::GraphCutData< TFlow >::excess(), cugip::GraphCutData< TFlow >::firstNeighborIndex(), cugip::ParallelQueueView< TType >::get_device(), cugip::GraphCutData< TFlow >::label(), cugip::GraphCutData< TFlow >::neighborCount(), cugip::GraphCutData< TFlow >::secondVertex(), cugip::device_flag_view::set_device(), and tryPullPush().
Referenced by pushKernel(), pushKernelMultiLevel(), and pushKernelMultiLevelGlobalSync().
template<typename TGraph , typename TPolicy > CUGIP_GLOBAL void cugip::pushKernel (TGraph aGraph, ParallelQueueView< int > aVertices, int aLevelStart, int aLevelEnd, int aCurrentLevel, device_flag_view aPushSuccessfulFlag)
Definition at line 238 of file graph_cut_push.hpp.
References CUGIP_GLOBAL, and pushImplementation().
template<typename TGraph > CUGIP_GLOBAL void cugip::pushKernel2 (TGraph aGraph, ParallelQueueView< int > aVertices, int * aLevelStarts, int aLevelCount, device_flag_view aPushSuccessfulFlag)
Definition at line 323 of file graph_cut_push.hpp.
template<typename TGraph , typename TPolicy > CUGIP_GLOBAL void cugip::pushKernelMultiLevel (TGraph aGraph, ParallelQueueView< int > aVertices, int * aLevelStarts, int aLevelCount, int aCurrentLevel, device_ptr< int > aLastProcessedLevel, device_flag_view aPushSuccessfulFlag)
Definition at line 257 of file graph_cut_push.hpp.
References CUGIP_GLOBAL, and pushImplementation().
template<typename TGraph , typename TPolicy > CUGIP_GLOBAL void cugip::pushKernelMultiLevelGlobalSync (TGraph aGraph, ParallelQueueView< int > aVertices, int * aLevelStarts, int aLevelCount, int aCurrentLevel, device_ptr< int > aLastProcessedLevel, device_flag_view aPushSuccessfulFlag, cub::GridBarrier barrier)
Definition at line 287 of file graph_cut_push.hpp.
References CUGIP_GLOBAL, and pushImplementation().
template<typename TFlow > CUGIP_GLOBAL void cugip::pushThroughTLinksFromSourceKernel (GraphCutData< TFlow > aGraph)
Definition at line 11 of file graph_cut_push.hpp.
References CUGIP_GLOBAL, cugip::GraphCutData< TFlow >::excess(), cugip::GraphCutData< TFlow >::sourceTLinkCapacity(), and cugip::GraphCutData< TFlow >::vertexCount().
template<typename TFlow > CUGIP_GLOBAL void cugip::pushThroughTLinksToSinkKernel (GraphCutData< TFlow > aGraph)
Todo:
handle situation when sink capacity isn't enough
Definition at line 28 of file graph_cut_push.hpp.
References CUGIP_DECL_DEVICE, cugip::GraphCutData< TFlow >::excess(), cugip::GraphCutData< TFlow >::sinkFlow(), cugip::GraphCutData< TFlow >::sinkTLinkCapacity(), and cugip::GraphCutData< TFlow >::vertexCount().
template<int tDimension> CUGIP_HD_WARNING_DISABLE CUGIP_DECL_HYBRID auto cugip::region_linear_access (const region< tDimension > & aRegion, int aIdx) -> simple_vector<int, tDimension>
Definition at line 34 of file region.hpp.
template<typename TGraphData , typename TPolicy > CUGIP_GLOBAL void cugip::relabel_compute_dynamic (TGraphData aGraph, ParallelQueueView< int > aVertexQueue, ParallelQueueView< int > aLevelStarts, TPolicy aPolicy)
Definition at line 823 of file graph_cut_relabeling.hpp.
References cugip::ParallelQueueView< TType >::back(), cugip::ParallelQueueView< TType >::clear_device(), cugip::ParallelQueueView< TType >::push_back(), and cugip::ParallelQueueView< TType >::size().
template<typename TImageView , typename TIdImageView , typename TUnionFind > void cugip::scan_image_for_wshed_path (TImageView aImageView, TIdImageView aIdImageView, TUnionFind aUnionFind, device_flag_view aUpdatedFlag)
Definition at line 437 of file watershed_transformation.hpp.
Referenced by watershed_transformation1().
template<typename TInputView , typename TOutputView , typename TTmpView , typename TKernel > void cugip::separable_convolution (TInputView aInView, TOutputView aOutView, TTmpView aTmpView, TKernel aKernel)
Definition at line 205 of file convolution.hpp.
Referenced by blur_structural_tensor().
template<int tDimension> convolution_kernel<simple_vector<float, tDimension>, typename FillStaticSize<tDimension, 3>::Type> cugip::sobel_gradient_kernel ()
Definition at line 69 of file convolution.hpp.
References for_each_neighbor(), cugip::convolution_kernel< TType, TSizeTraits >::get(), cugip::convolution_kernel< TType, TSizeTraits >::offset, and to_vector().
template<typename TCoordType , int tDim> CUGIP_DECL_HYBRID void cugip::sort (simple_vector< TCoordType, tDim > & aVector) inline
Todo:
check performance
Definition at line 746 of file math.hpp.
References CUGIP_DECL_HYBRID.
uint64_t cugip::splitBy3 (unsigned int a) inline
Definition at line 143 of file access_utils.hpp.
References CUGIP_DECL_HYBRID.
Referenced by get_zorder_access_index().
template<typename TType > CUGIP_DECL_HYBRID TType cugip::sqr (TType aValue) inline
Definition at line 616 of file math.hpp.
References CUGIP_DECL_HYBRID.
Referenced by eigen_values(), eigen_vector(), eigen_vectors(), cugip::ReactionDiffusionRule::f(), find_orthonormal(), cugip::ReactionDiffusionRule::g(), gaussian_kernel(), and cugip::compute_diffusion_tensor_ftor::operator()().
template<typename TView > UnaryOperatorImageView<TView, SquareFunctor> cugip::square (TView view)
Creates view which returns squared values from the original view.
Definition at line 366 of file view_arithmetics.hpp.
References view().
template<typename TView > UnaryOperatorImageView<TView, SquareRootFunctor> cugip::squareRoot (TView view)
Creates view which returns square root of the values from the original view.
Definition at line 379 of file view_arithmetics.hpp.
References view().
template<typename TImageView , typename TIdImageView > void cugip::step1 (TImageView aImageView, TIdImageView aIdImageView)
Definition at line 124 of file watershed_transformation.hpp.
Referenced by watershed_transformation().
template<typename TImageView , typename TIdImageView > void cugip::step2 (TImageView aImageView, TIdImageView aIdImageView)
Definition at line 131 of file watershed_transformation.hpp.
Referenced by watershed_transformation().
template<typename TImageView , typename TIdImageView > void cugip::step3 (TImageView aImageView, TIdImageView aIdImageView)
Definition at line 138 of file watershed_transformation.hpp.
Referenced by watershed_transformation().
template<typename TImageView , typename TIdImageView > void cugip::step4 (TImageView aImageView, TIdImageView aIdImageView)
Definition at line 145 of file watershed_transformation.hpp.
Referenced by watershed_transformation().
CUGIP_DECL_HYBRID Int2 cugip::stridesFromSize (Int2 size) inline
Returns
Strides for memory without padding.
Definition at line 16 of file access_utils.hpp.
References CUGIP_DECL_HYBRID.
Referenced by makeConstDeviceImageView(), makeConstHostImageView(), makeDeviceImageView(), makeHostImageView(), and cugip::host_image< TElement, tDim >::reallocate().
CUGIP_DECL_HYBRID Int3 cugip::stridesFromSize (Int3 size) inline
Returns
Strides for memory without padding.
Definition at line 23 of file access_utils.hpp.
References CUGIP_DECL_HYBRID.
CUGIP_DECL_HYBRID int cugip::stridesFromSize (int size) inline
Returns
Strides for memory without padding.
Definition at line 29 of file access_utils.hpp.
References CUGIP_DECL_HYBRID, and CUGIP_HD_WARNING_DISABLE.
template<typename TElement > cudaPitchedPtr cugip::stridesToPitchedPtr (TElement * ptr, Int2 size, Int2 strides) inline
Convert element based strides to cuda pitched pointer.
Parameters
ptr Data pointer
size Size of image buffer
Definition at line 49 of file cuda_utils.hpp.
References CUGIP_ASSERT.
Referenced by copyDeviceToHostAsync(), and copyHostToDeviceAsync().
template<typename TElement > cudaPitchedPtr cugip::stridesToPitchedPtr (TElement * ptr, Int3 size, Int3 strides) inline
Definition at line 56 of file cuda_utils.hpp.
References CUGIP_ASSERT, CUGIP_DECL_DEVICE, and mapBlockIdxAndThreadIdxToViewCoordinates().
template<typename TArg1View , typename TArg21View > void cugip::subtract (TArg1View aArg1View, TArg21View aArg2View)
Definition at line 35 of file arithmetics.hpp.
References CUGIP_ASSERT, and CUGIP_DECL_HYBRID.
template<typename TView1 , typename TView2 > LinearCombinationImageView<int, TView1, int, TView2> cugip::subtract (TView1 view1, TView2 view2)
Utility function wrapping two image subtraction.
Todo:
(johny) - possible more efficient implementation
Definition at line 96 of file view_arithmetics.hpp.
template<typename TType , int tDimension> CUGIP_DECL_HYBRID TType cugip::sum (const simple_vector< TType, tDimension > & aVector) inline
Definition at line 693 of file math.hpp.
References CUGIP_DECL_HYBRID.
Referenced by gaussian_kernel(), cugip::ConwayRule::operator()(), and cugip::CheckerBoardImageView< TElement, tDimension >::operator[]().
CUGIP_DECL_DEVICE int cugip::threadOrderFromIndex () inline
Definition at line 107 of file cuda_utils.hpp.
References CUGIP_DECL_DEVICE.
template<typename TInView , typename TOutView > void cugip::threshold_masking (TInView aInView, TOutView aOutView, typename TInView::value_type aThreshold, typename TOutView::value_type aMaskValue, typename TOutView::value_type aNonMaskValue = 0)
Definition at line 35 of file thresholding.hpp.
References transform().
template<int... tSize> CUGIP_DECL_HYBRID simple_vector<int, sizeof...(tSize)> cugip::to_vector (IntSequence< tSize... >)
Todo:
make constexpr
Definition at line 169 of file static_int_sequence.hpp.
Referenced by cugip::convolution_kernel< simple_vector< float, tDimension >, typename FillStaticSize< tDimension, 3 >::Type >::get(), kernel_hidden_updates(), cugip::convolution_kernel< simple_vector< float, tDimension >, typename FillStaticSize< tDimension, 3 >::Type >::size(), and sobel_gradient_kernel().
template<typename TFlow > CUGIP_DECL_DEVICE TFlow cugip::tryPull (GraphCutData< TFlow > & aGraph, int aFrom, int aTo, TFlow aCapacity)
Definition at line 98 of file graph_cut_push.hpp.
References CUGIP_DECL_DEVICE, cugip::GraphCutData< TFlow >::excess(), and min().
Referenced by tryPullPush().
template<typename TFlow > CUGIP_DECL_DEVICE bool cugip::tryPullPush (GraphCutData< TFlow > & aGraph, int aFrom, int aTo, int aConnectionIndex, bool aConnectionSide)
Definition at line 118 of file graph_cut_push.hpp.
References CUGIP_DECL_DEVICE, cugip::GraphCutData< TFlow >::excess(), cugip::EdgeResidualsRecord< TFlow >::getResidual(), cugip::GraphCutData< TFlow >::residuals(), and tryPull().
Referenced by pushImplementation().
template<typename TFunctor , typename TView > UnaryOperatorImageView<TView, TFunctor> cugip::unaryOperator (TView view, TFunctor functor)
Definition at line 432 of file view_arithmetics.hpp.
References view().
template<typename TFunctor , typename TView > UnaryOperatorOnLocatorImageView<TView, TFunctor> cugip::unaryOperatorOnLocator (TView view, TFunctor functor)
Definition at line 522 of file view_arithmetics.hpp.
References view().
template<typename TFunctor , typename TView > UnaryOperatorOnPositionImageView<TView, TFunctor> cugip::unaryOperatorOnPosition (TView view, TFunctor functor)
Definition at line 476 of file view_arithmetics.hpp.
References view().
template<typename TType , typename TView > UnaryOperatorImageView<TView, UpperLimitFunctor<TType> > cugip::upperLimit (TType limit, TView view)
Returns view returning values from the original view with values bigger then limit replaced by the limit.
Definition at line 418 of file view_arithmetics.hpp.
References view().
template<typename TType , typename TView > UnaryOperatorImageView<TView, UpperLimitReplacementFunctor<TType> > cugip::upperLimit (TType limit, TType replacement, TView view)
Returns view returning values from the original view with values bigger then limit replaced by the specified replacement.
Definition at line 426 of file view_arithmetics.hpp.
References view().
template<typename TView > CUGIP_HD_WARNING_DISABLE CUGIP_DECL_HYBRID region<dimension<TView>::value> cugip::valid_region (const TView & view)
Definition at line 71 of file view_declaration_utils.hpp.
References CUGIP_DECL_HYBRID, and CUGIP_HD_WARNING_DISABLE.
Referenced by cugip::BorderHandlingTraits< border_handling_enum::REPEAT >::access(), cugip::BorderHandlingTraits< border_handling_enum::ZERO >::access(), and valid_region().
template<typename TElement > host_image_view<TElement, 3> cugip::view (itk::Image< TElement, 3 > & aImage)
Definition at line 10 of file itk_utils.hpp.
template<typename TImage > TImage::view_t cugip::view (TImage & aImage)
Definition at line 114 of file image.hpp.
Referenced by abs_view(), addValue(), bordered_subview(), cugip::texture_image< TElement, tDim >::const_view(), cugip::CellularAutomatonBaseCRTP< AsyncCellularAutomatonWithGlobalState< TGrid, TNeighborhood, TRule, TGlobalState, TSemiGlobalState >, TRule, device_image< TGrid::Element, TGrid::cDimension >, 2 >::currentOutputView(), getDimension(), cugip::CellularAutomatonBaseCRTP< AsyncCellularAutomatonWithGlobalState< TGrid, TNeighborhood, TRule, TGlobalState, TSemiGlobalState >, TRule, device_image< TGrid::Element, TGrid::cDimension >, 2 >::initialize(), cugip::coherence_enhancing_diffusion< tDimension >::iteration(), lowerLimit(), mirror(), multiplyByFactor(), nAryOperator(), padView(), slice(), square(), squareRoot(), subview(), unaryOperator(), unaryOperatorOnLocator(), unaryOperatorOnPosition(), upperLimit(), and zipViews().
template<typename TElement > host_image_view<TElement, 2> cugip::view (itk::Image< TElement, 2 > & aImage)
Definition at line 22 of file itk_utils.hpp.
template<typename TElement , int tDim> texture_image<TElement, tDim>::view_t cugip::view (texture_image< TElement, tDim > & aImage)
Definition at line 102 of file texture.hpp.
References cugip::texture_image< TElement, tDim >::view().
template<typename TElement , int tDim> host_image<TElement, tDim>::view_t cugip::view (host_image< TElement, tDim > & aImage)
Definition at line 116 of file host_image.hpp.
References cugip::host_image< TElement, tDim >::view().
template<typename TType > device_memory_1d<TType> cugip::view (const device_memory_1d_owner< TType > & aBuffer)
Definition at line 1120 of file memory.hpp.
template<typename TImageView , typename TIdImageView , typename TDistanceView > void cugip::watershed_evolution (TImageView aImageView, TIdImageView aIdImageView, TIdImageView aTmpIdImageView, TDistanceView aDistanceView1, TDistanceView aDistanceView2, device_flag_view aUpdateFlag)
Definition at line 239 of file watershed_transformation.hpp.
Referenced by watershed_transformation2().
template<typename TImageView , typename TIdImageView , typename TDistanceView > CUGIP_GLOBAL void cugip::watershed_evolution_kernel (TImageView aImageView, TIdImageView aIdImageView, TIdImageView aTmpIdImageView, TDistanceView aDistanceView1, TDistanceView aDistanceView2, device_flag_view aUpdateFlag)
Definition at line 189 of file watershed_transformation.hpp.
References max(), and cugip::device_flag_view::set_device().
template<typename TImageView , typename TIdImageView > void cugip::watershed_transformation (TImageView aImageView, TIdImageView aIdImageView, TIdImageView aTmpIdImageView)
Definition at line 153 of file watershed_transformation.hpp.
References step1(), step2(), step3(), and step4().
template<typename TImageView , typename TIdImageView , typename TUnionFind > void cugip::watershed_transformation1 (TImageView aImageView, TIdImageView aIdImageView, TUnionFind aUnionFind)
Definition at line 452 of file watershed_transformation.hpp.
References cugip::device_flag_view::check_host(), connected_component_labeling(), D_PRINT, filter(), init_watershed_from_plateaus_labels(), cugip::device_flag_view::reset_host(), scan_image_for_wshed_path(), and cugip::device_flag::view().
template<typename TImageView , typename TIdImageView , typename TDistanceView > void cugip::watershed_transformation2 (TImageView aImageView, TIdImageView aIdImageView, TIdImageView aTmpIdImageView, TDistanceView aDistanceView1, TDistanceView aDistanceView2)
Todo:
handle copying after last iteration
Definition at line 262 of file watershed_transformation.hpp.
References cugip::device_flag_view::check_host(), D_PRINT, init_watershed_buffers(), cugip::device_flag_view::reset_host(), cugip::device_flag::view(), and watershed_evolution().
template<typename TView , typename... TViews> NAryOperatorDeviceImageView<ZipValues, TView, TViews...> cugip::zipViews (TView view, TViews... views)
Definition at line 614 of file view_arithmetics.hpp.
References view().