var namespacecugip =
[
    [ "AbsFunctor", "structcugip_1_1_abs_functor.html", "structcugip_1_1_abs_functor" ],
    [ "AccessDimensionImageView", "classcugip_1_1_access_dimension_image_view.html", "classcugip_1_1_access_dimension_image_view" ],
    [ "AddValueFunctor", "structcugip_1_1_add_value_functor.html", "structcugip_1_1_add_value_functor" ],
    [ "AggregatingTimerSet", "classcugip_1_1_aggregating_timer_set.html", "classcugip_1_1_aggregating_timer_set" ],
    [ "apply_diffusion_tensor_ftor", "structcugip_1_1apply__diffusion__tensor__ftor.html", "structcugip_1_1apply__diffusion__tensor__ftor" ],
    [ "assign_color_ftor", "structcugip_1_1assign__color__ftor.html", "structcugip_1_1assign__color__ftor" ],
    [ "assign_masked_id_functor", "structcugip_1_1assign__masked__id__functor.html", "structcugip_1_1assign__masked__id__functor" ],
    [ "AsyncCellOperationWithGlobalState", "structcugip_1_1_async_cell_operation_with_global_state.html", "structcugip_1_1_async_cell_operation_with_global_state" ],
    [ "AsyncCellularAutomatonWithGlobalState", "classcugip_1_1_async_cellular_automaton_with_global_state.html", "classcugip_1_1_async_cellular_automaton_with_global_state" ],
    [ "AsyncCellularAutomatonWithGlobalStateAndPointer", "classcugip_1_1_async_cellular_automaton_with_global_state_and_pointer.html", "classcugip_1_1_async_cellular_automaton_with_global_state_and_pointer" ],
    [ "BinaryOperatorDeviceImageView", "classcugip_1_1_binary_operator_device_image_view.html", "classcugip_1_1_binary_operator_device_image_view" ],
    [ "BlockedAccessIndex", "structcugip_1_1_blocked_access_index.html", "structcugip_1_1_blocked_access_index" ],
    [ "bordered_subimage_view", "classcugip_1_1bordered__subimage__view.html", null ],
    [ "bordered_subimage_view< TView, false >", "classcugip_1_1bordered__subimage__view_3_01_t_view_00_01false_01_4.html", "classcugip_1_1bordered__subimage__view_3_01_t_view_00_01false_01_4" ],
    [ "BorderHandlingTraits", "structcugip_1_1_border_handling_traits.html", "structcugip_1_1_border_handling_traits" ],
    [ "BorderHandlingTraits< border_handling_enum::MIRROR >", "structcugip_1_1_border_handling_traits_3_01border__handling__enum_1_1_m_i_r_r_o_r_01_4.html", "structcugip_1_1_border_handling_traits_3_01border__handling__enum_1_1_m_i_r_r_o_r_01_4" ],
    [ "BorderHandlingTraits< border_handling_enum::REPEAT >", "structcugip_1_1_border_handling_traits_3_01border__handling__enum_1_1_r_e_p_e_a_t_01_4.html", "structcugip_1_1_border_handling_traits_3_01border__handling__enum_1_1_r_e_p_e_a_t_01_4" ],
    [ "BorderHandlingTraits< border_handling_enum::ZERO >", "structcugip_1_1_border_handling_traits_3_01border__handling__enum_1_1_z_e_r_o_01_4.html", "structcugip_1_1_border_handling_traits_3_01border__handling__enum_1_1_z_e_r_o_01_4" ],
    [ "CellOperation", "structcugip_1_1_cell_operation.html", "structcugip_1_1_cell_operation" ],
    [ "CellOperationWithGlobalState", "structcugip_1_1_cell_operation_with_global_state.html", "structcugip_1_1_cell_operation_with_global_state" ],
    [ "CellularAutomaton", "classcugip_1_1_cellular_automaton.html", "classcugip_1_1_cellular_automaton" ],
    [ "CellularAutomatonBaseCRTP", "classcugip_1_1_cellular_automaton_base_c_r_t_p.html", "classcugip_1_1_cellular_automaton_base_c_r_t_p" ],
    [ "CellularAutomatonWithGlobalState", "classcugip_1_1_cellular_automaton_with_global_state.html", "classcugip_1_1_cellular_automaton_with_global_state" ],
    [ "ChannelSumFunctor", "structcugip_1_1_channel_sum_functor.html", "structcugip_1_1_channel_sum_functor" ],
    [ "CheckerBoardImageView", "classcugip_1_1_checker_board_image_view.html", "classcugip_1_1_checker_board_image_view" ],
    [ "Choose", "structcugip_1_1_choose.html", null ],
    [ "Choose< 0, H, T... >", "structcugip_1_1_choose_3_010_00_01_h_00_01_t_8_8_8_01_4.html", null ],
    [ "Choose< N, H, T... >", "structcugip_1_1_choose_3_01_n_00_01_h_00_01_t_8_8_8_01_4.html", null ],
    [ "clear_nonminima_plateaus_ftor", "structcugip_1_1clear__nonminima__plateaus__ftor.html", "structcugip_1_1clear__nonminima__plateaus__ftor" ],
    [ "coherence_enhancing_diffusion", "classcugip_1_1coherence__enhancing__diffusion.html", "classcugip_1_1coherence__enhancing__diffusion" ],
    [ "column_accessor", "classcugip_1_1column__accessor.html", "classcugip_1_1column__accessor" ],
    [ "compute_diffusion_tensor_ftor", "structcugip_1_1compute__diffusion__tensor__ftor.html", "structcugip_1_1compute__diffusion__tensor__ftor" ],
    [ "compute_structural_tensor_ftor", "structcugip_1_1compute__structural__tensor__ftor.html", "structcugip_1_1compute__structural__tensor__ftor" ],
    [ "ConnectedComponentLabelingRule", "structcugip_1_1_connected_component_labeling_rule.html", "structcugip_1_1_connected_component_labeling_rule" ],
    [ "ConnectedComponentLabelingRule2", "structcugip_1_1_connected_component_labeling_rule2.html", "structcugip_1_1_connected_component_labeling_rule2" ],
    [ "const_device_image_view", "classcugip_1_1const__device__image__view.html", "classcugip_1_1const__device__image__view" ],
    [ "const_device_memory_1d", "structcugip_1_1const__device__memory__1d.html", "structcugip_1_1const__device__memory__1d" ],
    [ "const_device_memory_2d", "structcugip_1_1const__device__memory__2d.html", "structcugip_1_1const__device__memory__2d" ],
    [ "const_device_memory_3d", "structcugip_1_1const__device__memory__3d.html", "structcugip_1_1const__device__memory__3d" ],
    [ "const_device_ptr", "structcugip_1_1const__device__ptr.html", "structcugip_1_1const__device__ptr" ],
    [ "const_host_image_view", "classcugip_1_1const__host__image__view.html", "classcugip_1_1const__host__image__view" ],
    [ "const_host_memory_1d", "structcugip_1_1const__host__memory__1d.html", "structcugip_1_1const__host__memory__1d" ],
    [ "const_host_memory_2d", "structcugip_1_1const__host__memory__2d.html", "structcugip_1_1const__host__memory__2d" ],
    [ "const_host_memory_3d", "structcugip_1_1const__host__memory__3d.html", "structcugip_1_1const__host__memory__3d" ],
    [ "const_memory_view", "classcugip_1_1const__memory__view.html", "classcugip_1_1const__memory__view" ],
    [ "ConstantDeviceImageView", "classcugip_1_1_constant_device_image_view.html", "classcugip_1_1_constant_device_image_view" ],
    [ "convert_float_and_byte", "structcugip_1_1convert__float__and__byte.html", "structcugip_1_1convert__float__and__byte" ],
    [ "convolution_kernel", "structcugip_1_1convolution__kernel.html", "structcugip_1_1convolution__kernel" ],
    [ "convolution_kernel< TType, StaticSize< tSize > >", "structcugip_1_1convolution__kernel_3_01_t_type_00_01_static_size_3_01t_size_01_4_01_4.html", "structcugip_1_1convolution__kernel_3_01_t_type_00_01_static_size_3_01t_size_01_4_01_4" ],
    [ "convolution_operator", "structcugip_1_1convolution__operator.html", "structcugip_1_1convolution__operator" ],
    [ "ConwayRule", "structcugip_1_1_conway_rule.html", "structcugip_1_1_conway_rule" ],
    [ "CopyDirectionTag", "structcugip_1_1_copy_direction_tag.html", null ],
    [ "DefaultForEachPolicy", "structcugip_1_1_default_for_each_policy.html", null ],
    [ "DefaultTransformLocatorPolicy", "structcugip_1_1_default_transform_locator_policy.html", "structcugip_1_1_default_transform_locator_policy" ],
    [ "DefaultTransformPolicy", "structcugip_1_1_default_transform_policy.html", null ],
    [ "device_base_ptr", "structcugip_1_1device__base__ptr.html", "structcugip_1_1device__base__ptr" ],
    [ "device_flag", "structcugip_1_1device__flag.html", "structcugip_1_1device__flag" ],
    [ "device_flag_view", "structcugip_1_1device__flag__view.html", "structcugip_1_1device__flag__view" ],
    [ "device_image", "classcugip_1_1device__image.html", "classcugip_1_1device__image" ],
    [ "device_image_view", "classcugip_1_1device__image__view.html", "classcugip_1_1device__image__view" ],
    [ "device_image_view_base", "classcugip_1_1device__image__view__base.html", "classcugip_1_1device__image__view__base" ],
    [ "device_image_view_crtp", "classcugip_1_1device__image__view__crtp.html", "classcugip_1_1device__image__view__crtp" ],
    [ "device_linear_access_view", "structcugip_1_1device__linear__access__view.html", "structcugip_1_1device__linear__access__view" ],
    [ "device_memory_1d", "structcugip_1_1device__memory__1d.html", "structcugip_1_1device__memory__1d" ],
    [ "device_memory_1d_owner", "structcugip_1_1device__memory__1d__owner.html", "structcugip_1_1device__memory__1d__owner" ],
    [ "device_memory_2d", "structcugip_1_1device__memory__2d.html", "structcugip_1_1device__memory__2d" ],
    [ "device_memory_2d_owner", "structcugip_1_1device__memory__2d__owner.html", "structcugip_1_1device__memory__2d__owner" ],
    [ "device_memory_3d", "structcugip_1_1device__memory__3d.html", "structcugip_1_1device__memory__3d" ],
    [ "device_memory_3d_owner", "structcugip_1_1device__memory__3d__owner.html", "structcugip_1_1device__memory__3d__owner" ],
    [ "device_ptr", "structcugip_1_1device__ptr.html", "structcugip_1_1device__ptr" ],
    [ "device_union_find", "classcugip_1_1device__union__find.html", "classcugip_1_1device__union__find" ],
    [ "device_union_find_view", "classcugip_1_1device__union__find__view.html", "classcugip_1_1device__union__find__view" ],
    [ "DeviceFlagMixin", "structcugip_1_1_device_flag_mixin.html", "structcugip_1_1_device_flag_mixin" ],
    [ "dim_traits", "structcugip_1_1dim__traits.html", "structcugip_1_1dim__traits" ],
    [ "dim_traits< 1 >", "structcugip_1_1dim__traits_3_011_01_4.html", "structcugip_1_1dim__traits_3_011_01_4" ],
    [ "dimension", "structcugip_1_1dimension.html", null ],
    [ "dimension< const_memory_view< TElement, tDim > >", "structcugip_1_1dimension_3_01const__memory__view_3_01_t_element_00_01t_dim_01_4_01_4.html", null ],
    [ "dimension< device_image< TElement, tDim > >", "structcugip_1_1dimension_3_01device__image_3_01_t_element_00_01t_dim_01_4_01_4.html", null ],
    [ "dimension< device_image_view_base< tDim > >", "structcugip_1_1dimension_3_01device__image__view__base_3_01t_dim_01_4_01_4.html", null ],
    [ "dimension< element< TType, tDim > >", "structcugip_1_1dimension_3_01element_3_01_t_type_00_01t_dim_01_4_01_4.html", null ],
    [ "dimension< host_image< TElement, tDim > >", "structcugip_1_1dimension_3_01host__image_3_01_t_element_00_01t_dim_01_4_01_4.html", null ],
    [ "dimension< image_locator< TImageView, TBorderHandling > >", "structcugip_1_1dimension_3_01image__locator_3_01_t_image_view_00_01_t_border_handling_01_4_01_4.html", null ],
    [ "dimension< intraits_1d< tWidth > >", "structcugip_1_1dimension_3_01intraits__1d_3_01t_width_01_4_01_4.html", null ],
    [ "dimension< intraits_2d< tWidth, tHeight > >", "structcugip_1_1dimension_3_01intraits__2d_3_01t_width_00_01t_height_01_4_01_4.html", null ],
    [ "dimension< intraits_3d< tWidth, tHeight, tDepth > >", "structcugip_1_1dimension_3_01intraits__3d_3_01t_width_00_01t_height_00_01t_depth_01_4_01_4.html", null ],
    [ "dimension< memory_view< TElement, tDim > >", "structcugip_1_1dimension_3_01memory__view_3_01_t_element_00_01t_dim_01_4_01_4.html", null ],
    [ "dimension< simple_vector< TCoordinateType, tDim > >", "structcugip_1_1dimension_3_01simple__vector_3_01_t_coordinate_type_00_01t_dim_01_4_01_4.html", null ],
    [ "dimension< texture_image< TElement, tDim > >", "structcugip_1_1dimension_3_01texture__image_3_01_t_element_00_01t_dim_01_4_01_4.html", null ],
    [ "dimension_1d_tag", "structcugip_1_1dimension__1d__tag.html", null ],
    [ "dimension_2d_tag", "structcugip_1_1dimension__2d__tag.html", null ],
    [ "dimension_3d_tag", "structcugip_1_1dimension__3d__tag.html", null ],
    [ "dimension_4d_tag", "structcugip_1_1dimension__4d__tag.html", null ],
    [ "dimension_helper", "structcugip_1_1dimension__helper.html", null ],
    [ "dimension_helper< 1 >", "structcugip_1_1dimension__helper_3_011_01_4.html", "structcugip_1_1dimension__helper_3_011_01_4" ],
    [ "dimension_helper< 2 >", "structcugip_1_1dimension__helper_3_012_01_4.html", "structcugip_1_1dimension__helper_3_012_01_4" ],
    [ "dimension_helper< 3 >", "structcugip_1_1dimension__helper_3_013_01_4.html", "structcugip_1_1dimension__helper_3_013_01_4" ],
    [ "dimension_helper< 4 >", "structcugip_1_1dimension__helper_3_014_01_4.html", "structcugip_1_1dimension__helper_3_014_01_4" ],
    [ "divergence", "structcugip_1_1divergence.html", "structcugip_1_1divergence" ],
    [ "DivisionImageView", "classcugip_1_1_division_image_view.html", "classcugip_1_1_division_image_view" ],
    [ "DummyGlobalState", "structcugip_1_1_dummy_global_state.html", "structcugip_1_1_dummy_global_state" ],
    [ "DummyTraceObject", "structcugip_1_1_dummy_trace_object.html", "structcugip_1_1_dummy_trace_object" ],
    [ "DurationRecord", "structcugip_1_1_duration_record.html", "structcugip_1_1_duration_record" ],
    [ "EdgeForwardTraversable", "structcugip_1_1_edge_forward_traversable.html", "structcugip_1_1_edge_forward_traversable" ],
    [ "EdgeRecord", "structcugip_1_1_edge_record.html", "structcugip_1_1_edge_record" ],
    [ "EdgeResidualsRecord", "structcugip_1_1_edge_residuals_record.html", "structcugip_1_1_edge_residuals_record" ],
    [ "EdgeReverseTraversable", "structcugip_1_1_edge_reverse_traversable.html", "structcugip_1_1_edge_reverse_traversable" ],
    [ "element", "structcugip_1_1element.html", "structcugip_1_1element" ],
    [ "EquivalenceGlobalState", "structcugip_1_1_equivalence_global_state.html", "structcugip_1_1_equivalence_global_state" ],
    [ "EquivalenceManager", "classcugip_1_1_equivalence_manager.html", "classcugip_1_1_equivalence_manager" ],
    [ "ExceptionBase", "classcugip_1_1_exception_base.html", null ],
    [ "FillFlag", "structcugip_1_1_fill_flag.html", null ],
    [ "FillStaticSize", "structcugip_1_1_fill_static_size.html", null ],
    [ "FillStaticSize< 2, tValue >", "structcugip_1_1_fill_static_size_3_012_00_01t_value_01_4.html", "structcugip_1_1_fill_static_size_3_012_00_01t_value_01_4" ],
    [ "FillStaticSize< 3, tValue >", "structcugip_1_1_fill_static_size_3_013_00_01t_value_01_4.html", "structcugip_1_1_fill_static_size_3_013_00_01t_value_01_4" ],
    [ "fold_and", "structcugip_1_1fold__and.html", "structcugip_1_1fold__and" ],
    [ "fold_and< TBoolTrait, THead >", "structcugip_1_1fold__and_3_01_t_bool_trait_00_01_t_head_01_4.html", "structcugip_1_1fold__and_3_01_t_bool_trait_00_01_t_head_01_4" ],
    [ "generate_basins_ftor", "structcugip_1_1generate__basins__ftor.html", "structcugip_1_1generate__basins__ftor" ],
    [ "generate_spiral_ftor", "structcugip_1_1generate__spiral__ftor.html", "structcugip_1_1generate__spiral__ftor" ],
    [ "GenerateIntSequence", "structcugip_1_1_generate_int_sequence.html", "structcugip_1_1_generate_int_sequence" ],
    [ "get_neighborhood_accessor", "structcugip_1_1get__neighborhood__accessor.html", "structcugip_1_1get__neighborhood__accessor" ],
    [ "get_policy", "structcugip_1_1get__policy.html", null ],
    [ "get_policy2", "structcugip_1_1get__policy2.html", null ],
    [ "get_policy2< tIdx1, tIdx2, const matrix< TType, tRowCount, tColCount > >", "structcugip_1_1get__policy2_3_01t_idx1_00_01t_idx2_00_01const_01matrix_3_01_t_type_00_01t_row_count_00_01t_col_count_01_4_01_4.html", "structcugip_1_1get__policy2_3_01t_idx1_00_01t_idx2_00_01const_01matrix_3_01_t_type_00_01t_row_count_00_01t_col_count_01_4_01_4" ],
    [ "get_policy2< tIdx1, tIdx2, const symmetric_tensor< TType, tDimension > >", "structcugip_1_1get__policy2_3_01t_idx1_00_01t_idx2_00_01const_01symmetric__tensor_3_01_t_type_00_01t_dimension_01_4_01_4.html", "structcugip_1_1get__policy2_3_01t_idx1_00_01t_idx2_00_01const_01symmetric__tensor_3_01_t_type_00_01t_dimension_01_4_01_4" ],
    [ "get_policy2< tIdx1, tIdx2, matrix< TType, tRowCount, tColCount > >", "structcugip_1_1get__policy2_3_01t_idx1_00_01t_idx2_00_01matrix_3_01_t_type_00_01t_row_count_00_01t_col_count_01_4_01_4.html", "structcugip_1_1get__policy2_3_01t_idx1_00_01t_idx2_00_01matrix_3_01_t_type_00_01t_row_count_00_01t_col_count_01_4_01_4" ],
    [ "get_policy2< tIdx1, tIdx2, symmetric_tensor< TType, tDimension > >", "structcugip_1_1get__policy2_3_01t_idx1_00_01t_idx2_00_01symmetric__tensor_3_01_t_type_00_01t_dimension_01_4_01_4.html", "structcugip_1_1get__policy2_3_01t_idx1_00_01t_idx2_00_01symmetric__tensor_3_01_t_type_00_01t_dimension_01_4_01_4" ],
    [ "get_policy< tIdx, const simple_vector< TType, tChannelCount > >", "structcugip_1_1get__policy_3_01t_idx_00_01const_01simple__vector_3_01_t_type_00_01t_channel_count_01_4_01_4.html", "structcugip_1_1get__policy_3_01t_idx_00_01const_01simple__vector_3_01_t_type_00_01t_channel_count_01_4_01_4" ],
    [ "get_policy< tIdx, const Tuple< TType... > >", "structcugip_1_1get__policy_3_01t_idx_00_01const_01_tuple_3_01_t_type_8_8_8_01_4_01_4.html", "structcugip_1_1get__policy_3_01t_idx_00_01const_01_tuple_3_01_t_type_8_8_8_01_4_01_4" ],
    [ "get_policy< tIdx, simple_vector< TType, tChannelCount > >", "structcugip_1_1get__policy_3_01t_idx_00_01simple__vector_3_01_t_type_00_01t_channel_count_01_4_01_4.html", "structcugip_1_1get__policy_3_01t_idx_00_01simple__vector_3_01_t_type_00_01t_channel_count_01_4_01_4" ],
    [ "get_policy< tIdx, Tuple< TType... > >", "structcugip_1_1get__policy_3_01t_idx_00_01_tuple_3_01_t_type_8_8_8_01_4_01_4.html", "structcugip_1_1get__policy_3_01t_idx_00_01_tuple_3_01_t_type_8_8_8_01_4_01_4" ],
    [ "GetChannel", "structcugip_1_1_get_channel.html", "structcugip_1_1_get_channel" ],
    [ "GetCopyDirection", "structcugip_1_1_get_copy_direction.html", null ],
    [ "GetCopyDirection< false, true, true, false >", "structcugip_1_1_get_copy_direction_3_01false_00_01true_00_01true_00_01false_01_4.html", "structcugip_1_1_get_copy_direction_3_01false_00_01true_00_01true_00_01false_01_4" ],
    [ "GetCopyDirection< tFromIsDevice, true, false, true >", "structcugip_1_1_get_copy_direction_3_01t_from_is_device_00_01true_00_01false_00_01true_01_4.html", "structcugip_1_1_get_copy_direction_3_01t_from_is_device_00_01true_00_01false_00_01true_01_4" ],
    [ "GetCopyDirection< true, false, false, true >", "structcugip_1_1_get_copy_direction_3_01true_00_01false_00_01false_00_01true_01_4.html", "structcugip_1_1_get_copy_direction_3_01true_00_01false_00_01false_00_01true_01_4" ],
    [ "GetCopyDirection< true, tFromIsHost, true, false >", "structcugip_1_1_get_copy_direction_3_01true_00_01t_from_is_host_00_01true_00_01false_01_4.html", "structcugip_1_1_get_copy_direction_3_01true_00_01t_from_is_host_00_01true_00_01false_01_4" ],
    [ "GetPositionInIntSequence", "structcugip_1_1_get_position_in_int_sequence.html", "structcugip_1_1_get_position_in_int_sequence" ],
    [ "gradient_magnitude", "structcugip_1_1gradient__magnitude.html", "structcugip_1_1gradient__magnitude" ],
    [ "gradient_magnitude_symmetric_difference", "structcugip_1_1gradient__magnitude__symmetric__difference.html", "structcugip_1_1gradient__magnitude__symmetric__difference" ],
    [ "gradient_symmetric_difference", "structcugip_1_1gradient__symmetric__difference.html", "structcugip_1_1gradient__symmetric__difference" ],
    [ "Graph", "classcugip_1_1_graph.html", "classcugip_1_1_graph" ],
    [ "GraphCutData", "structcugip_1_1_graph_cut_data.html", "structcugip_1_1_graph_cut_data" ],
    [ "GraphCutPolicy", "structcugip_1_1_graph_cut_policy.html", "structcugip_1_1_graph_cut_policy" ],
    [ "GraphData", "structcugip_1_1_graph_data.html", "structcugip_1_1_graph_data" ],
    [ "grayscale_ftor", "structcugip_1_1grayscale__ftor.html", "structcugip_1_1grayscale__ftor" ],
    [ "Grid", "structcugip_1_1_grid.html", "structcugip_1_1_grid" ],
    [ "HandlePlateauBorder", "structcugip_1_1_handle_plateau_border.html", "structcugip_1_1_handle_plateau_border" ],
    [ "HasSmallerNeighbor", "structcugip_1_1_has_smaller_neighbor.html", "structcugip_1_1_has_smaller_neighbor" ],
    [ "host_image", "classcugip_1_1host__image.html", "classcugip_1_1host__image" ],
    [ "host_image_view", "classcugip_1_1host__image__view.html", "classcugip_1_1host__image__view" ],
    [ "host_image_view_base", "classcugip_1_1host__image__view__base.html", "classcugip_1_1host__image__view__base" ],
    [ "host_linear_access_view", "structcugip_1_1host__linear__access__view.html", "structcugip_1_1host__linear__access__view" ],
    [ "host_memory_1d", "structcugip_1_1host__memory__1d.html", "structcugip_1_1host__memory__1d" ],
    [ "host_memory_2d", "structcugip_1_1host__memory__2d.html", "structcugip_1_1host__memory__2d" ],
    [ "host_memory_3d", "structcugip_1_1host__memory__3d.html", "structcugip_1_1host__memory__3d" ],
    [ "Id", "structcugip_1_1_id.html", "structcugip_1_1_id" ],
    [ "image_locator", "classcugip_1_1image__locator.html", "classcugip_1_1image__locator" ],
    [ "IncompatibleViewSizes", "classcugip_1_1_incompatible_view_sizes.html", null ],
    [ "init_watershed_labels_from_plateaus_ftor", "structcugip_1_1init__watershed__labels__from__plateaus__ftor.html", "structcugip_1_1init__watershed__labels__from__plateaus__ftor" ],
    [ "init_watershed_labels_ftor", "structcugip_1_1init__watershed__labels__ftor.html", "structcugip_1_1init__watershed__labels__ftor" ],
    [ "init_wsheds_ftor", "structcugip_1_1init__wsheds__ftor.html", "structcugip_1_1init__wsheds__ftor" ],
    [ "IntervalMeasurement", "classcugip_1_1_interval_measurement.html", "classcugip_1_1_interval_measurement" ],
    [ "intraits_1d", "structcugip_1_1intraits__1d.html", "structcugip_1_1intraits__1d" ],
    [ "intraits_2d", "structcugip_1_1intraits__2d.html", "structcugip_1_1intraits__2d" ],
    [ "intraits_3d", "structcugip_1_1intraits__3d.html", "structcugip_1_1intraits__3d" ],
    [ "IntSequence", "classcugip_1_1_int_sequence.html", "classcugip_1_1_int_sequence" ],
    [ "IntValue", "structcugip_1_1_int_value.html", "structcugip_1_1_int_value" ],
    [ "is_callable", "structcugip_1_1is__callable.html", "structcugip_1_1is__callable" ],
    [ "is_device_view", "structcugip_1_1is__device__view.html", null ],
    [ "is_host_view", "structcugip_1_1is__host__view.html", null ],
    [ "is_image_view", "structcugip_1_1is__image__view.html", null ],
    [ "is_memory_based", "structcugip_1_1is__memory__based.html", null ],
    [ "is_memory_based< const_device_image_view< TElement, tDim > >", "structcugip_1_1is__memory__based_3_01const__device__image__view_3_01_t_element_00_01t_dim_01_4_01_4.html", null ],
    [ "is_memory_based< const_host_image_view< TElement, tDim > >", "structcugip_1_1is__memory__based_3_01const__host__image__view_3_01_t_element_00_01t_dim_01_4_01_4.html", null ],
    [ "is_memory_based< device_image_view< TElement, tDim > >", "structcugip_1_1is__memory__based_3_01device__image__view_3_01_t_element_00_01t_dim_01_4_01_4.html", null ],
    [ "is_memory_based< host_image_view< TElement, tDim > >", "structcugip_1_1is__memory__based_3_01host__image__view_3_01_t_element_00_01t_dim_01_4_01_4.html", null ],
    [ "is_memory_view", "structcugip_1_1is__memory__view.html", null ],
    [ "is_memory_view< const_memory_view< TElement, tDim > >", "structcugip_1_1is__memory__view_3_01const__memory__view_3_01_t_element_00_01t_dim_01_4_01_4.html", null ],
    [ "is_memory_view< memory_view< TElement, tDim > >", "structcugip_1_1is__memory__view_3_01memory__view_3_01_t_element_00_01t_dim_01_4_01_4.html", null ],
    [ "IsValueInIntSequence", "structcugip_1_1_is_value_in_int_sequence.html", "structcugip_1_1_is_value_in_int_sequence" ],
    [ "LastItemInIntSequence", "structcugip_1_1_last_item_in_int_sequence.html", "structcugip_1_1_last_item_in_int_sequence" ],
    [ "LinearAccessIndex", "structcugip_1_1_linear_access_index.html", "structcugip_1_1_linear_access_index" ],
    [ "LinearCombinationImageView", "classcugip_1_1_linear_combination_image_view.html", "classcugip_1_1_linear_combination_image_view" ],
    [ "local_minima_detection_ftor", "structcugip_1_1local__minima__detection__ftor.html", "structcugip_1_1local__minima__detection__ftor" ],
    [ "LocalMinimaConnectedComponentRule", "structcugip_1_1_local_minima_connected_component_rule.html", "structcugip_1_1_local_minima_connected_component_rule" ],
    [ "LocalMinimaEquivalenceGlobalState", "structcugip_1_1_local_minima_equivalence_global_state.html", "structcugip_1_1_local_minima_equivalence_global_state" ],
    [ "LocalMinimumLabel", "structcugip_1_1_local_minimum_label.html", "structcugip_1_1_local_minimum_label" ],
    [ "LowerLimitFunctor", "structcugip_1_1_lower_limit_functor.html", "structcugip_1_1_lower_limit_functor" ],
    [ "LowerLimitReplacementFunctor", "structcugip_1_1_lower_limit_replacement_functor.html", "structcugip_1_1_lower_limit_replacement_functor" ],
    [ "mandelbrot_ftor", "structcugip_1_1mandelbrot__ftor.html", "structcugip_1_1mandelbrot__ftor" ],
    [ "MaskedImageView", "classcugip_1_1_masked_image_view.html", "classcugip_1_1_masked_image_view" ],
    [ "matrix", "classcugip_1_1matrix.html", "classcugip_1_1matrix" ],
    [ "MaxFunctor", "structcugip_1_1_max_functor.html", "structcugip_1_1_max_functor" ],
    [ "memory_management", "structcugip_1_1memory__management.html", null ],
    [ "memory_management< TElement, 1 >", "structcugip_1_1memory__management_3_01_t_element_00_011_01_4.html", "structcugip_1_1memory__management_3_01_t_element_00_011_01_4" ],
    [ "memory_management< TElement, 2 >", "structcugip_1_1memory__management_3_01_t_element_00_012_01_4.html", "structcugip_1_1memory__management_3_01_t_element_00_012_01_4" ],
    [ "memory_management< TElement, 3 >", "structcugip_1_1memory__management_3_01_t_element_00_013_01_4.html", "structcugip_1_1memory__management_3_01_t_element_00_013_01_4" ],
    [ "memory_view", "classcugip_1_1memory__view.html", "classcugip_1_1memory__view" ],
    [ "MeshGridView", "classcugip_1_1_mesh_grid_view.html", "classcugip_1_1_mesh_grid_view" ],
    [ "MinCut", "structcugip_1_1_min_cut.html", "structcugip_1_1_min_cut" ],
    [ "MinFunctor", "structcugip_1_1_min_functor.html", "structcugip_1_1_min_functor" ],
    [ "MinimalGraphCutComputation", "classcugip_1_1_minimal_graph_cut_computation.html", "classcugip_1_1_minimal_graph_cut_computation" ],
    [ "MirrorImageView", "classcugip_1_1_mirror_image_view.html", "classcugip_1_1_mirror_image_view" ],
    [ "MooreNeighborhood", "structcugip_1_1_moore_neighborhood.html", null ],
    [ "MooreNeighborhood< 2 >", "structcugip_1_1_moore_neighborhood_3_012_01_4.html", "structcugip_1_1_moore_neighborhood_3_012_01_4" ],
    [ "MooreNeighborhood< 3 >", "structcugip_1_1_moore_neighborhood_3_013_01_4.html", "structcugip_1_1_moore_neighborhood_3_013_01_4" ],
    [ "MultiIntervalMeasurement", "classcugip_1_1_multi_interval_measurement.html", "classcugip_1_1_multi_interval_measurement" ],
    [ "MultiplicationImageView", "classcugip_1_1_multiplication_image_view.html", "classcugip_1_1_multiplication_image_view" ],
    [ "MultiplyByFactorFunctor", "structcugip_1_1_multiply_by_factor_functor.html", "structcugip_1_1_multiply_by_factor_functor" ],
    [ "MultiViewTraits", "structcugip_1_1_multi_view_traits.html", "structcugip_1_1_multi_view_traits" ],
    [ "NaiveSweepPass", "structcugip_1_1_naive_sweep_pass.html", "structcugip_1_1_naive_sweep_pass" ],
    [ "NaiveSweepPass2", "structcugip_1_1_naive_sweep_pass2.html", "structcugip_1_1_naive_sweep_pass2" ],
    [ "NaiveWorkDistribution", "structcugip_1_1_naive_work_distribution.html", "structcugip_1_1_naive_work_distribution" ],
    [ "NAryOperatorDeviceImageView", "classcugip_1_1_n_ary_operator_device_image_view.html", "classcugip_1_1_n_ary_operator_device_image_view" ],
    [ "negate", "structcugip_1_1negate.html", "structcugip_1_1negate" ],
    [ "neighborhood_4", "structcugip_1_1neighborhood__4.html", "structcugip_1_1neighborhood__4" ],
    [ "neighborhood_4_tag", "structcugip_1_1neighborhood__4__tag.html", "structcugip_1_1neighborhood__4__tag" ],
    [ "neighborhood_accessor", "classcugip_1_1neighborhood__accessor.html", "classcugip_1_1neighborhood__accessor" ],
    [ "NeighborhoodAccessor", "structcugip_1_1_neighborhood_accessor.html", "structcugip_1_1_neighborhood_accessor" ],
    [ "nl_means_parameters", "structcugip_1_1nl__means__parameters.html", "structcugip_1_1nl__means__parameters" ],
    [ "Options", "structcugip_1_1_options.html", null ],
    [ "PaddedImageView", "classcugip_1_1_padded_image_view.html", "classcugip_1_1_padded_image_view" ],
    [ "ParallelQueue", "classcugip_1_1_parallel_queue.html", "classcugip_1_1_parallel_queue" ],
    [ "ParallelQueueView", "classcugip_1_1_parallel_queue_view.html", "classcugip_1_1_parallel_queue_view" ],
    [ "PreloadingTransformLocatorPolicy", "structcugip_1_1_preloading_transform_locator_policy.html", "structcugip_1_1_preloading_transform_locator_policy" ],
    [ "ProductOfIntSequence", "structcugip_1_1_product_of_int_sequence.html", "structcugip_1_1_product_of_int_sequence" ],
    [ "Push", "structcugip_1_1_push.html", "structcugip_1_1_push" ],
    [ "PushPolicy", "structcugip_1_1_push_policy.html", "structcugip_1_1_push_policy" ],
    [ "Range", "structcugip_1_1_range.html", null ],
    [ "Range< L, I, Sizes< N... > >", "structcugip_1_1_range_3_01_l_00_01_i_00_01_sizes_3_01_n_8_8_8_01_4_01_4.html", null ],
    [ "Range< L, L, Sizes< N... > >", "structcugip_1_1_range_3_01_l_00_01_l_00_01_sizes_3_01_n_8_8_8_01_4_01_4.html", null ],
    [ "ReactionDiffusionRule", "structcugip_1_1_reaction_diffusion_rule.html", "structcugip_1_1_reaction_diffusion_rule" ],
    [ "region", "structcugip_1_1region.html", "structcugip_1_1region" ],
    [ "Relabel", "structcugip_1_1_relabel.html", "structcugip_1_1_relabel" ],
    [ "RelabelPolicy", "structcugip_1_1_relabel_policy.html", "structcugip_1_1_relabel_policy" ],
    [ "scan_image_for_wshed_path_ftor", "structcugip_1_1scan__image__for__wshed__path__ftor.html", "structcugip_1_1scan__image__for__wshed__path__ftor" ],
    [ "separable_convolution_operator", "structcugip_1_1separable__convolution__operator.html", "structcugip_1_1separable__convolution__operator" ],
    [ "SetMask", "structcugip_1_1_set_mask.html", "structcugip_1_1_set_mask" ],
    [ "simple_vector", "classcugip_1_1simple__vector.html", "classcugip_1_1simple__vector" ],
    [ "Sizes", "structcugip_1_1_sizes.html", null ],
    [ "slice_image_view", "classcugip_1_1slice__image__view.html", null ],
    [ "slice_image_view< TView, tSliceDimension, false >", "classcugip_1_1slice__image__view_3_01_t_view_00_01t_slice_dimension_00_01false_01_4.html", "classcugip_1_1slice__image__view_3_01_t_view_00_01t_slice_dimension_00_01false_01_4" ],
    [ "sobel_gradient", "structcugip_1_1sobel__gradient.html", "structcugip_1_1sobel__gradient" ],
    [ "sobel_gradient_magnitude", "structcugip_1_1sobel__gradient__magnitude.html", "structcugip_1_1sobel__gradient__magnitude" ],
    [ "sobel_weighted_divergence", "structcugip_1_1sobel__weighted__divergence.html", "structcugip_1_1sobel__weighted__divergence" ],
    [ "SquareFunctor", "structcugip_1_1_square_functor.html", "structcugip_1_1_square_functor" ],
    [ "SquareRootFunctor", "structcugip_1_1_square_root_functor.html", "structcugip_1_1_square_root_functor" ],
    [ "static_matrix_traits", "structcugip_1_1static__matrix__traits.html", "structcugip_1_1static__matrix__traits" ],
    [ "static_matrix_traits< matrix< TType, tRowCount, tColCount > >", "structcugip_1_1static__matrix__traits_3_01matrix_3_01_t_type_00_01t_row_count_00_01t_col_count_01_4_01_4.html", "structcugip_1_1static__matrix__traits_3_01matrix_3_01_t_type_00_01t_row_count_00_01t_col_count_01_4_01_4" ],
    [ "static_matrix_traits< symmetric_tensor< TType, tDimension > >", "structcugip_1_1static__matrix__traits_3_01symmetric__tensor_3_01_t_type_00_01t_dimension_01_4_01_4.html", "structcugip_1_1static__matrix__traits_3_01symmetric__tensor_3_01_t_type_00_01t_dimension_01_4_01_4" ],
    [ "static_memory_block", "structcugip_1_1static__memory__block.html", "structcugip_1_1static__memory__block" ],
    [ "static_vector_traits", "structcugip_1_1static__vector__traits.html", "structcugip_1_1static__vector__traits" ],
    [ "static_vector_traits< column_accessor< TMatrix > >", "structcugip_1_1static__vector__traits_3_01column__accessor_3_01_t_matrix_01_4_01_4.html", "structcugip_1_1static__vector__traits_3_01column__accessor_3_01_t_matrix_01_4_01_4" ],
    [ "static_vector_traits< simple_vector< TValue, tDimension > >", "structcugip_1_1static__vector__traits_3_01simple__vector_3_01_t_value_00_01t_dimension_01_4_01_4.html", "structcugip_1_1static__vector__traits_3_01simple__vector_3_01_t_value_00_01t_dimension_01_4_01_4" ],
    [ "StaticSize", "structcugip_1_1_static_size.html", "structcugip_1_1_static_size" ],
    [ "step1_ftor", "structcugip_1_1step1__ftor.html", "structcugip_1_1step1__ftor" ],
    [ "subimage_view", "classcugip_1_1subimage__view.html", null ],
    [ "subimage_view< TView, false >", "classcugip_1_1subimage__view_3_01_t_view_00_01false_01_4.html", "classcugip_1_1subimage__view_3_01_t_view_00_01false_01_4" ],
    [ "SumValuesFunctor", "structcugip_1_1_sum_values_functor.html", "structcugip_1_1_sum_values_functor" ],
    [ "SweepPass", "structcugip_1_1_sweep_pass.html", "structcugip_1_1_sweep_pass" ],
    [ "symmetric_tensor", "classcugip_1_1symmetric__tensor.html", "classcugip_1_1symmetric__tensor" ],
    [ "texture_image", "classcugip_1_1texture__image.html", "classcugip_1_1texture__image" ],
    [ "texture_view", "classcugip_1_1texture__view.html", "classcugip_1_1texture__view" ],
    [ "thresholding_ftor", "structcugip_1_1thresholding__ftor.html", "structcugip_1_1thresholding__ftor" ],
    [ "Tile", "structcugip_1_1_tile.html", "structcugip_1_1_tile" ],
    [ "TileProcessor", "structcugip_1_1_tile_processor.html", "structcugip_1_1_tile_processor" ],
    [ "transform_update_add", "structcugip_1_1transform__update__add.html", "structcugip_1_1transform__update__add" ],
    [ "transform_update_assign", "structcugip_1_1transform__update__assign.html", "structcugip_1_1transform__update__assign" ],
    [ "Tuple", "structcugip_1_1_tuple.html", "structcugip_1_1_tuple" ],
    [ "TupleElem", "classcugip_1_1_tuple_elem.html", "classcugip_1_1_tuple_elem" ],
    [ "TupleImpl", "classcugip_1_1_tuple_impl.html", null ],
    [ "TupleImpl< Sizes< N... >, T... >", "classcugip_1_1_tuple_impl_3_01_sizes_3_01_n_8_8_8_01_4_00_01_t_8_8_8_01_4.html", "classcugip_1_1_tuple_impl_3_01_sizes_3_01_n_8_8_8_01_4_00_01_t_8_8_8_01_4" ],
    [ "UnaryOperatorImageView", "classcugip_1_1_unary_operator_image_view.html", "classcugip_1_1_unary_operator_image_view" ],
    [ "UnaryOperatorOnLocatorImageView", "classcugip_1_1_unary_operator_on_locator_image_view.html", "classcugip_1_1_unary_operator_on_locator_image_view" ],
    [ "UnaryOperatorOnPositionImageView", "classcugip_1_1_unary_operator_on_position_image_view.html", "classcugip_1_1_unary_operator_on_position_image_view" ],
    [ "UniqueIdDeviceImageView", "classcugip_1_1_unique_id_device_image_view.html", "classcugip_1_1_unique_id_device_image_view" ],
    [ "UpperLimitFunctor", "structcugip_1_1_upper_limit_functor.html", "structcugip_1_1_upper_limit_functor" ],
    [ "UpperLimitReplacementFunctor", "structcugip_1_1_upper_limit_replacement_functor.html", "structcugip_1_1_upper_limit_replacement_functor" ],
    [ "VonNeumannNeighborhood", "structcugip_1_1_von_neumann_neighborhood.html", null ],
    [ "VonNeumannNeighborhood< 2 >", "structcugip_1_1_von_neumann_neighborhood_3_012_01_4.html", "structcugip_1_1_von_neumann_neighborhood_3_012_01_4" ],
    [ "VonNeumannNeighborhood< 3 >", "structcugip_1_1_von_neumann_neighborhood_3_013_01_4.html", "structcugip_1_1_von_neumann_neighborhood_3_013_01_4" ],
    [ "Watershed2GlobalStateRule", "structcugip_1_1_watershed2_global_state_rule.html", "structcugip_1_1_watershed2_global_state_rule" ],
    [ "Watershed2Rule", "structcugip_1_1_watershed2_rule.html", "structcugip_1_1_watershed2_rule" ],
    [ "Watershed2RuleBase", "structcugip_1_1_watershed2_rule_base.html", "structcugip_1_1_watershed2_rule_base" ],
    [ "Watershed3Rule", "structcugip_1_1_watershed3_rule.html", "structcugip_1_1_watershed3_rule" ],
    [ "WatershedRule", "structcugip_1_1_watershed_rule.html", "structcugip_1_1_watershed_rule" ],
    [ "WatershedSteepestDescentGlobalStateRule", "structcugip_1_1_watershed_steepest_descent_global_state_rule.html", "structcugip_1_1_watershed_steepest_descent_global_state_rule" ],
    [ "WatershedSteepestDescentRule", "structcugip_1_1_watershed_steepest_descent_rule.html", "structcugip_1_1_watershed_steepest_descent_rule" ],
    [ "WatershedSteepestDescentRuleBase", "structcugip_1_1_watershed_steepest_descent_rule_base.html", "structcugip_1_1_watershed_steepest_descent_rule_base" ],
    [ "WorkDistribution", "structcugip_1_1_work_distribution.html", "structcugip_1_1_work_distribution" ],
    [ "WorkLimits", "structcugip_1_1_work_limits.html", "structcugip_1_1_work_limits" ],
    [ "ZipValues", "structcugip_1_1_zip_values.html", "structcugip_1_1_zip_values" ]
];