CUGIP: cugip::detail Namespace Reference
cugip::detail Namespace Reference
Views
Classes
struct compute_divergence
struct compute_divergence< TOutputType, TLocator, 0 >
struct compute_symmetric_difference
struct compute_symmetric_difference< TOutputType, TLocator, 0 >
struct compute_weight
struct ForEachImplementation
struct ForEachImplementation< false >
struct ForEachImplementation< true >
struct ForEachPositionImplementation
struct ForEachPositionImplementation< false >
struct ForEachPositionImplementation< true >
struct GenerateIntSequenceImpl
struct GenerateIntSequenceImpl< 0, tValues... >
struct GetPositionInIntSequenceImpl
struct GetPositionInIntSequenceImpl< tCurrentIndex, tValue, tHead >
struct IsValueInIntSequenceImpl
struct IsValueInIntSequenceImpl< tValue, tHead >
struct LastItemInIntSequenceImpl
struct LastItemInIntSequenceImpl< IntSequence< tHead, tTail... > >
struct LastItemInIntSequenceImpl< IntSequence< tTail > >
struct multiply_ftor
struct ProductIntSequenceImpl
struct ProductIntSequenceImpl< tCurrentResult, IntSequence< tHead > >
struct ProductIntSequenceImpl< tCurrentResult, IntSequence< tHead, tValues... > >
struct RunTimeThreadBlockSize
struct scan_neighborhood_for_connections_ftor
struct separable_convolution_impl
struct separable_convolution_impl< 2 >
struct separable_convolution_impl< 3 >
class SharedMemory
struct SliceGenerator
struct SliceGenerator< TView, tSliceDimension, true >
struct SubviewGenerator
struct SubviewGenerator< TView, true >
struct threshold_mask_operator
struct TransformImplementation
struct TransformImplementation< false >
struct TransformImplementation< true >
struct TransformLocatorImplementation
struct TransformLocatorImplementation< false >
struct TransformLocatorImplementation< true >
struct TransformPositionImplementation
struct TransformPositionImplementation< false >
struct TransformPositionImplementation< true >
struct weighted_add_ftor
Functions
template<typename TInImageView , typename TOutImageView , typename TParameters >
CUGIP_GLOBAL void kernel_nonlocal_means (TInImageView aIn, TOutImageView aOut, TParameters aParameters)
template<typename TInImageView , typename TOutImageView , typename TParameters >
CUGIP_GLOBAL void kernel_nonlocal_means3 (TInImageView aIn, TOutImageView aOut, TParameters aParameters)
template<typename TInImageView , typename TOutImageView , typename TParameters , int tStepCount>
CUGIP_GLOBAL void kernel_nonlocal_means2 (TInImageView aIn, TOutImageView aOut, TParameters aParameters)
template<typename TParameters >
bool subvolume_too_big (dim3 aBlockSize, const simple_vector< int, 3 > &aGridSize, TParameters aParameters)
template<typename TImageView , typename TLUTBufferView >
CUGIP_GLOBAL void init_lut_kernel (TImageView aImageView, TLUTBufferView aLUT)
template<typename TImageView , typename TLUTBufferView >
void init_lut (TImageView aImageView, TLUTBufferView aLUT)
template<typename TImageView , typename TLUTBufferView >
void scan_image_for_connections (TImageView aImageView, TLUTBufferView aLUT, device_flag_view aLutUpdatedFlag)
template<typename TImageView , typename TLUTBufferView >
CUGIP_GLOBAL void update_lut_kernel (TImageView aImageView, TLUTBufferView aLUT)
template<typename TImageView , typename TLUTBufferView >
void update_lut (TImageView aImageView, TLUTBufferView aLUT)
template<typename TImageView , typename TLUTBufferView >
CUGIP_GLOBAL void update_labels_kernel (TImageView aImageView, TLUTBufferView aLUT)
template<typename TImageView , typename TLUTBufferView >
void update_labels (TImageView aImageView, TLUTBufferView aLUT)
template<typename TType >
void copy_wrapper (const TType *aFromPointer, int aFromPitch, TType *aToPointer, int aToPitch, size2_t aSize, cudaMemcpyKind aMemcpyKind)
template<typename TType >
void copy_wrapper (const TType *aFromPointer, int aFromPitch, TType *aToPointer, int aToPitch, size3_t aSize, cudaMemcpyKind aMemcpyKind)
template<typename TView , typename TFunctor , typename TPolicy >
CUGIP_GLOBAL void kernel_for_each (TView aView, TFunctor aOperator, TPolicy aPolicy)
template<typename TView , typename TFunctor , typename TPolicy >
CUGIP_GLOBAL void kernel_for_each_position (TView aView, TFunctor aOperator, TPolicy aPolicy)
template<typename TInView , typename TFunctor , typename TPolicy >
void for_each_host (TInView aInView, TFunctor aOperator, TPolicy aPolicy)
template<typename TInView , typename TFunctor , typename TPolicy >
void for_each_position_host (TInView aInView, TFunctor aOperator, TPolicy aPolicy)
template<typename TFunctor >
TFunctor for_each_implementation (region< 2 > aRegion, TFunctor aOperator)
template<typename TFunctor >
TFunctor for_each_implementation (region< 3 > aRegion, TFunctor aOperator)
template<typename TInView , typename TOutView , typename TFunctor , typename TAssignOperation , typename TPolicy >
CUGIP_GLOBAL void kernel_transform (TInView aInView, TOutView aOutView, TFunctor aOperator, TAssignOperation aAssignOperation, TPolicy aPolicy)
template<typename TInView1 , typename TInView2 , typename TOutView , typename TFunctor , typename TAssignOperation , typename TPolicy >
CUGIP_GLOBAL void kernel_transform2 (TInView1 aInView1, TInView2 aInView2, TOutView aOutView, TFunctor aOperator, TAssignOperation aAssignOperation, TPolicy aPolicy)
template<typename TInView , typename TOutView , typename TFunctor , typename TAssignOperation , typename TPolicy >
CUGIP_GLOBAL void kernel_transform_position (TInView aInView, TOutView aOutView, TFunctor aOperator, TAssignOperation aAssignOperation, TPolicy aPolicy)
template<typename TInView , typename TOutView , typename TOperator , typename TAssignOperation , typename TPolicy >
CUGIP_GLOBAL void kernel_transform_locator (TInView aInView, TOutView aOutView, TOperator aOperator, TAssignOperation aAssignOperation, TPolicy aPolicy)
template<typename TInView , typename TOutView , typename TOperator , typename TAssignOperation , typename TPolicy >
CUGIP_GLOBAL void kernel_transform_locator_preload (TInView aInView, TOutView aOutView, TOperator aOperator, TAssignOperation aAssignOperation, TPolicy aPolicy)
template<typename TInView , typename TOutView , typename TFunctor , typename TAssignOperation , typename TPolicy >
void transformHost (TInView aInView, TOutView aOutView, TFunctor aOperator, TAssignOperation aAssignOperation, TPolicy aPolicy)
template<typename TInView1 , typename TInView2 , typename TOutView , typename TFunctor , typename TAssignOperation , typename TPolicy >
void transformHost (TInView1 aInView1, TInView2 aInView2, TOutView aOutView, TFunctor aOperator, TAssignOperation aAssignOperation, TPolicy aPolicy)
template<typename TInView , typename TOutView , typename TFunctor , typename TAssignOperation , typename TPolicy >
void transformPositionHost (TInView aInView, TOutView aOutView, TFunctor aOperator, TAssignOperation aAssignOperation, TPolicy aPolicy)
template<typename TInView , typename TOutView , typename TOperator , typename TAssignOperation , typename TPolicy >
void transformLocatorHost (TInView aInView, TOutView aOutView, TOperator aOperator, TAssignOperation aAssignOperation, TPolicy aPolicy)
template<typename TView , typename TType >
CUGIP_GLOBAL void kernel_fill (TView aView, TType aValue)
template<typename TInView , typename TOutView , typename TFunctor >
CUGIP_GLOBAL void kernel_filter (TInView aInView, TOutView aOutView, TFunctor aOperator)
template<typename TInputView , typename TOutputView , typename TOperator , int tDim, int tBlockSize, bool tStoreIntermediateR>
CUGIP_GLOBAL void kernel_scan_block_dim (TInputView aInput, TOutputView aOutput, TOutputView aIntermediateResultsView, TOperator aOperator)
template<typename TOutputView , typename TOperator , int tDim, int tBlockSize>
CUGIP_GLOBAL void kernel_update_block_dim (TOutputView aOutput, TOutputView aIntermediateResultsView, TOperator aOperator)
template<typename TInputView , typename TOutputView , typename TOperator , int tDim>
void scan_block_dim (TInputView aInput, TOutputView aOutput, TOutputView aTmpView, TOperator aOperator)
template<typename TOutputView , typename TOperator , int tDim>
void update_block_dim (TOutputView aOutput, TOutputView aTmpView, TOperator aOperator)
template<typename TInputView , typename TOutputView , typename TOperator , int tDim>
void scan_dim (TInputView aInput, TOutputView aOutput, TOutputView aTmpView, TOperator aOperator)
Function Documentation
template<typename TType > void cugip::detail::copy_wrapper (const TType * aFromPointer, int aFromPitch, TType * aToPointer, int aToPitch, size2_t aSize, cudaMemcpyKind aMemcpyKind)
Definition at line 17 of file copy.hpp.
template<typename TType > void cugip::detail::copy_wrapper (const TType * aFromPointer, int aFromPitch, TType * aToPointer, int aToPitch, size3_t aSize, cudaMemcpyKind aMemcpyKind)
Definition at line 37 of file copy.hpp.
template<typename TInView , typename TFunctor , typename TPolicy > void cugip::detail::for_each_host (TInView aInView, TFunctor aOperator, TPolicy aPolicy)
Definition at line 8 of file for_each_host_implementation.hpp.
References cugip::elementCount(), and cugip::linear_access().
Referenced by cugip::detail::ForEachImplementation< false >::run().
template<typename TFunctor > TFunctor cugip::detail::for_each_implementation (region< 2 > aRegion, TFunctor aOperator)
Definition at line 45 of file for_each_host_implementation.hpp.
References cugip::region< tDimension >::corner, and cugip::region< tDimension >::size.
Referenced by cugip::for_each().
template<typename TFunctor > TFunctor cugip::detail::for_each_implementation (region< 3 > aRegion, TFunctor aOperator)
Definition at line 57 of file for_each_host_implementation.hpp.
References cugip::region< tDimension >::corner, and cugip::region< tDimension >::size.
template<typename TInView , typename TFunctor , typename TPolicy > void cugip::detail::for_each_position_host (TInView aInView, TFunctor aOperator, TPolicy aPolicy)
Definition at line 26 of file for_each_host_implementation.hpp.
References cugip::elementCount(), and cugip::index_from_linear_access_index().
Referenced by cugip::detail::ForEachPositionImplementation< false >::run().
template<typename TImageView , typename TLUTBufferView > void cugip::detail::init_lut (TImageView aImageView, TLUTBufferView aLUT)
Definition at line 32 of file connected_component_labeling.hpp.
References cugip::multiply().
Referenced by cugip::connected_component_labeling().
template<typename TImageView , typename TLUTBufferView > CUGIP_GLOBAL void cugip::detail::init_lut_kernel (TImageView aImageView, TLUTBufferView aLUT)
Todo:
check 0
Definition at line 19 of file connected_component_labeling.hpp.
References cugip::linear_access(), and cugip::multiply().
template<typename TView , typename TType > CUGIP_GLOBAL void cugip::detail::kernel_fill (TView aView, TType aValue)
Definition at line 12 of file fill.hpp.
template<typename TInView , typename TOutView , typename TFunctor > CUGIP_GLOBAL void cugip::detail::kernel_filter (TInView aInView, TOutView aOutView, TFunctor aOperator)
Definition at line 14 of file filter.hpp.
template<typename TView , typename TFunctor , typename TPolicy > CUGIP_GLOBAL void cugip::detail::kernel_for_each (TView aView, TFunctor aOperator, TPolicy aPolicy)
Definition at line 8 of file for_each_device_implementation.hpp.
template<typename TView , typename TFunctor , typename TPolicy > CUGIP_GLOBAL void cugip::detail::kernel_for_each_position (TView aView, TFunctor aOperator, TPolicy aPolicy)
Definition at line 34 of file for_each_device_implementation.hpp.
template<typename TInImageView , typename TOutImageView , typename TParameters > CUGIP_GLOBAL void cugip::detail::kernel_nonlocal_means (TInImageView aIn, TOutImageView aOut, TParameters aParameters)
Definition at line 76 of file nonlocal_means.hpp.
References CUGIP_GLOBAL, cugip::detail::compute_weight< tPatchRadius >::run(), and cugip::detail::SharedMemory< TElement, TStaticSize, TThreadBlockSize >::view().
template<typename TInImageView , typename TOutImageView , typename TParameters , int tStepCount> CUGIP_GLOBAL void cugip::detail::kernel_nonlocal_means2 (TInImageView aIn, TOutImageView aOut, TParameters aParameters)
Definition at line 170 of file nonlocal_means.hpp.
References cugip::image_locator< TImageView, TBorderHandling >::dimensions(), cugip::for_each_neighbor(), cugip::detail::compute_weight< tPatchRadius >::run(), and cugip::detail::SharedMemory< TElement, TStaticSize, TThreadBlockSize >::view().
template<typename TInImageView , typename TOutImageView , typename TParameters > CUGIP_GLOBAL void cugip::detail::kernel_nonlocal_means3 (TInImageView aIn, TOutImageView aOut, TParameters aParameters)
Definition at line 115 of file nonlocal_means.hpp.
References CUGIP_GLOBAL, cugip::currentThreadIndex(), and cugip::detail::compute_weight< tPatchRadius >::run().
template<typename TInputView , typename TOutputView , typename TOperator , int tDim, int tBlockSize, bool tStoreIntermediateR> CUGIP_GLOBAL void cugip::detail::kernel_scan_block_dim (TInputView aInput, TOutputView aOutput, TOutputView aIntermediateResultsView, TOperator aOperator)
Todo:
use right mask for background
Todo:
use right mask for background
Definition at line 16 of file scan.hpp.
References CUGIP_GLOBAL, CUGIP_SHARED, and cugip::less().
Referenced by scan_block_dim().
template<typename TInView , typename TOutView , typename TFunctor , typename TAssignOperation , typename TPolicy > CUGIP_GLOBAL void cugip::detail::kernel_transform (TInView aInView, TOutView aOutView, TFunctor aOperator, TAssignOperation aAssignOperation, TPolicy aPolicy)
Definition at line 7 of file transform_device_implementation.hpp.
References CUGIP_GLOBAL.
template<typename TInView1 , typename TInView2 , typename TOutView , typename TFunctor , typename TAssignOperation , typename TPolicy > CUGIP_GLOBAL void cugip::detail::kernel_transform2 (TInView1 aInView1, TInView2 aInView2, TOutView aOutView, TFunctor aOperator, TAssignOperation aAssignOperation, TPolicy aPolicy)
Definition at line 19 of file transform_device_implementation.hpp.
template<typename TInView , typename TOutView , typename TOperator , typename TAssignOperation , typename TPolicy > CUGIP_GLOBAL void cugip::detail::kernel_transform_locator (TInView aInView, TOutView aOutView, TOperator aOperator, TAssignOperation aAssignOperation, TPolicy aPolicy)
Definition at line 77 of file transform_device_implementation.hpp.
References CUGIP_GLOBAL.
template<typename TInView , typename TOutView , typename TOperator , typename TAssignOperation , typename TPolicy > CUGIP_GLOBAL void cugip::detail::kernel_transform_locator_preload (TInView aInView, TOutView aOutView, TOperator aOperator, TAssignOperation aAssignOperation, TPolicy aPolicy)
Definition at line 89 of file transform_device_implementation.hpp.
References cugip::makeDeviceImageView(), and cugip::to_vector().
template<typename TInView , typename TOutView , typename TFunctor , typename TAssignOperation , typename TPolicy > CUGIP_GLOBAL void cugip::detail::kernel_transform_position (TInView aInView, TOutView aOutView, TFunctor aOperator, TAssignOperation aAssignOperation, TPolicy aPolicy)
Definition at line 53 of file transform_device_implementation.hpp.
template<typename TOutputView , typename TOperator , int tDim, int tBlockSize> CUGIP_GLOBAL void cugip::detail::kernel_update_block_dim (TOutputView aOutput, TOutputView aIntermediateResultsView, TOperator aOperator)
Definition at line 96 of file scan.hpp.
References CUGIP_SHARED, and cugip::less().
Referenced by update_block_dim().
template<typename TInputView , typename TOutputView , typename TOperator , int tDim> void cugip::detail::scan_block_dim (TInputView aInput, TOutputView aOutput, TOutputView aTmpView, TOperator aOperator)
Todo:
generic method for thread distribution over the data
Definition at line 132 of file scan.hpp.
References D_PRINT, kernel_scan_block_dim(), and SCAN_BLOCK_SIZE.
Referenced by scan_dim().
template<typename TInputView , typename TOutputView , typename TOperator , int tDim> void cugip::detail::scan_dim (TInputView aInput, TOutputView aOutput, TOutputView aTmpView, TOperator aOperator)
Todo:
handle intermediate results - proper recursive call
Definition at line 190 of file scan.hpp.
References CUGIP_ASSERT, scan_block_dim(), SCAN_BLOCK_SIZE, and update_block_dim().
Referenced by cugip::scan().
template<typename TImageView , typename TLUTBufferView > void cugip::detail::scan_image_for_connections (TImageView aImageView, TLUTBufferView aLUT, device_flag_view aLutUpdatedFlag)
Definition at line 91 of file connected_component_labeling.hpp.
References CUGIP_GLOBAL.
Referenced by cugip::connected_component_labeling().
template<typename TParameters > bool cugip::detail::subvolume_too_big (dim3 aBlockSize, const simple_vector< int, 3 > & aGridSize, TParameters aParameters)
Definition at line 221 of file nonlocal_means.hpp.
References cugip::multiply().
template<typename TInView , typename TOutView , typename TFunctor , typename TAssignOperation , typename TPolicy > void cugip::detail::transformHost (TInView aInView, TOutView aOutView, TFunctor aOperator, TAssignOperation aAssignOperation, TPolicy aPolicy)
Definition at line 7 of file transform_host_implementation.hpp.
References cugip::elementCount(), and cugip::linear_access().
Referenced by cugip::detail::TransformImplementation< false >::run().
template<typename TInView1 , typename TInView2 , typename TOutView , typename TFunctor , typename TAssignOperation , typename TPolicy > void cugip::detail::transformHost (TInView1 aInView1, TInView2 aInView2, TOutView aOutView, TFunctor aOperator, TAssignOperation aAssignOperation, TPolicy aPolicy)
Definition at line 16 of file transform_host_implementation.hpp.
References cugip::elementCount(), and cugip::linear_access().
template<typename TInView , typename TOutView , typename TOperator , typename TAssignOperation , typename TPolicy > void cugip::detail::transformLocatorHost (TInView aInView, TOutView aOutView, TOperator aOperator, TAssignOperation aAssignOperation, TPolicy aPolicy)
Definition at line 55 of file transform_host_implementation.hpp.
References cugip::elementCount(), cugip::index_from_linear_access_index(), and cugip::linear_access().
Referenced by cugip::detail::TransformLocatorImplementation< false >::run().
template<typename TInView , typename TOutView , typename TFunctor , typename TAssignOperation , typename TPolicy > void cugip::detail::transformPositionHost (TInView aInView, TOutView aOutView, TFunctor aOperator, TAssignOperation aAssignOperation, TPolicy aPolicy)
Definition at line 38 of file transform_host_implementation.hpp.
References cugip::elementCount(), and cugip::linear_access().
Referenced by cugip::detail::TransformPositionImplementation< false >::run().
template<typename TOutputView , typename TOperator , int tDim> void cugip::detail::update_block_dim (TOutputView aOutput, TOutputView aTmpView, TOperator aOperator)
Todo:
generic method for thread distribution over the data
Definition at line 161 of file scan.hpp.
References D_PRINT, kernel_update_block_dim(), and SCAN_BLOCK_SIZE.
Referenced by scan_dim().
template<typename TImageView , typename TLUTBufferView > void cugip::detail::update_labels (TImageView aImageView, TLUTBufferView aLUT)
Definition at line 148 of file connected_component_labeling.hpp.
References cugip::multiply().
Referenced by cugip::clear_nonminima_plateaus(), cugip::connected_component_labeling(), and cugip::watershed_transformation1().
template<typename TImageView , typename TLUTBufferView > CUGIP_GLOBAL void cugip::detail::update_labels_kernel (TImageView aImageView, TLUTBufferView aLUT)
Definition at line 133 of file connected_component_labeling.hpp.
References cugip::linear_access(), and cugip::multiply().
template<typename TImageView , typename TLUTBufferView > void cugip::detail::update_lut (TImageView aImageView, TLUTBufferView aLUT)
Definition at line 122 of file connected_component_labeling.hpp.
References CUGIP_GLOBAL, and cugip::multiply().
Referenced by cugip::connected_component_labeling(), and cugip::watershed_transformation1().
template<typename TImageView , typename TLUTBufferView > CUGIP_GLOBAL void cugip::detail::update_lut_kernel (TImageView aImageView, TLUTBufferView aLUT)
Definition at line 98 of file connected_component_labeling.hpp.
References cugip::linear_access(), and cugip::multiply().