CUGIP: cugip::GraphCutData< TFlow > Struct Template Reference
cugip::GraphCutData< TFlow > Struct Template Reference
#include <graph_cut_data.hpp>
Public Types
typedef TFlow Flow
Public Member Functions
CUGIP_DECL_DEVICE int neighborCount (int aVertexId) const
CUGIP_DECL_DEVICE TFlow & excess (int aVertexId)
CUGIP_DECL_DEVICE int & label (int aVertexId)
CUGIP_DECL_HYBRID int vertexCount () const
CUGIP_DECL_DEVICE int firstNeighborIndex (int aVertexId) const
CUGIP_DECL_DEVICE int secondVertex (int aIndex) const
CUGIP_DECL_DEVICE int connectionIndex (int aIndex) const
CUGIP_DECL_DEVICE bool connectionSide (int aIndex) const
CUGIP_DECL_DEVICE TFlow sourceTLinkCapacity (int aIndex) const
CUGIP_DECL_DEVICE TFlow sinkTLinkCapacity (int aIndex) const
template<TLinkType tTLinkType>
CUGIP_DECL_DEVICE TFlow tLinkCapacity (int aIndex) const
CUGIP_DECL_DEVICE EdgeResidualsRecord< TFlow > & residuals (int aIndex)
CUGIP_DECL_DEVICE TFlow & sinkFlow (int aVertexId)
Public Attributes
int mVertexCount
int mEdgeCount
TFlow * vertexExcess
int * labels
int * neighbors
TFlow * mTLinks [2]
int * secondVertices
int * connectionIndices
EdgeResidualsRecord< TFlow > * mResiduals
TFlow * mSinkFlow
Detailed Description
template<typename TFlow>
struct cugip::GraphCutData< TFlow >
Definition at line 21 of file graph_cut_data.hpp.
Member Typedef Documentation
template<typename TFlow> typedef TFlow cugip::GraphCutData< TFlow >::Flow
Definition at line 23 of file graph_cut_data.hpp.
Member Function Documentation
template<typename TFlow> CUGIP_DECL_DEVICE int cugip::GraphCutData< TFlow >::connectionIndex (int aIndex) const inline
Definition at line 69 of file graph_cut_data.hpp.
Referenced by cugip::pushImplementation().
template<typename TFlow> CUGIP_DECL_DEVICE bool cugip::GraphCutData< TFlow >::connectionSide (int aIndex) const inline
Definition at line 76 of file graph_cut_data.hpp.
Referenced by cugip::pushImplementation().
template<typename TFlow> CUGIP_DECL_DEVICE TFlow& cugip::GraphCutData< TFlow >::excess (int aVertexId) inline
Definition at line 32 of file graph_cut_data.hpp.
Referenced by cugip::pushImplementation(), cugip::pushThroughTLinksFromSourceKernel(), cugip::pushThroughTLinksToSinkKernel(), cugip::tryPull(), and cugip::tryPullPush().
template<typename TFlow> CUGIP_DECL_DEVICE int cugip::GraphCutData< TFlow >::firstNeighborIndex (int aVertexId) const inline
Definition at line 52 of file graph_cut_data.hpp.
Referenced by cugip::GraphCutData< Flow >::neighborCount(), and cugip::pushImplementation().
template<typename TFlow> CUGIP_DECL_DEVICE int& cugip::GraphCutData< TFlow >::label (int aVertexId) inline
Definition at line 39 of file graph_cut_data.hpp.
Referenced by cugip::pushImplementation().
template<typename TFlow> CUGIP_DECL_DEVICE int cugip::GraphCutData< TFlow >::neighborCount (int aVertexId) const inline
Definition at line 25 of file graph_cut_data.hpp.
Referenced by cugip::pushImplementation().
template<typename TFlow> CUGIP_DECL_DEVICE EdgeResidualsRecord<TFlow>& cugip::GraphCutData< TFlow >::residuals (int aIndex) inline
Definition at line 107 of file graph_cut_data.hpp.
Referenced by cugip::tryPullPush().
template<typename TFlow> CUGIP_DECL_DEVICE int cugip::GraphCutData< TFlow >::secondVertex (int aIndex) const inline
Definition at line 62 of file graph_cut_data.hpp.
Referenced by cugip::pushImplementation().
template<typename TFlow> CUGIP_DECL_DEVICE TFlow& cugip::GraphCutData< TFlow >::sinkFlow (int aVertexId) inline
Definition at line 116 of file graph_cut_data.hpp.
Referenced by cugip::pushThroughTLinksToSinkKernel().
template<typename TFlow> CUGIP_DECL_DEVICE TFlow cugip::GraphCutData< TFlow >::sinkTLinkCapacity (int aIndex) const inline
Definition at line 91 of file graph_cut_data.hpp.
Referenced by cugip::pushThroughTLinksToSinkKernel().
template<typename TFlow> CUGIP_DECL_DEVICE TFlow cugip::GraphCutData< TFlow >::sourceTLinkCapacity (int aIndex) const inline
Definition at line 83 of file graph_cut_data.hpp.
Referenced by cugip::pushThroughTLinksFromSourceKernel().
template<typename TFlow> template<TLinkType tTLinkType> CUGIP_DECL_DEVICE TFlow cugip::GraphCutData< TFlow >::tLinkCapacity (int aIndex) const inline
Definition at line 100 of file graph_cut_data.hpp.
template<typename TFlow> CUGIP_DECL_HYBRID int cugip::GraphCutData< TFlow >::vertexCount () const inline
Definition at line 46 of file graph_cut_data.hpp.
Referenced by cugip::assignLabelByDistance(), cugip::for_each_vertex(), cugip::forEachVertexKernel(), cugip::pushThroughTLinksFromSourceKernel(), and cugip::pushThroughTLinksToSinkKernel().
Member Data Documentation
template<typename TFlow> int* cugip::GraphCutData< TFlow >::connectionIndices
Definition at line 135 of file graph_cut_data.hpp.
Referenced by cugip::GraphCutData< Flow >::connectionIndex(), and cugip::GraphCutData< Flow >::connectionSide().
template<typename TFlow> int* cugip::GraphCutData< TFlow >::labels
Definition at line 126 of file graph_cut_data.hpp.
Referenced by cugip::GraphCutData< Flow >::label().
template<typename TFlow> int cugip::GraphCutData< TFlow >::mEdgeCount
Definition at line 123 of file graph_cut_data.hpp.
template<typename TFlow> EdgeResidualsRecord<TFlow>* cugip::GraphCutData< TFlow >::mResiduals
Definition at line 136 of file graph_cut_data.hpp.
Referenced by cugip::GraphCutData< Flow >::residuals().
template<typename TFlow> TFlow* cugip::GraphCutData< TFlow >::mSinkFlow
Definition at line 138 of file graph_cut_data.hpp.
Referenced by cugip::GraphCutData< Flow >::sinkFlow().
template<typename TFlow> TFlow* cugip::GraphCutData< TFlow >::mTLinks[2]
Definition at line 132 of file graph_cut_data.hpp.
Referenced by cugip::GraphCutData< Flow >::tLinkCapacity().
template<typename TFlow> int cugip::GraphCutData< TFlow >::mVertexCount
Definition at line 122 of file graph_cut_data.hpp.
Referenced by cugip::GraphCutData< Flow >::vertexCount().
template<typename TFlow> int* cugip::GraphCutData< TFlow >::neighbors
Definition at line 127 of file graph_cut_data.hpp.
Referenced by cugip::GraphCutData< Flow >::firstNeighborIndex().
template<typename TFlow> int* cugip::GraphCutData< TFlow >::secondVertices
Definition at line 134 of file graph_cut_data.hpp.
Referenced by cugip::GraphCutData< Flow >::secondVertex().
template<typename TFlow> TFlow* cugip::GraphCutData< TFlow >::vertexExcess
Definition at line 125 of file graph_cut_data.hpp.
Referenced by cugip::GraphCutData< Flow >::excess().
The documentation for this struct was generated from the following file:
/home/johny/programming/git/MedV4D/extern/cugip/include/cugip/advanced_operations/detail/graph_cut_data.hpp