CUGIP: cugip::convolution_kernel< TType, TSizeTraits > Struct Template Reference
cugip::convolution_kernel< TType, TSizeTraits > Struct Template Reference
#include <convolution.hpp>
Public Types
typedef TType element_t
Public Member Functions
CUGIP_DECL_HYBRID TType get (const simple_vector< int, cDimension > &aIndex) const
CUGIP_DECL_HYBRID TType & get (const simple_vector< int, cDimension > &aIndex)
Static Public Member Functions
static CUGIP_DECL_HYBRID constexpr simple_vector< int, cDimension > size ()
Public Attributes
TType data [TSizeTraits::count()]
simple_vector< int, cDimension > offset
Static Public Attributes
static constexpr int cDimension = TSizeTraits::cDimension
Detailed Description
template<typename TType, typename TSizeTraits>
struct cugip::convolution_kernel< TType, TSizeTraits >
Definition at line 11 of file convolution.hpp.
Member Typedef Documentation
template<typename TType, typename TSizeTraits> typedef TType cugip::convolution_kernel< TType, TSizeTraits >::element_t
Definition at line 14 of file convolution.hpp.
Member Function Documentation
template<typename TType, typename TSizeTraits> CUGIP_DECL_HYBRID TType cugip::convolution_kernel< TType, TSizeTraits >::get (const simple_vector< int, cDimension > & aIndex) const inline
Definition at line 23 of file convolution.hpp.
Referenced by cugip::gaussian_kernel(), and cugip::sobel_gradient_kernel().
template<typename TType, typename TSizeTraits> CUGIP_DECL_HYBRID TType& cugip::convolution_kernel< TType, TSizeTraits >::get (const simple_vector< int, cDimension > & aIndex) inline
Definition at line 29 of file convolution.hpp.
template<typename TType, typename TSizeTraits> static CUGIP_DECL_HYBRID constexpr simple_vector<int, cDimension> cugip::convolution_kernel< TType, TSizeTraits >::size () inline static
Definition at line 17 of file convolution.hpp.
Member Data Documentation
template<typename TType, typename TSizeTraits> constexpr int cugip::convolution_kernel< TType, TSizeTraits >::cDimension = TSizeTraits::cDimension static
Definition at line 13 of file convolution.hpp.
template<typename TType, typename TSizeTraits> TType cugip::convolution_kernel< TType, TSizeTraits >::data[TSizeTraits::count()]
Definition at line 34 of file convolution.hpp.
Referenced by cugip::convolution_kernel< simple_vector< float, tDimension >, typename FillStaticSize< tDimension, 3 >::Type >::get(), and cugip::convolution_kernel< TType, StaticSize< tSize > >::get().
template<typename TType, typename TSizeTraits> simple_vector<int, cDimension> cugip::convolution_kernel< TType, TSizeTraits >::offset
Definition at line 35 of file convolution.hpp.
Referenced by cugip::gaussian_kernel(), cugip::convolution_kernel< simple_vector< float, tDimension >, typename FillStaticSize< tDimension, 3 >::Type >::get(), cugip::convolution_kernel< TType, StaticSize< tSize > >::get(), cugip::separable_convolution_operator< TKernel, tDimension >::operator()(), and cugip::sobel_gradient_kernel().
The documentation for this struct was generated from the following file:
/home/johny/programming/git/MedV4D/extern/cugip/include/cugip/basic_filters/convolution.hpp