CUGIP: cugip::detail::compute_weight< tPatchRadius > Struct Template Reference
cugip::detail::compute_weight< tPatchRadius > Struct Template Reference
#include <nonlocal_means.hpp>
Static Public Member Functions
template<typename TLocator >
static CUGIP_DECL_DEVICE float run (TLocator aOrigin, TLocator aPatchCenter, float aVariance)
template<typename TLocator >
static CUGIP_DECL_DEVICE void run (TLocator aOrigin1, TLocator aPatchCenter1, float &weight1, TLocator aOrigin2, TLocator aPatchCenter2, float &weight2, float aVariance)
Detailed Description
template<int tPatchRadius>
struct cugip::detail::compute_weight< tPatchRadius >
Definition at line 26 of file nonlocal_means.hpp.
Member Function Documentation
template<int tPatchRadius> template<typename TLocator > static CUGIP_DECL_DEVICE float cugip::detail::compute_weight< tPatchRadius >::run (TLocator aOrigin, TLocator aPatchCenter, float aVariance) inline static
Definition at line 30 of file nonlocal_means.hpp.
References CUGIP_DECL_DEVICE, and cugip::sqr().
Referenced by cugip::detail::kernel_nonlocal_means(), cugip::detail::kernel_nonlocal_means2(), and cugip::detail::kernel_nonlocal_means3().
template<int tPatchRadius> template<typename TLocator > static CUGIP_DECL_DEVICE void cugip::detail::compute_weight< tPatchRadius >::run (TLocator aOrigin1, TLocator aPatchCenter1, float & weight1, TLocator aOrigin2, TLocator aPatchCenter2, float & weight2, float aVariance) inline static
Definition at line 43 of file nonlocal_means.hpp.
References CUGIP_GLOBAL, and cugip::sqr().
The documentation for this struct was generated from the following file:
/home/johny/programming/git/MedV4D/extern/cugip/include/cugip/advanced_operations/nonlocal_means.hpp