CUGIP: cugip::ReactionDiffusionRule Struct Reference
cugip::ReactionDiffusionRule Struct Reference
Math
#include <rules.hpp>
Public Types
template<typename T >
using remove_reference = typename std::remove_reference< T >::type
Public Member Functions
template<typename TValue >
CUGIP_DECL_DEVICE float f (const TValue &aValue) const
template<typename TValue >
CUGIP_DECL_DEVICE float g (const TValue &aValue) const
template<typename TNeighborhood >
CUGIP_DECL_DEVICE auto operator() (int aIteration, TNeighborhood aNeighborhood) -> remove_reference< decltype(aNeighborhood[0])> const
Public Attributes
float timestep = 0.2
float alpha = 0.1f
float beta = 0.1f
vect2f_t k = vect2f_t(0.64f, 0.32f)
Detailed Description
Definition at line 506 of file rules.hpp.
Member Typedef Documentation
template<typename T > using cugip::ReactionDiffusionRule::remove_reference = typename std::remove_reference<T>::type
Definition at line 509 of file rules.hpp.
Member Function Documentation
template<typename TValue > CUGIP_DECL_DEVICE float cugip::ReactionDiffusionRule::f (const TValue & aValue) const inline
Definition at line 513 of file rules.hpp.
References CUGIP_DECL_DEVICE, and cugip::sqr().
template<typename TValue > CUGIP_DECL_DEVICE float cugip::ReactionDiffusionRule::g (const TValue & aValue) const inline
Definition at line 520 of file rules.hpp.
References CUGIP_DECL_DEVICE, and cugip::sqr().
template<typename TNeighborhood > CUGIP_DECL_DEVICE auto cugip::ReactionDiffusionRule::operator() (int aIteration, TNeighborhood aNeighborhood) -> remove_reference<decltype(aNeighborhood[0])> const inline
Todo:
global state by reference
Definition at line 529 of file rules.hpp.
References cugip::product().
Member Data Documentation
float cugip::ReactionDiffusionRule::alpha = 0.1f
Definition at line 546 of file rules.hpp.
float cugip::ReactionDiffusionRule::beta = 0.1f
Definition at line 547 of file rules.hpp.
vect2f_t cugip::ReactionDiffusionRule::k = vect2f_t(0.64f, 0.32f)
Definition at line 548 of file rules.hpp.
float cugip::ReactionDiffusionRule::timestep = 0.2
Definition at line 545 of file rules.hpp.
The documentation for this struct was generated from the following file:
/home/johny/programming/git/MedV4D/extern/cugip/include/cugip/cellular_automata/rules.hpp