CUGIP: cugip::compute_diffusion_tensor_ftor Struct Reference
cugip::compute_diffusion_tensor_ftor Struct Reference
#include <coherence_enhancing_diffusion.hpp>
Public Member Functions
template<typename TStructuralTensor >
CUGIP_DECL_HYBRID TStructuralTensor operator() (const TStructuralTensor &aTensor)
Public Attributes
float alpha
float contrast
Static Public Attributes
static constexpr float cKappaEpsilon = 0.00000001f
Detailed Description
Definition at line 75 of file coherence_enhancing_diffusion.hpp.
Member Function Documentation
template<typename TStructuralTensor > CUGIP_DECL_HYBRID TStructuralTensor cugip::compute_diffusion_tensor_ftor::operator() (const TStructuralTensor & aTensor) inline
Definition at line 81 of file coherence_enhancing_diffusion.hpp.
References cugip::compute_structural_tensor_ftor< TGradientVector, TStructuralTensor >::cDimension, cugip::eigen_values(), cugip::eigen_vectors(), cugip::matrix_from_eigen_vectors_and_values(), and cugip::sqr().
Member Data Documentation
float cugip::compute_diffusion_tensor_ftor::alpha
Definition at line 107 of file coherence_enhancing_diffusion.hpp.
constexpr float cugip::compute_diffusion_tensor_ftor::cKappaEpsilon = 0.00000001f static
Definition at line 77 of file coherence_enhancing_diffusion.hpp.
float cugip::compute_diffusion_tensor_ftor::contrast
Definition at line 108 of file coherence_enhancing_diffusion.hpp.
The documentation for this struct was generated from the following file:
/home/johny/programming/git/MedV4D/extern/cugip/include/cugip/advanced_operations/coherence_enhancing_diffusion.hpp