CUGIP: cugip::device_flag_view Struct Reference
cugip::device_flag_view Struct Reference
#include <device_flag.hpp>
Public Types
typedef bool flag_t
Public Member Functions
CUGIP_DECL_HOST void reset_host ()
CUGIP_DECL_DEVICE void reset_device ()
CUGIP_DECL_HOST void set_host ()
CUGIP_DECL_DEVICE void set_device ()
CUGIP_DECL_HOST bool check_host ()
CUGIP_DECL_DEVICE bool check_device ()
Public Attributes
device_ptr< flag_t > mFlag
Detailed Description
Definition at line 7 of file device_flag.hpp.
Member Typedef Documentation
typedef bool cugip::device_flag_view::flag_t
Definition at line 17 of file device_flag.hpp.
Member Function Documentation
CUGIP_DECL_DEVICE bool cugip::device_flag_view::check_device () inline
Definition at line 58 of file device_flag.hpp.
References CUGIP_ASSERT, mFlag, and cugip::device_base_ptr< TType >::p.
CUGIP_DECL_HOST bool cugip::device_flag_view::check_host () inline
Definition at line 51 of file device_flag.hpp.
References CUGIP_ASSERT, CUGIP_DECL_DEVICE, mFlag, and cugip::device_base_ptr< TType >::p.
Referenced by cugip::Push< TGraphData, TPolicy >::compute(), cugip::connected_component_labeling(), cugip::watershed_transformation1(), and cugip::watershed_transformation2().
CUGIP_DECL_DEVICE void cugip::device_flag_view::reset_device () inline
Definition at line 27 of file device_flag.hpp.
References CUGIP_ASSERT, CUGIP_DECL_HOST, mFlag, and cugip::device_base_ptr< TType >::p.
CUGIP_DECL_HOST void cugip::device_flag_view::reset_host () inline
Definition at line 19 of file device_flag.hpp.
References CUGIP_ASSERT, CUGIP_DECL_DEVICE, mFlag, and cugip::device_base_ptr< TType >::p.
Referenced by cugip::Push< TGraphData, TPolicy >::compute(), cugip::connected_component_labeling(), cugip::device_flag::device_flag(), cugip::watershed_transformation1(), and cugip::watershed_transformation2().
CUGIP_DECL_DEVICE void cugip::device_flag_view::set_device () inline
Definition at line 43 of file device_flag.hpp.
References CUGIP_ASSERT, CUGIP_DECL_HOST, mFlag, and cugip::device_base_ptr< TType >::p.
Referenced by cugip::pushImplementation(), and cugip::watershed_evolution_kernel().
CUGIP_DECL_HOST void cugip::device_flag_view::set_host () inline
Definition at line 35 of file device_flag.hpp.
References CUGIP_ASSERT, CUGIP_DECL_DEVICE, mFlag, and cugip::device_base_ptr< TType >::p.
Member Data Documentation
device_ptr<flag_t> cugip::device_flag_view::mFlag
Definition at line 77 of file device_flag.hpp.
Referenced by check_device(), check_host(), cugip::device_flag::device_flag(), reset_device(), reset_host(), set_device(), set_host(), and cugip::device_flag::~device_flag().
The documentation for this struct was generated from the following file:
/home/johny/programming/git/MedV4D/extern/cugip/include/cugip/device_flag.hpp