CUGIP: cugip::TileProcessor< TGraph, TPolicy > Struct Template Reference
cugip::TileProcessor< TGraph, TPolicy > Struct Template Reference
#include <graph_cut_relabeling.hpp>
Public Member Functions
CUGIP_DECL_DEVICE TileProcessor (TGraph &aGraph, ParallelQueueView< int > &aVertices, int *aOffsetScratch, int currentLevel, const TPolicy &aPolicy)
CUGIP_DECL_DEVICE void processTile (int aOffset, int aCount)
CUGIP_DECL_DEVICE int cullNeighbors (int scratchIndex)
CUGIP_DECL_DEVICE void expand (Tile< TGraph > &aTile)
Public Attributes
TGraph & mGraph
ParallelQueueView< int > & mVertices
int * offsetScratch
int mCurrentLevel
const TPolicy & mPolicy
Detailed Description
template<typename TGraph, typename TPolicy>
struct cugip::TileProcessor< TGraph, TPolicy >
Definition at line 455 of file graph_cut_relabeling.hpp.
Constructor & Destructor Documentation
template<typename TGraph, typename TPolicy> CUGIP_DECL_DEVICE cugip::TileProcessor< TGraph, TPolicy >::TileProcessor (TGraph & aGraph, ParallelQueueView< int > & aVertices, int * aOffsetScratch, int currentLevel, const TPolicy & aPolicy) inline
Definition at line 465 of file graph_cut_relabeling.hpp.
References CUGIP_DECL_DEVICE.
Member Function Documentation
template<typename TGraph, typename TPolicy> CUGIP_DECL_DEVICE int cugip::TileProcessor< TGraph, TPolicy >::cullNeighbors (int scratchIndex) inline
Definition at line 556 of file graph_cut_relabeling.hpp.
References CUGIP_DECL_DEVICE.
template<typename TGraph, typename TPolicy> CUGIP_DECL_DEVICE void cugip::TileProcessor< TGraph, TPolicy >::expand (Tile< TGraph > & aTile) inline
Definition at line 577 of file graph_cut_relabeling.hpp.
References cugip::Tile< TGraph >::listLength, cugip::Tile< TGraph >::listProgress, cugip::Tile< TGraph >::listStart, cugip::Tile< TGraph >::prefixSum, and cugip::Tile< TGraph >::progress.
template<typename TGraph, typename TPolicy> CUGIP_DECL_DEVICE void cugip::TileProcessor< TGraph, TPolicy >::processTile (int aOffset, int aCount) inline
Todo:
nema to delat jen jedno vlakno?
Todo:
save to shared memory and then to global
Definition at line 485 of file graph_cut_relabeling.hpp.
References cugip::ParallelQueueView< TType >::allocate(), CUGIP_DECL_DEVICE, cugip::ParallelQueueView< TType >::get_device(), cugip::Tile< TGraph >::getAdjacencyList(), cugip::Tile< TGraph >::listLength, cugip::Tile< TGraph >::load(), cugip::Tile< TGraph >::prefixSum, cugip::Tile< TGraph >::progress, and cugip::Tile< TGraph >::totalCount.
Referenced by cugip::SweepPass< TGraph, TPolicy >::invoke().
Member Data Documentation
template<typename TGraph, typename TPolicy> int cugip::TileProcessor< TGraph, TPolicy >::mCurrentLevel
Definition at line 462 of file graph_cut_relabeling.hpp.
template<typename TGraph, typename TPolicy> TGraph& cugip::TileProcessor< TGraph, TPolicy >::mGraph
Definition at line 457 of file graph_cut_relabeling.hpp.
template<typename TGraph, typename TPolicy> const TPolicy& cugip::TileProcessor< TGraph, TPolicy >::mPolicy
Definition at line 593 of file graph_cut_relabeling.hpp.
template<typename TGraph, typename TPolicy> ParallelQueueView<int>& cugip::TileProcessor< TGraph, TPolicy >::mVertices
Definition at line 458 of file graph_cut_relabeling.hpp.
template<typename TGraph, typename TPolicy> int* cugip::TileProcessor< TGraph, TPolicy >::offsetScratch
Definition at line 460 of file graph_cut_relabeling.hpp.
The documentation for this struct was generated from the following file:
/home/johny/programming/git/MedV4D/extern/cugip/include/cugip/advanced_operations/detail/graph_cut_relabeling.hpp