CUGIP: cugip::MinCut< TGraphData, TPolicy, TTraceObject > Struct Template Reference
cugip::MinCut< TGraphData, TPolicy, TTraceObject > Struct Template Reference
#include <graph_cut_implementation.hpp>
Classes
struct PreflowInit
struct PreflowInit< PreflowInitialization::Default, tDummy >
struct PreflowInit< PreflowInitialization::Push, tDummy >
Static Public Member Functions
static float compute (TGraphData &aGraph, ParallelQueueView< int > &aVertexQueue, thrust::host_vector< int > &aLevelStarts, TPolicy &aPolicy, TTraceObject &aTraceObject)
static void push_through_tlinks_from_source (TGraphData &aGraph)
static void push_through_tlinks_to_sink (TGraphData &aGraph)
static float computeFlowThroughSinkFrontier (TGraphData &aGraph)
Detailed Description
template<typename TGraphData, typename TPolicy, typename TTraceObject>
struct cugip::MinCut< TGraphData, TPolicy, TTraceObject >
Definition at line 66 of file graph_cut_implementation.hpp.
Member Function Documentation
template<typename TGraphData, typename TPolicy, typename TTraceObject> static float cugip::MinCut< TGraphData, TPolicy, TTraceObject >::compute (TGraphData & aGraph, ParallelQueueView< int > & aVertexQueue, thrust::host_vector< int > & aLevelStarts, TPolicy & aPolicy, TTraceObject & aTraceObject) inline static
Definition at line 123 of file graph_cut_implementation.hpp.
References cugip::Push< TGraphData, TPolicy >::compute(), cugip::Relabel< TGraphData, TPolicy >::compute(), cugip::MinCut< TGraphData, TPolicy, TTraceObject >::computeFlowThroughSinkFrontier(), and CUGIP_DPRINT.
Referenced by cugip::MinimalGraphCutComputation< TGraph >::run().
template<typename TGraphData, typename TPolicy, typename TTraceObject> static float cugip::MinCut< TGraphData, TPolicy, TTraceObject >::computeFlowThroughSinkFrontier (TGraphData & aGraph) inline static
Definition at line 229 of file graph_cut_implementation.hpp.
References cugip::MinCut< TGraphData, TPolicy, TTraceObject >::push_through_tlinks_to_sink(), and cugip::reduce().
Referenced by cugip::MinCut< TGraphData, TPolicy, TTraceObject >::compute().
template<typename TGraphData, typename TPolicy, typename TTraceObject> static void cugip::MinCut< TGraphData, TPolicy, TTraceObject >::push_through_tlinks_from_source (TGraphData & aGraph) inline static
Definition at line 201 of file graph_cut_implementation.hpp.
References CUGIP_DPRINT.
template<typename TGraphData, typename TPolicy, typename TTraceObject> static void cugip::MinCut< TGraphData, TPolicy, TTraceObject >::push_through_tlinks_to_sink (TGraphData & aGraph) inline static
Definition at line 215 of file graph_cut_implementation.hpp.
Referenced by cugip::MinCut< TGraphData, TPolicy, TTraceObject >::computeFlowThroughSinkFrontier().
The documentation for this struct was generated from the following file:
/home/johny/programming/git/MedV4D/extern/cugip/include/cugip/advanced_operations/detail/graph_cut_implementation.hpp