CUGIP: cugip::device_flag Struct Reference
cugip::device_flag Struct Reference
#include <device_flag.hpp>
Public Types
typedef bool flag_t
Public Types inherited from cugip::device_flag_view
typedef bool flag_t
Public Member Functions
device_flag ()
~device_flag ()
device_flag_view & view ()
Public Member Functions inherited from cugip::device_flag_view
CUGIP_DECL_HOST void reset_host ()
CUGIP_DECL_DEVICE void reset_device ()
CUGIP_DECL_HOST void set_host ()
CUGIP_DECL_DEVICE void set_device ()
CUGIP_DECL_HOST bool check_host ()
CUGIP_DECL_DEVICE bool check_device ()
Private Member Functions
device_flag (const device_flag &)
device_flag & operator= (const device_flag &)
Additional Inherited Members
Public Attributes inherited from cugip::device_flag_view
device_ptr< flag_t > mFlag
Detailed Description
Definition at line 80 of file device_flag.hpp.
Member Typedef Documentation
typedef bool cugip::device_flag::flag_t
Definition at line 82 of file device_flag.hpp.
Constructor & Destructor Documentation
cugip::device_flag::device_flag () inline
Definition at line 83 of file device_flag.hpp.
References cugip::device_flag_view::mFlag, and cugip::device_flag_view::reset_host().
cugip::device_flag::~device_flag () inline
Definition at line 91 of file device_flag.hpp.
References CUGIP_ASSERT, cugip::device_base_ptr< TType >::get(), and cugip::device_flag_view::mFlag.
cugip::device_flag::device_flag (const device_flag &) private
Member Function Documentation
device_flag& cugip::device_flag::operator= (const device_flag &) private
device_flag_view& cugip::device_flag::view () inline
Definition at line 98 of file device_flag.hpp.
Referenced by cugip::Push< TGraphData, TPolicy >::compute(), cugip::connected_component_labeling(), cugip::watershed_transformation1(), and cugip::watershed_transformation2().
The documentation for this struct was generated from the following file:
/home/johny/programming/git/MedV4D/extern/cugip/include/cugip/device_flag.hpp