CUGIP: cugip::detail::scan_neighborhood_for_connections_ftor< TInputType, TLUT > Struct Template Reference
cugip::detail::scan_neighborhood_for_connections_ftor< TInputType, TLUT > Struct Template Reference
#include <connected_component_labeling.hpp>
Public Member Functions
scan_neighborhood_for_connections_ftor (TLUT aLUT, device_flag_view aLutUpdatedFlag)
template<typename TLocator >
CUGIP_DECL_HYBRID TInputType minValidLabel (TLocator aLocator, TInputType aCurrent, const dimension_2d_tag &)
template<typename TLocator >
CUGIP_DECL_DEVICE void operator() (TLocator aLocator)
Public Attributes
TLUT mLUT
device_flag_view mLutUpdatedFlag
Detailed Description
template<typename TInputType, typename TLUT>
struct cugip::detail::scan_neighborhood_for_connections_ftor< TInputType, TLUT >
Definition at line 42 of file connected_component_labeling.hpp.
Constructor & Destructor Documentation
template<typename TInputType , typename TLUT > cugip::detail::scan_neighborhood_for_connections_ftor< TInputType, TLUT >::scan_neighborhood_for_connections_ftor (TLUT aLUT, device_flag_view aLutUpdatedFlag) inline
Definition at line 44 of file connected_component_labeling.hpp.
References CUGIP_DECL_HYBRID.
Member Function Documentation
template<typename TInputType , typename TLUT > template<typename TLocator > CUGIP_DECL_HYBRID TInputType cugip::detail::scan_neighborhood_for_connections_ftor< TInputType, TLUT >::minValidLabel (TLocator aLocator, TInputType aCurrent, const dimension_2d_tag &) inline
Definition at line 50 of file connected_component_labeling.hpp.
References CUGIP_DECL_DEVICE, and cugip::get().
Referenced by cugip::detail::scan_neighborhood_for_connections_ftor< TInputType, TLUT >::operator()().
template<typename TInputType , typename TLUT > template<typename TLocator > CUGIP_DECL_DEVICE void cugip::detail::scan_neighborhood_for_connections_ftor< TInputType, TLUT >::operator() (TLocator aLocator) inline
Todo:
hybrid
Definition at line 71 of file connected_component_labeling.hpp.
References cugip::detail::scan_neighborhood_for_connections_ftor< TInputType, TLUT >::minValidLabel(), cugip::detail::scan_neighborhood_for_connections_ftor< TInputType, TLUT >::mLUT, cugip::detail::scan_neighborhood_for_connections_ftor< TInputType, TLUT >::mLutUpdatedFlag, and cugip::device_flag_view::set_device().
Member Data Documentation
template<typename TInputType , typename TLUT > TLUT cugip::detail::scan_neighborhood_for_connections_ftor< TInputType, TLUT >::mLUT
Definition at line 84 of file connected_component_labeling.hpp.
Referenced by cugip::detail::scan_neighborhood_for_connections_ftor< TInputType, TLUT >::operator()().
template<typename TInputType , typename TLUT > device_flag_view cugip::detail::scan_neighborhood_for_connections_ftor< TInputType, TLUT >::mLutUpdatedFlag
Definition at line 85 of file connected_component_labeling.hpp.
Referenced by cugip::detail::scan_neighborhood_for_connections_ftor< TInputType, TLUT >::operator()().
The documentation for this struct was generated from the following file:
/home/johny/programming/git/MedV4D/extern/cugip/include/cugip/basic_filters/connected_component_labeling.hpp